public enum aqzf {
    ELIGIBLE,
    INELIGIBLE_DENYLISTED,
    INELIGIBLE_FULL_MIN_SDK,
    INELIGIBLE_KV_NO_AGENT,
    INELIGIBLE_KV_FULL_ONLY,
    INELIGIBLE_SIDEWINDER,
    INELIGIBLE_DOLLY_CONSENT,
    INELIGIBLE_PACKAGE_CONSENT,
    INELIGIBLE_FIRST_PARTY,
    INELIGIBLE_GCM,
    INELIGIBLE_UNSELECTED_CLOUD_RESTORE;

}

