public enum beuf {
    LOADING_SCREEN,
    ERROR_SCREEN,
    PASSWORDS_SCREEN,
    SEARCH_SCREEN,
    ADD_SCREEN,
    SETTINGS_SCREEN,
    DETAIL_SCREEN,
    EDIT_SCREEN,
    PICKER_SCREEN,
    CHECKUP_SCREEN,
    PASSKEY_WIZARD_SCREEN,
    PASSKEY_WIZARD_DEMO_ENTRY_SCREEN,
    PASSKEY_WIZARD_DEMO_SCREEN,
    IMPORT_FROM_FILE_SCREEN,
    IMPORT_CREDENTIALS_SCREEN,
    MOVE_PASSWORDS_SCREEN,
    HOME_SCREEN,
    REAUTH_SCREEN,
    NONE;

}

