public enum bewg {
    NOTE_CHAR_LIMIT_EXCEEDS,
    USERNAME_CHAR_LIMIT_EXCEEDS,
    PASSWORD_CHAR_LIMIT_EXCEEDS,
    URL_CHAR_LIMIT_EXCEEDS,
    PASSWORD_IS_EMPTY,
    URL_AND_USERNAME_ARE_EMPTY,
    URL_IS_EMPTY,
    URL_CONTAINS_NON_ASCII_CHARS,
    URL_IS_NOT_VALID_SIGN_ON_REALM,
    CONFLICT_WITH_PASSWORD_IN_IMPORTED_FILE,
    CONFLICT_WITH_PASSWORD_IN_ACCOUNT;

    static {
        bewg.l = arr_bewg;
        ibsn.a(arr_bewg);
    }
}

