public enum blzx {
    CTAP1_ERR_SUCCESS(0),
    CTAP1_ERR_INVALID_COMMAND(1),
    CTAP1_ERR_INVALID_PARAMETER(2),
    CTAP1_ERR_INVALID_LENGTH(3),
    CTAP1_ERR_INVALID_SEQ(4),
    CTAP1_ERR_TIMEOUT(5),
    CTAP1_ERR_CHANNEL_BUSY(6),
    CTAP1_ERR_LOCK_REQUIRED(10),
    CTAP1_ERR_INVALID_CHANNEL(11),
    CTAP2_ERR_CBOR_PARSING(16),
    CTAP2_ERR_CBOR_UNEXPECTED_TYPE(17),
    CTAP2_ERR_INVALID_CBOR(18),
    CTAP2_ERR_INVALID_CBOR_TYPE(19),
    CTAP2_ERR_MISSING_PARAMETER(20),
    CTAP2_ERR_LIMIT_EXCEEDED(21),
    CTAP2_ERR_UNSUPPORTED_EXTENSION(22),
    CTAP2_ERR_TOO_MANY_ELEMENTS(23),
    CTAP2_ERR_EXTENSION_NOT_SUPPORTED(24),
    CTAP2_ERR_CREDENTIAL_EXCLUDED(25),
    CTAP2_ERR_CREDENTIAL_NOT_VALID(0x20),
    CTAP2_ERR_PROCESSING(33),
    CTAP2_ERR_INVALID_CREDENTIAL(34),
    CTAP2_ERR_USER_ACTION_PENDING(35),
    CTAP2_ERR_OPERATION_PENDING(36),
    CTAP2_ERR_NO_OPERATIONS(37),
    CTAP2_ERR_UNSUPPORTED_ALGORITHM(38),
    CTAP2_ERR_OPERATION_DENIED(39),
    CTAP2_ERR_KEY_STORE_FULL(40),
    CTAP2_ERR_NOT_BUSY(41),
    CTAP2_ERR_NO_OPERATION_PENDING(42),
    CTAP2_ERR_UNSUPPORTED_OPTION(43),
    CTAP2_ERR_INVALID_OPTION(44),
    CTAP2_ERR_KEEPALIVE_CANCEL(45),
    CTAP2_ERR_NO_CREDENTIALS(46),
    CTAP2_ERR_USER_ACTION_TIMEOUT(0x2F),
    CTAP2_ERR_NOT_ALLOWED(0x30),
    CTAP2_ERR_PIN_INVALID(49),
    CTAP2_ERR_PIN_BLOCKED(50),
    CTAP2_ERR_PIN_AUTH_INVALID(51),
    CTAP2_ERR_PIN_AUTH_BLOCKED(52),
    CTAP2_ERR_PIN_NOT_SET(53),
    CTAP2_ERR_PIN_REQUIRED(54),
    CTAP2_ERR_PIN_POLICY_VIOLATION(55),
    CTAP2_ERR_PIN_TOKEN_EXPIRED(56),
    CTAP2_ERR_REQUEST_TOO_LARGE(57),
    CTAP1_ERR_OTHER(0x7F),
    CTAP2_ERR_SPEC_LAST(-33),
    CTAP2_ERR_EXTENSION_FIRST((byte)0xE0),
    CTAP2_ERR_EXTENSION_LAST(-17),
    CTAP2_ERR_VENDOR_FIRST(-16),
    CTAP2_ERR_VENDOR_LAST(-1);

    public final byte Z;

    private blzx(byte b) {
        this.Z = b;
    }

    public static blzx a(byte b) {
        blzx[] arr_blzx = blzx.values();
        for(int v = 0; v < arr_blzx.length; ++v) {
            blzx blzx0 = arr_blzx[v];
            if(blzx0.Z == b) {
                return blzx0;
            }
        }
        return blzx.T;
    }
}

