import com.google.android.gms.fido.fido2.api.common.AuthenticatorErrorResponse;
import com.google.android.gms.fido.fido2.api.common.ErrorCode;

public final class bmhw extends aztk {
    public static final AuthenticatorErrorResponse A;
    public static final AuthenticatorErrorResponse B;
    public static final AuthenticatorErrorResponse C;
    public static final AuthenticatorErrorResponse D;
    public static final AuthenticatorErrorResponse E;
    public static final AuthenticatorErrorResponse F;
    public static final ggeo G;
    public static final AuthenticatorErrorResponse a;
    public static final AuthenticatorErrorResponse b;
    public static final AuthenticatorErrorResponse c;
    public static final AuthenticatorErrorResponse d;
    public static final AuthenticatorErrorResponse e;
    public static final AuthenticatorErrorResponse f;
    public static final AuthenticatorErrorResponse g;
    public static final AuthenticatorErrorResponse h;
    public static final AuthenticatorErrorResponse i;
    public static final AuthenticatorErrorResponse j;
    public static final AuthenticatorErrorResponse k;
    public static final AuthenticatorErrorResponse l;
    public static final AuthenticatorErrorResponse m;
    public static final AuthenticatorErrorResponse n;
    public static final AuthenticatorErrorResponse o;
    public static final AuthenticatorErrorResponse p;
    public static final AuthenticatorErrorResponse q;
    public static final AuthenticatorErrorResponse r;
    public static final AuthenticatorErrorResponse s;
    public static final AuthenticatorErrorResponse t;
    public static final AuthenticatorErrorResponse u;
    public static final AuthenticatorErrorResponse v;
    public static final AuthenticatorErrorResponse w;
    public static final AuthenticatorErrorResponse x;
    public static final AuthenticatorErrorResponse y;
    public static final AuthenticatorErrorResponse z;

    static {
        bmhb bmhb0 = new bmhb();
        bmhb0.b(ErrorCode.a);
        AuthenticatorErrorResponse authenticatorErrorResponse0 = bmhb0.a();
        bmhw.a = authenticatorErrorResponse0;
        bmhb bmhb1 = new bmhb();
        bmhb1.b(ErrorCode.b);
        AuthenticatorErrorResponse authenticatorErrorResponse1 = bmhb1.a();
        bmhw.b = authenticatorErrorResponse1;
        bmhb bmhb2 = new bmhb();
        bmhb2.b(ErrorCode.c);
        AuthenticatorErrorResponse authenticatorErrorResponse2 = bmhb2.a();
        bmhw.c = authenticatorErrorResponse2;
        bmhb bmhb3 = new bmhb();
        bmhb3.b(ErrorCode.d);
        AuthenticatorErrorResponse authenticatorErrorResponse3 = bmhb3.a();
        bmhw.d = authenticatorErrorResponse3;
        bmhb bmhb4 = new bmhb();
        bmhb4.b(ErrorCode.e);
        AuthenticatorErrorResponse authenticatorErrorResponse4 = bmhb4.a();
        bmhw.e = authenticatorErrorResponse4;
        bmhb bmhb5 = new bmhb();
        bmhb5.b(ErrorCode.f);
        AuthenticatorErrorResponse authenticatorErrorResponse5 = bmhb5.a();
        bmhw.f = authenticatorErrorResponse5;
        bmhb bmhb6 = new bmhb();
        bmhb6.b(ErrorCode.g);
        AuthenticatorErrorResponse authenticatorErrorResponse6 = bmhb6.a();
        bmhw.g = authenticatorErrorResponse6;
        bmhb bmhb7 = new bmhb();
        bmhb7.b(ErrorCode.h);
        AuthenticatorErrorResponse authenticatorErrorResponse7 = bmhb7.a();
        bmhw.h = authenticatorErrorResponse7;
        bmhb bmhb8 = new bmhb();
        bmhb8.b(ErrorCode.i);
        AuthenticatorErrorResponse authenticatorErrorResponse8 = bmhb8.a();
        bmhw.i = authenticatorErrorResponse8;
        bmhb bmhb9 = new bmhb();
        bmhb9.b(ErrorCode.j);
        AuthenticatorErrorResponse authenticatorErrorResponse9 = bmhb9.a();
        bmhw.j = authenticatorErrorResponse9;
        bmhb bmhb10 = new bmhb();
        bmhb10.b(ErrorCode.k);
        AuthenticatorErrorResponse authenticatorErrorResponse10 = bmhb10.a();
        bmhw.k = authenticatorErrorResponse10;
        bmhb bmhb11 = new bmhb();
        bmhb11.b(ErrorCode.l);
        AuthenticatorErrorResponse authenticatorErrorResponse11 = bmhb11.a();
        bmhw.l = authenticatorErrorResponse11;
        bmhb bmhb12 = new bmhb();
        bmhb12.b(ErrorCode.b);
        bmhb12.a = "A request is already pending.";
        AuthenticatorErrorResponse authenticatorErrorResponse12 = bmhb12.a();
        bmhw.m = authenticatorErrorResponse12;
        bmhb bmhb13 = new bmhb();
        bmhb13.b(ErrorCode.c);
        bmhb13.a = "This is an Invalid Domain.";
        AuthenticatorErrorResponse authenticatorErrorResponse13 = bmhb13.a();
        bmhw.n = authenticatorErrorResponse13;
        bmhb bmhb14 = new bmhb();
        bmhb14.b(ErrorCode.b);
        bmhb14.a = "The user attempted to register an authenticator that contains one of the credentials already registered with the relying party.";
        AuthenticatorErrorResponse authenticatorErrorResponse14 = bmhb14.a();
        bmhw.o = authenticatorErrorResponse14;
        bmhb bmhb15 = new bmhb();
        bmhb15.b(ErrorCode.b);
        bmhb15.a = "The user attempted to use an authenticator that recognized none of the provided credentials.";
        AuthenticatorErrorResponse authenticatorErrorResponse15 = bmhb15.a();
        bmhw.p = authenticatorErrorResponse15;
        bmhb bmhb16 = new bmhb();
        bmhb16.b(ErrorCode.b);
        bmhb16.a = "Internal key storage is full for the given authenticator. Please delete some keys on your authenticator to create new ones.";
        AuthenticatorErrorResponse authenticatorErrorResponse16 = bmhb16.a();
        bmhw.q = authenticatorErrorResponse16;
        bmhb bmhb17 = new bmhb();
        bmhb17.b(ErrorCode.a);
        bmhb17.a = "Not implemented.";
        AuthenticatorErrorResponse authenticatorErrorResponse17 = bmhb17.a();
        bmhw.r = authenticatorErrorResponse17;
        bmhb bmhb18 = new bmhb();
        bmhb18.b(ErrorCode.a);
        bmhb18.a = "Resident credentials or empty \'allowCredentials\' lists are not supported at this time.";
        AuthenticatorErrorResponse authenticatorErrorResponse18 = bmhb18.a();
        bmhw.s = authenticatorErrorResponse18;
        bmhb bmhb19 = new bmhb();
        bmhb19.b(ErrorCode.a);
        bmhb19.a = "The specified `userVerification` requirement cannot be fulfilled by this device unless the device is secured with a screen lock.";
        AuthenticatorErrorResponse authenticatorErrorResponse19 = bmhb19.a();
        bmhw.t = authenticatorErrorResponse19;
        bmhb bmhb20 = new bmhb();
        bmhb20.b(ErrorCode.a);
        bmhb20.a = "None of the algorithms specified in `pubKeyCredParams` are supported by this device.";
        AuthenticatorErrorResponse authenticatorErrorResponse20 = bmhb20.a();
        bmhw.u = authenticatorErrorResponse20;
        bmhb bmhb21 = new bmhb();
        bmhb21.b(ErrorCode.a);
        bmhb21.a = "Use of an empty `allowCredentials` list is not supported on this device.";
        AuthenticatorErrorResponse authenticatorErrorResponse21 = bmhb21.a();
        bmhw.v = authenticatorErrorResponse21;
        bmhb bmhb22 = new bmhb();
        bmhb22.b(ErrorCode.k);
        bmhb22.a = "User verification is cancelled by the user.";
        AuthenticatorErrorResponse authenticatorErrorResponse22 = bmhb22.a();
        bmhw.w = authenticatorErrorResponse22;
        bmhb bmhb23 = new bmhb();
        bmhb23.b(ErrorCode.k);
        bmhb23.a = "Error occurred while using this authenticator.";
        AuthenticatorErrorResponse authenticatorErrorResponse23 = bmhb23.a();
        bmhw.x = authenticatorErrorResponse23;
        bmhb bmhb24 = new bmhb();
        bmhb24.b(ErrorCode.a);
        bmhb24.a = "FIDO2 API is not supported on devices below N";
        AuthenticatorErrorResponse authenticatorErrorResponse24 = bmhb24.a();
        bmhw.y = authenticatorErrorResponse24;
        bmhb bmhb25 = new bmhb();
        bmhb25.b(ErrorCode.a);
        bmhb25.a = "RpId is not valid.";
        AuthenticatorErrorResponse authenticatorErrorResponse25 = bmhb25.a();
        bmhw.z = authenticatorErrorResponse25;
        bmhb bmhb26 = new bmhb();
        bmhb26.b(ErrorCode.g);
        bmhb26.a = "Error decoding the request.";
        AuthenticatorErrorResponse authenticatorErrorResponse26 = bmhb26.a();
        bmhw.A = authenticatorErrorResponse26;
        bmhb bmhb27 = new bmhb();
        bmhb27.b(ErrorCode.a);
        bmhb27.a = "Invalid or unsupported command.";
        AuthenticatorErrorResponse authenticatorErrorResponse27 = bmhb27.a();
        bmhw.B = authenticatorErrorResponse27;
        bmhb bmhb28 = new bmhb();
        bmhb28.b(ErrorCode.j);
        bmhb28.a = "An error occurred during signing.";
        AuthenticatorErrorResponse authenticatorErrorResponse28 = bmhb28.a();
        bmhw.C = authenticatorErrorResponse28;
        bmhb bmhb29 = new bmhb();
        bmhb29.b(ErrorCode.h);
        bmhb29.a = "An error occurred with a cryptauth operation";
        AuthenticatorErrorResponse authenticatorErrorResponse29 = bmhb29.a();
        bmhw.D = authenticatorErrorResponse29;
        bmhb bmhb30 = new bmhb();
        bmhb30.b(ErrorCode.i);
        bmhb30.a = "PIN policy violation.";
        AuthenticatorErrorResponse authenticatorErrorResponse30 = bmhb30.a();
        bmhw.E = authenticatorErrorResponse30;
        bmhb bmhb31 = new bmhb();
        bmhb31.b(ErrorCode.i);
        bmhb31.a = "PIN authentication using pinUvAuthToken blocked. Requires power cycle to reset.";
        AuthenticatorErrorResponse authenticatorErrorResponse31 = bmhb31.a();
        bmhw.F = authenticatorErrorResponse31;
        ggek ggek0 = new ggek();
        ggek0.i(Integer.valueOf(34000), authenticatorErrorResponse0);
        ggek0.i(Integer.valueOf(34001), authenticatorErrorResponse1);
        ggek0.i(Integer.valueOf(34002), authenticatorErrorResponse2);
        ggek0.i(Integer.valueOf(34003), authenticatorErrorResponse3);
        ggek0.i(Integer.valueOf(34004), authenticatorErrorResponse4);
        ggek0.i(Integer.valueOf(34005), authenticatorErrorResponse5);
        ggek0.i(Integer.valueOf(34006), authenticatorErrorResponse6);
        ggek0.i(Integer.valueOf(34007), authenticatorErrorResponse7);
        ggek0.i(Integer.valueOf(34008), authenticatorErrorResponse8);
        ggek0.i(Integer.valueOf(34009), authenticatorErrorResponse9);
        ggek0.i(Integer.valueOf(34010), authenticatorErrorResponse10);
        ggek0.i(Integer.valueOf(34011), authenticatorErrorResponse11);
        ggek0.i(Integer.valueOf(34012), authenticatorErrorResponse12);
        ggek0.i(Integer.valueOf(34013), authenticatorErrorResponse13);
        ggek0.i(Integer.valueOf(34014), authenticatorErrorResponse14);
        ggek0.i(Integer.valueOf(34029), authenticatorErrorResponse16);
        ggek0.i(Integer.valueOf(0x84DF), authenticatorErrorResponse15);
        ggek0.i(Integer.valueOf(0x84E0), authenticatorErrorResponse17);
        ggek0.i(Integer.valueOf(34017), authenticatorErrorResponse18);
        ggek0.i(Integer.valueOf(34018), authenticatorErrorResponse19);
        ggek0.i(Integer.valueOf(34019), authenticatorErrorResponse20);
        ggek0.i(Integer.valueOf(34020), authenticatorErrorResponse21);
        ggek0.i(Integer.valueOf(34021), authenticatorErrorResponse22);
        ggek0.i(Integer.valueOf(34022), authenticatorErrorResponse23);
        ggek0.i(Integer.valueOf(34023), authenticatorErrorResponse24);
        ggek0.i(Integer.valueOf(34024), authenticatorErrorResponse25);
        ggek0.i(Integer.valueOf(34025), authenticatorErrorResponse26);
        ggek0.i(Integer.valueOf(34026), authenticatorErrorResponse27);
        ggek0.i(Integer.valueOf(34027), authenticatorErrorResponse28);
        ggek0.i(Integer.valueOf(34028), authenticatorErrorResponse29);
        ggek0.i(Integer.valueOf(34030), authenticatorErrorResponse30);
        ggek0.i(Integer.valueOf(0x84EF), authenticatorErrorResponse31);
        bmhw.G = ggek0.b();
    }

    public static AuthenticatorErrorResponse a(int v) {
        ggeo ggeo0 = bmhw.G;
        Integer integer0 = v;
        if(ggeo0.containsKey(integer0)) {
            return (AuthenticatorErrorResponse)ggeo0.get(integer0);
        }
        bmhb bmhb0 = new bmhb();
        bmhb0.b(ErrorCode.h);
        return bmhb0.a();
    }
}

