public enum bmle {
    NONE,
    TUNNEL_SERVER_CONNECT_FAILED,
    HANDSHAKE_FAILED,
    DECRYPT_FAILURE,
    ENCRYPT_FAILURE,
    INVALID_CBOR,
    INVALID_CTAP,
    INTERNAL_ERROR,
    INVALID_MESSAGE_TYPE_BYTE,
    UNEXPECTED_EOF,
    EOF_WHILE_PROCESSING,
    AUTHENTICATOR_SELECTION_RECEIVED,
    INVALID_JSON,
    UNSUPPORTED_JSON_REQUEST_TYPE;

}

