public enum bmqk {
    CREATE_CLIENT_PIN,
    CONFIRM_CLIENT_PIN,
    ACCEPT_CLIENT_PIN,
    CLIENT_PIN_MISMATCH,
    CLIENT_PIN_SUCCESS,
    CONFIRM_CLIENT_PIN_SUCCESS,
    CREATE_CLIENT_PIN_SUCCESS,
    CLIENT_PIN_FAILURE,
    UNKNOWN;

}

