public enum bnaf {
    UNKNOWN,
    FIDO2_API,
    FIDO2_PRIVILEGED_API,
    FIDO2_ZERO_PARTY,
    HYBRID_ACTIVITY,
    HYBRID_CLIENT,
    HYBRID_AUTHENTICATOR,
    HYBRID_FCM_EVENT,
    HYBRID_DATA_TRANSFER,
    U2F_API,
    U2F_PRIVILEGED_API,
    U2F_ZERO_PARTY,
    TARGET_DIRECT_TRANSFER,
    SOURCE_DIRECT_TRANSFER,
    FIDO_AUTOENROLLMENT_V1,
    FIDO_AUTOENROLLMENT_V2,
    FIDO_KEY_VALIDITY_CHECK_V1,
    FIDO_KEY_VALIDITY_CHECK_V2,
    PAASK;

}

