public enum bxnz implements hfub {
    VIEW_NAME_DEFAULT_VIEW_NAME(0),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_INITIAL_LOADING(1),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_WARM_WELCOME(2),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_MULTI_CREDENTIAL(3),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_SINGLE_CREDENTIAL(4),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_CONFIRMATION(5),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_SELECT_PHONE_NUMBER(6),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_UNVERIFIED_APP_WARNING(7),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_ZUUL_INTRO(8),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_SELECT_ACCOUNT_FOR_ZUUL_KEY_RETRIEVAL(9),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_NO_PASSWORD_AFTER_ZUUL_KEY_RETRIEVAL(10),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_SINGLE_PASSKEY(11),
    VIEW_NAME_GIS_ASSISTED_SIGN_IN_SINGLE_HYBRID(12),
    VIEW_NAME_GIS_ASSISTED_CHROME_AFFILIATION_WARNING(13),
    VIEW_NAME_GIS_GOOGLE_SIGN_IN_ACCOUNT_CHOOSER(21),
    VIEW_NAME_GIS_GOOGLE_SIGN_IN_CONSENT(22),
    VIEW_NAME_GIS_GOOGLE_SIGN_IN_UNVERIFIED_APP_WARNING(23),
    VIEW_NAME_GIS_GOOGLE_SIGN_IN_SELECT_PHONE_NUMBER(24),
    VIEW_NAME_GIS_GOOGLE_SIGN_IN_VERIFIED_PHONE_NUMBER_CONSENT(25),
    VIEW_NAME_GIS_AUTHORIZATION_INITIAL_LOADING(41),
    VIEW_NAME_GIS_AUTHORIZATION_ACCOUNT_CHOOSER(42),
    VIEW_NAME_GIS_AUTHORIZATION_CONSENT(43),
    VIEW_NAME_GIS_PASSWORD_SAVING_LOADING(61),
    VIEW_NAME_GIS_PASSWORD_SAVING_CONFIRMATION(62),
    VIEW_NAME_GIS_PASSWORD_SAVING_ACCOUNT_SELECTION(0x3F),
    VIEW_NAME_GIS_PASSWORD_SAVING_ZUUL_INTRO(0x40),
    VIEW_NAME_GIS_SAVE_ACCOUNT_LINKING_TOKEN_ACCOUNT_CHOOSER(81),
    VIEW_NAME_GIS_SAVE_ACCOUNT_LINKING_TOKEN_LOADING(82),
    VIEW_NAME_GIS_SAVE_ACCOUNT_LINKING_TOKEN_ACTIVITY_GOOGLE_CONSENT(83),
    VIEW_NAME_GIS_PHONE_NUMBER_HINT(101),
    VIEW_NAME_FIDO_AUTHENTICATION_PASSKEYS_NOT_FOUND(0x79),
    VIEW_NAME_FIDO_AUTHENTICATION_PASSKEYS_AUTHENTICATION_CONSENT(0x7A),
    VIEW_NAME_FIDO_AUTHENTICATION_PASSKEYS_SINGLE_SELECTION(0x7B),
    VIEW_NAME_FIDO_AUTHENTICATION_PASSKEYS_MULTI_SELECTION(0x7C),
    VIEW_NAME_FIDO_AUTHENTICATION_ERROR(0x7D),
    VIEW_NAME_FIDO_AUTHENTICATION_BIOMETRIC_PROMPT(0x7E),
    VIEW_NAME_FIDO_REGISTRATION_ACCOUNT_SELECTION(0x8D),
    VIEW_NAME_FIDO_REGISTRATION_CREATION_CONSENT(0x8E),
    VIEW_NAME_FIDO_REGISTRATION_CREATION(0x8F),
    VIEW_NAME_FIDO_REGISTRATION_ERROR(0x90),
    VIEW_NAME_FIDO_REGISTRATION_BIOMETRIC_PROMPT(0x91),
    VIEW_NAME_FIDO_REGISTRATION_NO_LSKF_ERROR(0x92),
    VIEW_NAME_FIDO_REGISTRATION_NO_GOOGLE_ACCOUNT_ERROR(0x93),
    VIEW_NAME_GET_VERIFIABLE_CREDENTIAL_LOADING(0xA1);

    public final int S;

    private bxnz(int v1) {
        this.S = v1;
    }

    @Override  // hfub
    public final int a() {
        return this.S;
    }

    @Override
    public final String toString() {
        return Integer.toString(this.S);
    }
}

