public enum byak {
    UI_EVENT_UNKNOWN,
    GET_CRED_PROVIDER_ACTIVITY_NOT_APPLICABLE,
    GET_CRED_PROVIDER_ACTIVITY_READY_TO_LAUNCH,
    GET_CRED_PROVIDER_ACTIVITY_PENDING,
    GET_CRED_REMOTE_SNACKBAR_SCREEN,
    GET_CRED_EMPTY_AUTH_SNACKBAR_SCREEN,
    GET_CRED_PRIMARY_SELECTION_SCREEN,
    GET_CRED_ALL_SIGN_IN_OPTION_SCREEN,
    GET_CRED_BIOMETRIC_FLOW_LAUNCHED,
    CREATE_CRED_BOTTOMSHEET,
    CREATE_CRED_PROVIDER_ACTIVITY_NOT_APPLICABLE,
    CREATE_CRED_PROVIDER_ACTIVITY_READY_TO_LAUNCH,
    CREATE_CRED_PROVIDER_ACTIVITY_PENDING,
    CREATE_CRED_CREATION_OPTION_SELECTION_SCREEN,
    CREATE_CRED_MORE_OPTIONS_SELECTION_SCREEN,
    CREATE_CRED_EXTERNAL_ONLY_SCREEN,
    CREATE_CRED_BIOMETRIC_FLOW_LAUNCHED,
    CREATE_CRED_MORE_OPTIONS_ROW_INTRO_SCREEN;

    static {
        byak.s = arr_byak;
        ibsn.a(arr_byak);
    }
}

