public final class byij {
    public final long A;
    public final long B;
    public final long C;
    public final jeu D;
    public final jdz E;
    public final long F;
    public final long G;
    public final long H;
    public final jeu I;
    public final jdz J;
    public final long K;
    public final long L;
    public final long M;
    public final jeu N;
    public final jdz O;
    public final long P;
    public final long Q;
    public final long R;
    public final jeu S;
    public final jdz T;
    public final long U;
    public final long V;
    public final long W;
    public final jeu X;
    public final jdz Y;
    public final long Z;
    public final jdz a;
    public final long aa;
    public final long ab;
    public final jeu ac;
    public final jdz ad;
    public final long ae;
    public final long af;
    public final long ag;
    public final jeu ah;
    public final jdz ai;
    public final long aj;
    public final long ak;
    public final long al;
    public final jeu am;
    public final jdz an;
    public final long ao;
    public final long ap;
    public final long aq;
    public final jeu ar;
    public final jdz as;
    public final long at;
    public final long au;
    public final long av;
    public final jeu aw;
    public final long b;
    public final long c;
    public final long d;
    public final jeu e;
    public final jdz f;
    public final long g;
    public final long h;
    public final long i;
    public final jeu j;
    public final jdz k;
    public final long l;
    public final long m;
    public final long n;
    public final jeu o;
    public final jdz p;
    public final long q;
    public final long r;
    public final long s;
    public final jeu t;
    public final jdz u;
    public final long v;
    public final long w;
    public final long x;
    public final jeu y;
    public final jdz z;

    public byij(byin byin0) {
        this.a = byin0.d;
        this.b = jlq.c(24.0);
        this.c = jlq.e(16);
        this.d = jlq.c(0.0);
        this.e = byin.b;
        this.f = byin0.d;
        this.g = jlq.c(20.0);
        this.h = jlq.e(14);
        this.i = jlq.c(0.0);
        this.j = byin.b;
        this.k = byin0.d;
        this.l = jlq.c(16.0);
        this.m = jlq.e(12);
        this.n = jlq.c(0.1);
        this.o = byin.b;
        this.p = byin0.c;
        this.q = jlq.c(64.0);
        this.r = jlq.e(57);
        this.s = jlq.c(0.0);
        this.t = byin.b;
        this.u = byin0.c;
        this.v = jlq.c(52.0);
        this.w = jlq.e(45);
        this.x = jlq.c(0.0);
        this.y = byin.b;
        this.z = byin0.c;
        this.A = jlq.c(44.0);
        this.B = jlq.e(36);
        this.C = jlq.c(0.0);
        this.D = byin.b;
        this.E = byin0.c;
        this.F = jlq.c(40.0);
        this.G = jlq.e(0x20);
        this.H = jlq.c(0.0);
        this.I = byin.b;
        this.J = byin0.c;
        this.K = jlq.c(36.0);
        this.L = jlq.e(28);
        this.M = jlq.c(0.0);
        this.N = byin.b;
        this.O = byin0.c;
        this.P = jlq.c(32.0);
        this.Q = jlq.e(24);
        this.R = jlq.c(0.0);
        this.S = byin.b;
        this.T = byin0.d;
        this.U = jlq.c(20.0);
        this.V = jlq.e(14);
        this.W = jlq.c(0.0);
        this.X = byin.a;
        this.Y = byin0.d;
        this.Z = jlq.c(16.0);
        this.aa = jlq.e(12);
        this.ab = jlq.c(0.1);
        this.ac = byin.a;
        this.ad = byin0.d;
        this.ae = jlq.c(16.0);
        this.af = jlq.e(11);
        this.ag = jlq.c(0.1);
        this.ah = byin.a;
        this.ai = byin0.c;
        this.aj = jlq.c(28.0);
        this.ak = jlq.e(22);
        this.al = jlq.c(0.0);
        this.am = byin.b;
        this.an = byin0.d;
        this.ao = jlq.c(24.0);
        this.ap = jlq.e(16);
        this.aq = jlq.c(0.0);
        this.ar = byin.a;
        this.as = byin0.d;
        this.at = jlq.c(20.0);
        this.au = jlq.e(14);
        this.av = jlq.c(0.0);
        this.aw = byin.a;
    }
}

