import dagger.internal.DoubleCheck;
import dagger.internal.MapFactory.Builder;
import dagger.internal.Provider;
import dagger.internal.SetFactory.Builder;
import dagger.internal.SetFactory;
import dagger.internal.SingleCheck;

public final class cqcf extends cqch {
    final Provider A;
    final Provider B;
    public final Provider C;
    public final Provider D;
    public final Provider E;
    final Provider F;
    public final Provider G;
    final Provider H;
    final Provider I;
    final Provider J;
    final Provider K;
    final Provider L;
    final Provider M;
    final Provider N;
    public final Provider O;
    final Provider P;
    public final Provider Q;
    final Provider R;
    public final Provider S;
    final Provider T;
    final Provider U;
    final Provider V;
    final Provider W;
    final Provider X;
    final Provider Y;
    public final cqcf a;
    final Provider b;
    final Provider c;
    final Provider d;
    public final Provider e;
    final Provider f;
    final Provider g;
    final Provider h;
    final Provider i;
    final Provider j;
    final Provider k;
    final Provider l;
    final Provider m;
    final Provider n;
    final Provider o;
    final Provider p;
    final Provider q;
    final Provider r;
    final Provider s;
    final Provider t;
    final Provider u;
    final Provider v;
    final Provider w;
    final Provider x;
    final Provider y;
    final Provider z;

    public cqcf() {
        this.a = this;
        cqce cqce0 = new cqce(this);
        this.b = cqce0;
        this.c = DoubleCheck.b(new cqbz(cqce0));
        Provider provider0 = DoubleCheck.b(cqdq.a);
        this.d = provider0;
        Provider provider1 = DoubleCheck.b(bapw.a);
        this.e = provider1;
        Provider provider2 = DoubleCheck.b(new cqdo(provider1));
        this.f = provider2;
        SetFactory.Builder setFactory$Builder0 = new SetFactory.Builder(1, 0);
        setFactory$Builder0.c(provider2);
        SetFactory setFactory0 = setFactory$Builder0.a();
        this.g = setFactory0;
        Provider provider3 = DoubleCheck.b(new fren(setFactory0, SetFactory.a, SetFactory.a));
        this.h = provider3;
        Provider provider4 = SingleCheck.a(fgvv.a);
        this.i = provider4;
        cqdt cqdt0 = new cqdt(provider1);
        this.j = cqdt0;
        Provider provider5 = DoubleCheck.b(new cqdp(provider1, provider4, cqdt0));
        this.k = provider5;
        Provider provider6 = DoubleCheck.b(new cqds(provider0, provider3, provider5, cqdt0));
        this.l = provider6;
        Provider provider7 = DoubleCheck.b(cqcx.a);
        this.m = provider7;
        Provider provider8 = DoubleCheck.b(cqda.a);
        this.n = provider8;
        Provider provider9 = DoubleCheck.b(new cqde(provider1));
        this.o = provider9;
        Provider provider10 = DoubleCheck.b(new cqcz(provider4, provider7));
        this.p = provider10;
        cqcd cqcd0 = new cqcd(provider10);
        this.q = cqcd0;
        Provider provider11 = DoubleCheck.b(cqdc.a);
        this.r = provider11;
        Provider provider12 = DoubleCheck.b(new cjjo(provider1, provider3, provider11, cqcd0));
        this.s = provider12;
        this.t = cqcg.a;
        Provider provider13 = DoubleCheck.b(new fjgw(provider1));
        this.u = provider13;
        this.v = cqcg.a;
        Provider provider14 = DoubleCheck.b(new fjgv(cqcg.a));
        this.w = provider14;
        Provider provider15 = DoubleCheck.b(new fjgx(provider1, provider14));
        this.x = provider15;
        cqcd cqcd1 = new cqcd(provider11);
        this.y = cqcd1;
        this.z = cqcg.a;
        this.A = cqcg.a;
        this.B = cqcg.a;
        Provider provider16 = DoubleCheck.b(new fjgz(provider1, provider7, provider8, cqdf.a, provider3, provider9, cqcd0, provider12, cqcg.a, provider13, provider15, provider6, cqcd1, provider14, cqcg.a, cqcg.a, cqcg.a));
        this.C = provider16;
        this.D = DoubleCheck.b(new cqgg(provider1, provider4, provider6));
        Provider provider17 = DoubleCheck.b(new cqcs(provider1));
        this.E = provider17;
        Provider provider18 = DoubleCheck.b(cqfe.a);
        this.F = provider18;
        this.G = DoubleCheck.b(new cqez(provider18));
        cqdu cqdu0 = new cqdu(provider1);
        this.H = cqdu0;
        cqhk cqhk0 = new cqhk(provider17, cqdu0, provider3);
        this.I = cqhk0;
        cqau cqau0 = new cqau(provider16);
        this.J = cqau0;
        cqbr cqbr0 = new cqbr(cqau0, provider17);
        this.K = cqbr0;
        cqhi cqhi0 = new cqhi(provider16);
        this.L = cqhi0;
        SetFactory.Builder setFactory$Builder1 = new SetFactory.Builder(3, 0);
        setFactory$Builder1.c(cqhk0);
        setFactory$Builder1.c(cqbr0);
        setFactory$Builder1.c(cqhi0);
        SetFactory setFactory1 = setFactory$Builder1.a();
        this.M = setFactory1;
        cqhl cqhl0 = new cqhl(setFactory1);
        this.N = cqhl0;
        MapFactory.Builder mapFactory$Builder0 = new MapFactory.Builder(1);
        mapFactory$Builder0.c(cqgx.c, cqhl0);
        this.O = mapFactory$Builder0.b();
        Provider provider19 = DoubleCheck.b(cqfa.a);
        this.P = provider19;
        cqfc cqfc0 = new cqfc(provider1);
        this.Q = cqfc0;
        Provider provider20 = DoubleCheck.b(new cqey(cqfc0));
        this.R = provider20;
        this.S = DoubleCheck.b(new cqfd(provider19, provider20, provider18));
        this.T = DoubleCheck.b(new cqdv(provider1, provider5));
        Provider provider21 = DoubleCheck.b(cqco.a);
        this.U = provider21;
        this.V = DoubleCheck.b(new cqaq(provider21));
        this.W = DoubleCheck.b(cqar.a);
        Provider provider22 = DoubleCheck.b(cqav.a);
        this.X = provider22;
        this.Y = new cqat(provider22, provider3);
    }

    @Override  // cqch
    public final cqby a() {
        return (cqby)this.c.get();
    }

    @Override  // cqch
    public final fiyj b() {
        return (fiyj)this.G.get();
    }
}

