enum cqpc {
    FMD_DISABLED,
    MISSING_LOCK_SCREEN,
    MISSING_PHONE_NUMBER,
    MISSING_ACCOUNT,
    MISSING_CONSTELLATION_CONSENT,
    PHONE_NUMBER_NOT_VERIFIED,
    PHONE_NUMBER_VERIFICATION_ERROR,
    MISSING_SECURITY_QUESTION;

}

