public enum ctdh {
    UNKNOWN_DATA_LAYER_ACTION,
    ACCOUNT_UPDATE_ACCOUNTS,
    ACCOUNT_INFO_GET_ACCOUNT_AVATAR,
    ACCOUNT_INFO_GET_ACCOUNT_DISPLAY_NAME,
    ACCOUNT_INFO_GET_ACCOUNT_DUSI_RPC,
    ACCOUNT_INFO_GET_ACCOUNT_DUSI_LOCAL,
    ACCOUNT_DEVICE_GROUP_INVITE_DEVICES,
    SETTINGS_SET_MULTIDEVICE_STATUS,
    SETTINGS_SET_MULTIDEVICE_WITH_ACCOUNT,
    SETTINGS_DISABLE_MULTIDEVICE_ALL_ACCOUNTS,
    SETTINGS_SET_ACCOUNT_STATUS,
    SETTINGS_SET_FEATURE_STATUS,
    SETTINGS_REMOVE_ACCOUNT,
    DATASTORE_INIT,
    ACCOUNT_INFO_GET_OBFUSCATED_GAIA;

    static {
        ctdh.p = arr_ctdh;
        ibsn.a(arr_ctdh);
    }
}

