public enum cyqm {
    SUCCESS,
    NAK,
    TIMEOUT,
    FAIL_TO_SEND_NO_CONNECTION,
    EXCEPTION,
    REDUNDANT_CALL,
    FAILED_TO_RECONNECT,
    NO_PROFILE_PROXY,
    FAIL_TO_SEND_EXCEPTION,
    FAIL_TO_SEND_NO_SESSION_NONCE;

}

