import j..util.Objects;

public enum dlnd {
    HOME_SCREEN("HOME_SCREEN"),
    GLOBAL_ACTIONS("GLOBAL_ACTIONS"),
    DEEP_LINK("DEEP_LINK"),
    VALUABLE_DETAILS("VALUABLE_DETAILS"),
    ADD_VALUABLE("ADD_VALUABLE"),
    ENTER_VALUABLE("ENTER_VALUABLE"),
    ACTIVATE_VALUABLE("ACTIVATE_VALUABLE"),
    PASS_NOTIFICATION("PASS_NOTIFICATION"),
    USER_ACTIVATION_NOTIFICATION("USER_ACTIVATION_NOTIFICATION"),
    PROGRAM_SEARCH("PROGRAM_SEARCH"),
    VALUABLE_SIGNUP("VALUABLE_SIGNUP"),
    GET_PASSES("GET_PASSES"),
    GET_TRANSIT_CARDS("GET_TRANSIT_CARDS"),
    SAVE_PASSES("SAVE_PASSES"),
    PAISA("PAISA"),
    GP3_SIGN_IN("GP3_SIGN_IN"),
    GP3_SIGN_UP("GP3_SIGN_UP"),
    CARD_ADDED_NOTIFICATION("CARD_ADDED_NOTIFICATION"),
    ANDROID_SHORTCUT("ANDROID_SHORTCUT"),
    PRIVACY_CONTROLS("PRIVACY_CONTROLS"),
    DEVICE_HANDOFF_NOTIFICATION("DEVICE_HANDOFF_NOTIFICATION"),
    DEVICE_HANDOFF_EDUCATION("DEVICE_HANDOFF_EDUCATION"),
    LEARN_HOW_TO_USE_NFC_PASS_DETAILS_DRAWER("LEARN_HOW_TO_USE_NFC_PASS_DETAILS_DRAWER"),
    LEARN_HOW_TO_USE_NFC_PASS_BARCODE_VIEW("LEARN_HOW_TO_USE_NFC_PASS_BARCODE_VIEW"),
    OPEN_WEAR_VALUABLES_DETAILS("OPEN_WEAR_VALUABLES_DETAILS"),
    NFC_TAP("NFC_TAP"),
    EDIT_USER_CREATED_PASS("EDIT_USER_CREATED_PASS"),
    MAPS_PLACESHEET_VALUABLE_DEEP_LINK("MAPS_PLACESHEET_VALUABLE_DEEP_LINK"),
    PASS_UPGRADE("PASS_UPGRADE"),
    DEEP_LINK_CONTENT_URI("DEEP_LINK_CONTENT_URI");

    public final String E;

    private dlnd(String s1) {
        this.E = s1;
    }

    public static dlnd a(String s) {
        dlnd[] arr_dlnd = dlnd.values();
        for(int v = 0; v < arr_dlnd.length; ++v) {
            dlnd dlnd0 = arr_dlnd[v];
            if(Objects.equals(dlnd0.E, s)) {
                return dlnd0;
            }
        }
        return null;
    }
}

