public enum dmov {
    PAGE_CHECKING_THINGS,
    PAGE_MAIN,
    PAGE_PROGRESS,
    PAGE_FAILURE,
    PAGE_ITEMIZED_FAILURE,
    PAGE_SUCCESS,
    PAGE_NON_BACKUPABLE_CARDS,
    PAGE_REMOVE_PROGRESS;

}

