public enum dnrm {
    SUCCESS,
    SUCCESS_EMULATOR,
    FAILED_HCE_NOT_SUPPORTED,
    NULL_AIDS,
    EMPTY_AIDS,
    FAILED_COMPONENT_UPDATE,
    FAILED_CARD_EMULATION,
    FAILED_SYNCHRONIZATION,
    FAILED_SERVICE_REGISTRATION;

}

