import dagger.android.AndroidInjector;
import dagger.internal.DoubleCheck;
import dagger.internal.InstanceFactory;
import dagger.internal.Preconditions;
import dagger.internal.Provider;

final class dxnv implements AndroidInjector {
    final Provider A;
    final Provider B;
    final Provider C;
    final Provider D;
    final Provider E;
    final Provider F;
    final Provider G;
    final Provider H;
    final Provider I;
    final Provider J;
    final Provider K;
    final Provider L;
    final Provider M;
    final Provider N;
    final Provider O;
    final Provider P;
    final Provider Q;
    final Provider R;
    final Provider S;
    final Provider T;
    final Provider U;
    final dxni V;
    final Provider W;
    private final dolg X;
    private final doma Y;
    private final domv Z;
    final Provider a;
    private final eefy aa;
    private final dzpy ab;
    final Provider b;
    final Provider c;
    final Provider d;
    final Provider e;
    final Provider f;
    final Provider g;
    final Provider h;
    final Provider i;
    final Provider j;
    final Provider k;
    final Provider l;
    final Provider m;
    final Provider n;
    final Provider o;
    final Provider p;
    final Provider q;
    final Provider r;
    final Provider s;
    final Provider t;
    final Provider u;
    final Provider v;
    final Provider w;
    final Provider x;
    final Provider y;
    final Provider z;

    public dxnv(dmgr dmgr0, doma doma0, dzpy dzpy0, eefy eefy0, dolg dolg0, domw domw0, edlf edlf0, edor edor0, domv domv0) {
        this.X = dolg0;
        this.Y = doma0;
        this.Z = domv0;
        this.aa = eefy0;
        this.ab = dzpy0;
        dxno dxno0 = new dxno(dolg0);
        this.a = dxno0;
        dxnq dxnq0 = new dxnq(domv0);
        this.b = dxnq0;
        domd domd0 = new domd(doma0);
        this.c = domd0;
        dxnw dxnw0 = new dxnw(domd0);
        this.d = dxnw0;
        dxnn dxnn0 = new dxnn(dolg0);
        this.e = dxnn0;
        dmgj dmgj0 = new dmgj(dxnq0, dxnn0);
        this.f = dmgj0;
        dxns dxns0 = new dxns(domv0);
        this.g = dxns0;
        dsod dsod0 = new dsod(dxnq0);
        this.h = dsod0;
        dspi dspi0 = new dspi(dsod0);
        this.i = dspi0;
        Provider provider0 = DoubleCheck.b(new dsny(dxnq0, dxnw0, dxnn0, dmgj0, dxns0, dspi0));
        this.j = provider0;
        dmkm dmkm0 = new dmkm(dxnq0);
        this.k = dmkm0;
        edoe edoe0 = new edoe(dxnq0);
        this.l = edoe0;
        edoc edoc0 = new edoc(dxnq0);
        this.m = edoc0;
        edod edod0 = new edod(dxnq0);
        this.n = edod0;
        edny edny0 = new edny(edoe0, edoc0, edod0);
        this.o = edny0;
        dxnp dxnp0 = new dxnp(edlf0);
        this.p = dxnp0;
        dxnu dxnu0 = new dxnu(edor0);
        this.q = dxnu0;
        dxeg dxeg0 = new dxeg(domd0);
        this.r = dxeg0;
        edsf edsf0 = new edsf(dxnq0);
        this.s = edsf0;
        this.t = DoubleCheck.b(new dspq(dxno0, dxnq0, provider0, dmkm0, edny0, dxnp0, dxnu0, dxeg0, edsf0));
        dome dome0 = new dome(doma0);
        this.u = dome0;
        dsgs dsgs0 = new dsgs(dxnq0);
        this.v = dsgs0;
        eega eega0 = new eega(eefy0);
        this.w = eega0;
        dzpz dzpz0 = new dzpz(dzpy0);
        this.x = dzpz0;
        dxnd dxnd0 = new dxnd(dxnq0, dsgs0, eega0, dzpz0);
        this.y = dxnd0;
        dxnm dxnm0 = new dxnm(dolg0);
        this.z = dxnm0;
        dmgs dmgs0 = new dmgs(dmgr0);
        this.A = dmgs0;
        this.B = dxnx.a;
        dmhh dmhh0 = new dmhh(dxnq0, dxnn0, dxnm0, dmgs0, dxnx.a);
        this.C = dmhh0;
        this.D = new edto();
        edtq edtq0 = new edtq(dxno0);
        this.E = edtq0;
        edtm edtm0 = new edtm(dxnq0, edtq0);
        this.F = edtm0;
        dxtf dxtf0 = new dxtf(dmhh0, edtm0);
        this.G = dxtf0;
        edtp edtp0 = new edtp(dxnq0, edtq0);
        this.H = edtp0;
        eczt eczt0 = new eczt(domd0);
        this.I = eczt0;
        dmgp dmgp0 = new dmgp(dxnq0, dmkm0);
        this.J = dmgp0;
        dqia dqia0 = new dqia(dmhh0, dmgp0);
        this.K = dqia0;
        eegb eegb0 = new eegb(dxnq0);
        this.L = eegb0;
        eegc eegc0 = new eegc(eefy0);
        this.M = eegc0;
        eegd eegd0 = new eegd(eefy0);
        this.N = eegd0;
        dxnr dxnr0 = new dxnr();
        this.O = dxnr0;
        eefq eefq0 = new eefq(eegb0, dxnm0, dxnn0, eegc0, eegd0, dxyf.a, dxnr0);
        this.P = eefq0;
        edmx edmx0 = new edmx(dxnq0);
        this.Q = edmx0;
        dxsu dxsu0 = new dxsu(dome0, dxnd0, dmhh0, dxtf0, edtp0, dmgj0, eczt0, dqia0, eefq0, dxeg0, dxno0, dxnm0, dxnq0, edmx0);
        this.R = dxsu0;
        eefx eefx0 = new eefx(eegb0, eegd0);
        this.S = eefx0;
        dxnt dxnt0 = new dxnt(domv0);
        this.T = dxnt0;
        dxqc dxqc0 = new dxqc(dome0, dxnd0, dmhh0, dxtf0, edtp0, dmgj0, eczt0, dxno0, dxeg0, eefx0, dxnt0);
        this.U = dxqc0;
        dxni dxni0 = new dxni(dxsu0, dxqc0);
        this.V = dxni0;
        this.W = InstanceFactory.a(new dxnj(dxni0));
    }

    @Override  // dagger.android.AndroidInjector
    public final void inject(Object object0) {
        dxna dxna0 = (dxna)object0;
        dxna0.b = this.X.a();
        dxna0.c = new frzk(new etgl(domd.b(this.Y)), new frzh(), domf.a(this.Y), domc.a(this.Y));
        dxna0.d = (dspp)this.t.get();
        dxna0.at = (dxnj)((InstanceFactory)this.W).a;
        fhwk fhwk0 = this.Z.i();
        Preconditions.e(fhwk0);
        dxna0.ag = fhwk0;
        dxna0.ah = this.Z.g();
        dxna0.ai = new dxnc(this.Z.a(), new dsgr(this.Z.a()), this.aa.c(), this.ab.a());
        this.Z.a();
        dxna0.aj = new dmgi(this.X.d(), dmgy.a());
        dxna0.ak = this.Z.h();
        dxna0.al = new fuok();
        domj domj0 = this.Z.b();
        Preconditions.e(domj0);
        dxna0.am = domj0;
        dxna0.an = this.aa.c();
        dxna0.ao = this.ab.a();
    }
}

