import android.content.Context;
import dagger.android.AndroidInjector;
import dagger.internal.DoubleCheck;
import dagger.internal.InstanceFactory;
import dagger.internal.Preconditions;
import dagger.internal.Provider;

final class dxon implements AndroidInjector {
    final Provider A;
    final Provider B;
    final Provider C;
    final Provider D;
    final Provider E;
    final Provider F;
    final Provider G;
    final Provider H;
    final Provider I;
    final Provider J;
    final Provider K;
    final dxsb L;
    final Provider M;
    private final dolg N;
    private final domv O;
    private final doma P;
    private final dzpy Q;
    private final eefy R;
    final Provider a;
    final Provider b;
    final Provider c;
    final Provider d;
    final Provider e;
    final Provider f;
    final Provider g;
    final Provider h;
    final Provider i;
    final Provider j;
    final Provider k;
    final Provider l;
    final Provider m;
    final Provider n;
    final Provider o;
    final Provider p;
    final Provider q;
    final Provider r;
    final Provider s;
    final Provider t;
    final Provider u;
    final Provider v;
    final Provider w;
    final Provider x;
    final Provider y;
    final Provider z;

    public dxon(dmgr dmgr0, doma doma0, dzpy dzpy0, eefy eefy0, dolg dolg0, edlf edlf0, edor edor0, domv domv0) {
        this.N = dolg0;
        this.O = domv0;
        this.P = doma0;
        this.Q = dzpy0;
        this.R = eefy0;
        dxoh dxoh0 = new dxoh(dolg0);
        this.a = dxoh0;
        dxoj dxoj0 = new dxoj(domv0);
        this.b = dxoj0;
        domd domd0 = new domd(doma0);
        this.c = domd0;
        dxoo dxoo0 = new dxoo(domd0);
        this.d = dxoo0;
        dxog dxog0 = new dxog(dolg0);
        this.e = dxog0;
        dmgj dmgj0 = new dmgj(dxoj0, dxog0);
        this.f = dmgj0;
        dxok dxok0 = new dxok(domv0);
        this.g = dxok0;
        dsod dsod0 = new dsod(dxoj0);
        this.h = dsod0;
        dspi dspi0 = new dspi(dsod0);
        this.i = dspi0;
        Provider provider0 = DoubleCheck.b(new dsny(dxoj0, dxoo0, dxog0, dmgj0, dxok0, dspi0));
        this.j = provider0;
        dmkm dmkm0 = new dmkm(dxoj0);
        this.k = dmkm0;
        edoe edoe0 = new edoe(dxoj0);
        this.l = edoe0;
        edoc edoc0 = new edoc(dxoj0);
        this.m = edoc0;
        edod edod0 = new edod(dxoj0);
        this.n = edod0;
        edny edny0 = new edny(edoe0, edoc0, edod0);
        this.o = edny0;
        dxoi dxoi0 = new dxoi(edlf0);
        this.p = dxoi0;
        dxom dxom0 = new dxom(edor0);
        this.q = dxom0;
        dxeg dxeg0 = new dxeg(domd0);
        this.r = dxeg0;
        edsf edsf0 = new edsf(dxoj0);
        this.s = edsf0;
        this.t = DoubleCheck.b(new dspq(dxoh0, dxoj0, provider0, dmkm0, edny0, dxoi0, dxom0, dxeg0, edsf0));
        dome dome0 = new dome(doma0);
        this.u = dome0;
        dsgs dsgs0 = new dsgs(dxoj0);
        this.v = dsgs0;
        eega eega0 = new eega(eefy0);
        this.w = eega0;
        dzpz dzpz0 = new dzpz(dzpy0);
        this.x = dzpz0;
        dxra dxra0 = new dxra(dxoj0, dsgs0, eega0, dzpz0);
        this.y = dxra0;
        dxof dxof0 = new dxof(dolg0);
        this.z = dxof0;
        dxsx dxsx0 = new dxsx(dome0, dxra0, dxof0);
        this.A = dxsx0;
        dxol dxol0 = new dxol(domv0);
        this.B = dxol0;
        dmgs dmgs0 = new dmgs(dmgr0);
        this.C = dmgs0;
        this.D = dxop.a;
        dmhh dmhh0 = new dmhh(dxoj0, dxog0, dxof0, dmgs0, dxop.a);
        this.E = dmhh0;
        this.F = new edto();
        edtq edtq0 = new edtq(dxoh0);
        this.G = edtq0;
        edtm edtm0 = new edtm(dxoj0, edtq0);
        this.H = edtm0;
        dxtf dxtf0 = new dxtf(dmhh0, edtm0);
        this.I = dxtf0;
        edtp edtp0 = new edtp(dxoj0, edtq0);
        this.J = edtp0;
        dxqj dxqj0 = new dxqj(dome0, dxra0, dxoh0, dxof0, dmgj0, dxol0, dxtf0, dxeg0, edtp0);
        this.K = dxqj0;
        dxsb dxsb0 = new dxsb(dxsx0, dxqj0);
        this.L = dxsb0;
        this.M = InstanceFactory.a(new dxsc(dxsb0));
    }

    @Override  // dagger.android.AndroidInjector
    public final void inject(Object object0) {
        dxqw dxqw0 = (dxqw)object0;
        dxqw0.b = this.N.a();
        dxqw0.c = (dspp)this.t.get();
        dxqw0.au = (dxsc)((InstanceFactory)this.M).a;
        fhwk fhwk0 = this.O.i();
        Preconditions.e(fhwk0);
        dxqw0.d = fhwk0;
        dxqw0.ag = this.O.g();
        dxqw0.ah = new eaca(domb.a(this.P), this.Q.a());
        Context context0 = this.O.a();
        dsgr dsgr0 = new dsgr(this.O.a());
        boolean z = this.Q.a();
        dxqw0.ai = new dxqz(context0, dsgr0, this.R.c(), z);
        this.O.a();
        dxqw0.aj = new dmgi(this.N.d(), dmgy.a());
        dxqw0.ak = this.O.h();
        dxqw0.al = new fuok();
        domj domj0 = this.O.b();
        Preconditions.e(domj0);
        dxqw0.am = domj0;
        dxqw0.an = this.R.c();
        dxqw0.ao = this.Q.a();
    }
}

