public enum esth {
    B1B8_ISS_AUTH_MANDATORY,
    B2B8_VALID_AT_OFFLINE_TERMINALS,
    B2B7_VALID_AT_TRANSIT_TERMS,
    B2B4_SKIP_VELOCITY_CHK_FOR_OFFLINE_9X_TERM,
    B2B3_GLOBAL_WALLET_ENABLED,
    B4B8_TXN_RECOVERY_ENABLED,
    B4B7_SRV_FEATURE_ENABLED,
    B4B6_VELOCITY_CHECK_ENABLED,
    B4B4_CIAC_DECL_TRANSIT_ENABLED,
    B4B3_ACT_ENABLED,
    B4B2_TC_LOGGING_ENABLED,
    B4B1_AAC_LOGGING_ENABLED,
    B5B85_SRV_COMPATIBILITY_VERSION,
    B7B8_MONEY_ADD_TXN_SUPPORTED,
    B7B7_VOID_TXN_SUPPORTED;

}

