public enum estj {
    B1B8_PROP_AUTH_DATA_INCLUDED,
    B1B7_DEBIT_ON_CARD_ISS_SUCCESS_AUTH,
    B2B8_ISS_APPROVE_ONL_TXN,
    B2B4_GO_ONLINE_ON_NEXT_TXN,
    B2B32_DO_NOT_RESET_OFFLINE_COUNTERS,
    B2B32_RESET_OFFLINE_COUNTERS_FOR_CL,
    B2B32_RESET_OFFLINE_COUNTERS_FOR_BOTH,
    B3B87_DO_NOT_UPDATE,
    B3B87_ADD_TO_OFFL_BALANCE,
    B3B87_DEDUCT_FROM_OFFL_BALANCE,
    B3B87_VALUE_RFU;

}

