public enum estn {
    B1B8_PERMANENT_SERVICE,
    B1B8_TEMPORARY_SERVICE,
    B1B7_SERVICE_BAL_LIM_UPDATE,
    B1B6_SERVICE_KEY_PLANT,
    B1B5_ACTIVE,
    B1B4_BLOCKED,
    B1B3_RFU,
    B1B2_WALLET_INACTIVE,
    B1B2_WALLET_ACTIVE,
    B1B1_USE_CARD_GLOBAL_BAL,
    B2B8_CURR_CODE_IS_KM;

}

