public enum estp {
    PURCHASE,
    TRANSIT,
    ONLINE_ADJUSTMENT,
    SERVICE_UPDATE,
    CASH,
    PURCHASE_WITH_CASH_BACK,
    PURCHASE_OR_CASH_OR_CASH_BACK,
    MONEY_ADD,
    VOID_TXN,
    NON_LEGACY_BALANCE_ENQUIRY,
    NON_LEGACY_SERVICE_CREATION;

}

