public enum estq {
    RETAIL,
    RETAIL_ONLINE_ONLY,
    RETAIL_OFFLINE_WITH_ONLINE,
    RETAIL_OFFLINE_ONLY,
    TRANSIT,
    TRANSIT_ONLINE_ONLY,
    TRANSIT_OFFLINE_WITH_ONLINE,
    TRANSIT_OFFLINE_ONLY,
    OFFLINE_ONLY,
    ONLINE_ONLY,
    OFF_LINE_WITH_ONLINE;

}

