import java.util.HashMap;

final class esuc extends HashMap {
    public esuc() {
        Byte byte0 = (byte)0;
        idoy idoy0 = new idoy(byte0, byte0);
        this.put(estk.a, idoy0);
        Byte byte1 = (byte)7;
        idoy idoy1 = new idoy(byte0, byte1);
        this.put(estk.b, idoy1);
        Byte byte2 = (byte)6;
        idoy idoy2 = new idoy(byte0, byte2);
        this.put(estk.c, idoy2);
        idoy idoy3 = new idoy(byte0, byte2);
        this.put(estk.d, idoy3);
        idoy idoy4 = new idoy(byte0, byte1);
        this.put(estk.g, idoy4);
        idoy idoy5 = new idoy(byte0, byte2);
        this.put(estk.f, idoy5);
        idoy idoy6 = new idoy(byte0, byte0);
        this.put(estk.h, idoy6);
        Byte byte3 = (byte)4;
        idoy idoy7 = new idoy(byte0, byte3);
        this.put(estk.i, idoy7);
        Byte byte4 = (byte)5;
        idoy idoy8 = new idoy(byte0, byte4);
        this.put(estk.j, idoy8);
        idoy idoy9 = new idoy(byte0, byte4);
        this.put(estk.k, idoy9);
        Byte byte5 = (byte)2;
        idoy idoy10 = new idoy(byte0, byte5);
        this.put(estk.l, idoy10);
        Byte byte6 = (byte)1;
        idoy idoy11 = new idoy(byte0, byte6);
        this.put(estk.m, idoy11);
        idoy idoy12 = new idoy(byte0, byte0);
        this.put(estk.n, idoy12);
        Byte byte7 = (byte)3;
        idoy idoy13 = new idoy(byte6, byte7);
        this.put(estk.o, idoy13);
        idoy idoy14 = new idoy(byte6, byte0);
        this.put(estk.p, idoy14);
        idoy idoy15 = new idoy(byte5, byte1);
        this.put(estk.q, idoy15);
        idoy idoy16 = new idoy(byte5, byte2);
        this.put(estk.r, idoy16);
        idoy idoy17 = new idoy(byte5, byte4);
        this.put(estk.s, idoy17);
        idoy idoy18 = new idoy(byte5, byte3);
        this.put(estk.t, idoy18);
        idoy idoy19 = new idoy(byte5, byte7);
        this.put(estk.u, idoy19);
        idoy idoy20 = new idoy(byte5, byte6);
        this.put(estk.v, idoy20);
        idoy idoy21 = new idoy(byte5, byte0);
        this.put(estk.w, idoy21);
        idoy idoy22 = new idoy(byte7, byte5);
        this.put(estk.x, idoy22);
        idoy idoy23 = new idoy(byte7, byte0);
        this.put(estk.y, idoy23);
        idoy idoy24 = new idoy(byte3, byte1);
        this.put(estk.z, idoy24);
        idoy idoy25 = new idoy(byte3, byte4);
        this.put(estk.A, idoy25);
        idoy idoy26 = new idoy(byte3, byte7);
        this.put(estk.B, idoy26);
        idoy idoy27 = new idoy(byte3, byte5);
        this.put(estk.C, idoy27);
        idoy idoy28 = new idoy(byte3, byte6);
        this.put(estk.D, idoy28);
        idoy idoy29 = new idoy(byte3, byte0);
        this.put(estk.E, idoy29);
        idoy idoy30 = new idoy(byte4, byte1);
        this.put(estk.F, idoy30);
        idoy idoy31 = new idoy(byte4, byte2);
        this.put(estk.G, idoy31);
        idoy idoy32 = new idoy(byte4, byte4);
        this.put(estk.H, idoy32);
        idoy idoy33 = new idoy(byte4, byte3);
        this.put(estk.I, idoy33);
        idoy idoy34 = new idoy(byte4, byte7);
        this.put(estk.J, idoy34);
        idoy idoy35 = new idoy(byte4, byte5);
        this.put(estk.K, idoy35);
        idoy idoy36 = new idoy(byte4, byte6);
        this.put(estk.L, idoy36);
        idoy idoy37 = new idoy(byte4, byte0);
        this.put(estk.M, idoy37);
        idoy idoy38 = new idoy(byte2, byte1);
        this.put(estk.N, idoy38);
        idoy idoy39 = new idoy(byte2, byte2);
        this.put(estk.O, idoy39);
        idoy idoy40 = new idoy(byte2, byte4);
        this.put(estk.P, idoy40);
        idoy idoy41 = new idoy(byte2, byte3);
        this.put(estk.Q, idoy41);
        idoy idoy42 = new idoy(byte2, byte7);
        this.put(estk.R, idoy42);
        idoy idoy43 = new idoy(byte1, byte1);
        this.put(estk.S, idoy43);
        idoy idoy44 = new idoy(byte1, byte2);
        this.put(estk.T, idoy44);
        idoy idoy45 = new idoy(byte1, byte4);
        this.put(estk.U, idoy45);
        idoy idoy46 = new idoy(byte1, byte3);
        this.put(estk.V, idoy46);
        idoy idoy47 = new idoy(byte1, byte7);
        this.put(estk.W, idoy47);
        idoy idoy48 = new idoy(byte1, byte6);
        this.put(estk.X, idoy48);
        idoy idoy49 = new idoy(byte1, byte0);
        this.put(estk.Y, idoy49);
    }
}

