public enum eswu {
    RECEIVED_FRAME,
    TRANSACTION_START,
    POLLING_LOOP_COLLECTION_FINISHED,
    POLLING_LOOP_COLLECTION_CONTINUE,
    POLLING_LOOP_SKIP_AUTH,
    POLLING_LOOP_REQUIRE_AUTH,
    OBSERVE_MODE_ENABLE,
    UI_DISMISS,
    AUTH_SUCCESS,
    POLLING_LOOP_REQUIRE_PAYMENT_INTENT,
    PAYMENT_INTENT_SUCCESS;

    static {
        eswu.l = arr_eswu;
        ibsn.a(arr_eswu);
    }
}

