public enum eynx {
    ADVANCED_SECURITY_SETTINGS,
    COMPANION_SETTINGS,
    ANDROID_SETTINGS,
    DEVICE_EXPIRATION_NOTIFICATION,
    COMPANION_PROMO_CARD,
    METHOD_DOWNGRADE_NOTIFICATION,
    METHOD_UNAVAILABLE_NOTIFICATION,
    BUGREPORT_NOTIFICATION,
    METHOD_AIRPLANE_MODE_NOTIFICATION;

    static {
        eynx.j = arr_eynx;
        ibsn.a(arr_eynx);
    }
}

