public enum fclm {
    FETCH_BACKUPS,
    FETCH_CACHED_BACKUPS,
    SELECT_BACKUP,
    BACKUP_SELECTED,
    KEY_RECOVERY,
    START_RESTORE,
    WAITING_FOR_CHARGING,
    RESTORE_STARTED,
    SKIPPED,
    ERROR,
    FINISH;

}

