public enum fuvg {
    SCAN_OVERLAP_RATIO_0_2,
    SCAN_OVERLAP_COUNT_0_2,
    SCAN_OVERLAP_MIN_RADIUS_0_2,
    SCAN_OVERLAP_RATIO_1_2,
    WIFI_LOC_DISTANCE_0_1,
    WIFI_LOC_DISTANCE_0_2,
    WIFI_LOC_DISTANCE_1_2,
    CELL_LOC_DISTANCE_0_2;

}

