public final class fvem {
    private static final fvej a;
    private static final ggeo b;

    static {
        fvei fvei0 = new fvei();
        fvei0.a(fveh.a, -2.8f);
        fvei0.a(fveh.c, -3.7f);
        fvei0.a(fveh.i, -4.8f);
        fvei0.a(fveh.j, -5.4f);
        fvei0.a(fveh.d, -2.9f);
        fvei0.a(fveh.t, -5.2f);
        fvei0.a(fveh.v, -5.2f);
        fvei0.a(fveh.p, -3.5f);
        fvei0.a(fveh.r, -6.0f);
        fvem.a = new fvej(fvei0);
        ggek ggek0 = new ggek();
        fvei fvei1 = new fvei();
        fvei1.a(fveh.a, -3.9f);
        ggek0.i("google/bullhead", new fvej(fvei1));
        fvei fvei2 = new fvei();
        fvei2.a(fveh.a, -4.4f);
        ggek0.i("google/nexus 5x", new fvej(fvei2));
        fvei fvei3 = new fvei();
        fvei3.a(fveh.a, -3.9f);
        ggek0.i("google/nexus 6p", new fvej(fvei3));
        fvei fvei4 = new fvei();
        fvei4.a(fveh.a, -2.7f);
        fvei4.a(fveh.i, -4.8f);
        fvei4.a(fveh.d, -3.0f);
        fvei4.a(fveh.t, -5.3f);
        fvei4.a(fveh.p, -2.6f);
        ggek0.i("google/pixel 2 xl", new fvej(fvei4));
        fvei fvei5 = new fvei();
        fvei5.a(fveh.a, -2.8f);
        fvei5.a(fveh.i, -4.5f);
        fvei5.a(fveh.d, -3.1f);
        fvei5.a(fveh.t, -4.1f);
        ggek0.i("google/pixel 2", new fvej(fvei5));
        fvei fvei6 = new fvei();
        fvei6.a(fveh.a, -5.1f);
        fvei6.a(fveh.i, -3.9f);
        fvei6.a(fveh.d, -3.5f);
        fvei6.a(fveh.t, -3.1f);
        fvei6.a(fveh.p, -3.65f);
        ggek0.i("google/pixel 3 xl", new fvej(fvei6));
        fvei fvei7 = new fvei();
        fvei7.a(fveh.a, -3.2f);
        fvei7.a(fveh.i, -3.8f);
        fvei7.a(fveh.d, -2.3f);
        fvei7.a(fveh.t, -2.9f);
        fvei7.a(fveh.p, -3.4f);
        ggek0.i("google/pixel 3", new fvej(fvei7));
        fvei fvei8 = new fvei();
        fvei8.a(fveh.a, -3.35f);
        fvei8.a(fveh.c, -4.15f);
        fvei8.a(fveh.i, -3.7f);
        fvei8.a(fveh.j, -5.5f);
        fvei8.a(fveh.d, -2.0f);
        ggek0.i("google/pixel 4 xl", new fvej(fvei8));
        fvei fvei9 = new fvei();
        fvei9.a(fveh.a, -3.65f);
        fvei9.a(fveh.c, -4.8f);
        fvei9.a(fveh.i, -4.2f);
        fvei9.a(fveh.j, -6.4f);
        fvei9.a(fveh.d, -2.3f);
        ggek0.i("google/pixel 4", new fvej(fvei9));
        fvei fvei10 = new fvei();
        fvei10.a(fveh.a, -5.7f);
        ggek0.i("google/pixel xl", new fvej(fvei10));
        fvei fvei11 = new fvei();
        fvei11.a(fveh.a, -7.5f);
        ggek0.i("google/pixel", new fvej(fvei11));
        fvei fvei12 = new fvei();
        fvei12.a(fveh.a, -2.5f);
        fvei12.a(fveh.i, -5.1f);
        fvei12.a(fveh.d, -3.0f);
        fvei12.a(fveh.t, -5.6f);
        fvei12.a(fveh.p, -3.5f);
        ggek0.i("google/taimen", new fvej(fvei12));
        fvei fvei13 = new fvei();
        fvei13.a(fveh.a, -4.4f);
        fvei13.a(fveh.i, -4.25f);
        fvei13.a(fveh.d, -2.1f);
        fvei13.a(fveh.t, -3.55f);
        ggek0.i("samsung/sm-g950f", new fvej(fvei13));
        fvei fvei14 = new fvei();
        fvei14.a(fveh.a, -2.9f);
        fvei14.a(fveh.d, -2.9f);
        fvei14.a(fveh.t, -5.0f);
        ggek0.i("samsung/sm-g950u1", new fvej(fvei14));
        fvei fvei15 = new fvei();
        fvei15.a(fveh.a, -3.5f);
        fvei15.a(fveh.i, -3.5f);
        fvei15.a(fveh.d, -2.5f);
        fvei15.a(fveh.t, -2.6f);
        ggek0.i("samsung/sm-g9600", new fvej(fvei15));
        fvei fvei16 = new fvei();
        fvei16.a(fveh.a, 3.3f);
        fvei16.a(fveh.i, -3.2f);
        fvei16.a(fveh.d, -1.9f);
        fvei16.a(fveh.t, -2.3f);
        fvei16.a(fveh.p, -3.45f);
        ggek0.i("samsung/sm-g973f", new fvej(fvei16));
        fvei fvei17 = new fvei();
        fvei17.a(fveh.a, 1.7f);
        fvei17.a(fveh.i, -3.95f);
        fvei17.a(fveh.d, -3.5f);
        ggek0.i("samsung/sm-g973u1", new fvej(fvei17));
        fvei fvei18 = new fvei();
        fvei18.a(fveh.a, -7.05f);
        fvei18.a(fveh.i, -4.35f);
        fvei18.a(fveh.d, -2.8f);
        fvei18.a(fveh.t, -4.6f);
        ggek0.i("sony/g8142", new fvej(fvei18));
        fvem.b = ggek0.b();
    }

    public static fvej a(String s) {
        fvej fvej0 = (fvej)fvem.b.get(s);
        return fvej0 == null ? fvem.a : fvej0;
    }
}

