interface gked {
    public static final gkee A;
    public static final gkee B;
    public static final gkee C;
    public static final gkee D;
    public static final gkee E;
    public static final gkee F;
    public static final gkee G;
    public static final gkee H;
    public static final gkee I;
    public static final gkee J;
    public static final gkee K;
    public static final gkee L;
    public static final gkee M;
    public static final gkee N;
    public static final gkee O;
    public static final gkee P;
    public static final gkee Q;
    public static final gkee a;
    public static final gkee b;
    public static final gkee c;
    public static final gkee d;
    public static final gkee e;
    public static final gkee f;
    public static final gkee g;
    public static final gkee h;
    public static final gkee i;
    public static final gkee j;
    public static final gkee k;
    public static final gkee l;
    public static final gkee m;
    public static final gkee n;
    public static final gkee o;
    public static final gkee p;
    public static final gkee q;
    public static final gkee r;
    public static final gkee s;
    public static final gkee t;
    public static final gkee u;
    public static final gkee v;
    public static final gkee w;
    public static final gkee x;
    public static final gkee y;
    public static final gkee z;

    static {
        gked.a = new gkee(0);
        gked.b = new gkee(6);
        gked.c = new gkee(1500);
        gked.d = new gkee(1501);
        gked.e = new gkee(1502);
        gked.f = new gkee(0x5DF);
        gked.g = new gkee(0x5E0);
        gked.h = new gkee(1505);
        gked.i = new gkee(1506);
        gked.j = new gkee(1507);
        gked.k = new gkee(1508);
        gked.l = new gkee(1509);
        gked.m = new gkee(1510);
        gked.n = new gkee(0x5E7);
        gked.o = new gkee(0x5E8);
        gked.p = new gkee(0x5E9);
        gked.q = new gkee(0x5EA);
        gked.r = new gkee(0x5EB);
        gked.s = new gkee(0x5EC);
        gked.t = new gkee(0x5ED);
        gked.u = new gkee(0x5EE);
        gked.v = new gkee(0x5EF);
        gked.w = new gkee(0x5F0);
        gked.x = new gkee(0x5F1);
        gked.y = new gkee(0x5F2);
        gked.z = new gkee(0x5F3);
        gked.A = new gkee(0x5F4);
        gked.B = new gkee(0x5F5);
        gked.C = new gkee(0x5F6);
        gked.D = new gkee(0x5F7);
        gked.E = new gkee(0x5F8);
        gked.F = new gkee(0x5F9);
        gked.G = new gkee(0x5FA);
        gked.H = new gkee(0x5FB);
        gked.I = new gkee(0x5FC);
        gked.J = new gkee(1700);
        gked.K = new gkee(1701);
        gked.L = new gkee(1702);
        gked.M = new gkee(1703);
        gked.N = new gkee(1704);
        gked.O = new gkee(1705);
        gked.P = new gkee(1706);
        gked.Q = new gkee(1707);
    }
}

