import java.net.InetAddress;
import java.net.URI;
import java.net.URL;
import java.util.BitSet;
import java.util.Calendar;
import java.util.Currency;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicIntegerArray;

public final class gqeq {
    public static final gqae A;
    public static final gqad B;
    public static final gqae C;
    public static final gqad D;
    public static final gqae E;
    public static final gqad F;
    public static final gqae G;
    public static final gqad H;
    public static final gqae I;
    public static final gqad J;
    public static final gqae K;
    public static final gqad L;
    public static final gqae M;
    public static final gqad N;
    public static final gqae O;
    public static final gqad P;
    public static final gqae Q;
    public static final gqad R;
    public static final gqae S;
    public static final gqad T;
    public static final gqae U;
    public static final gqae V;
    public static final gqad a;
    public static final gqae b;
    public static final gqad c;
    public static final gqae d;
    public static final gqad e;
    public static final gqad f;
    public static final gqae g;
    public static final gqad h;
    public static final gqae i;
    public static final gqad j;
    public static final gqae k;
    public static final gqad l;
    public static final gqae m;
    public static final gqad n;
    public static final gqae o;
    public static final gqad p;
    public static final gqae q;
    public static final gqad r;
    public static final gqae s;
    public static final gqad t;
    public static final gqad u;
    public static final gqae v;
    public static final gqad w;
    public static final gqad x;
    public static final gqad y;
    public static final gqad z;

    static {
        gqad gqad0 = new gqdu().d();
        gqeq.a = gqad0;
        gqeq.b = new gqed(Class.class, gqad0);
        gqad gqad1 = new gqee().d();
        gqeq.c = gqad1;
        gqeq.d = new gqed(BitSet.class, gqad1);
        gqej gqej0 = new gqej();
        gqeq.e = gqej0;
        gqeq.f = new gqek();
        gqeq.g = new gqef(Boolean.TYPE, Boolean.class, gqej0);
        gqel gqel0 = new gqel();
        gqeq.h = gqel0;
        gqeq.i = new gqef(Byte.TYPE, Byte.class, gqel0);
        gqem gqem0 = new gqem();
        gqeq.j = gqem0;
        gqeq.k = new gqef(Short.TYPE, Short.class, gqem0);
        gqen gqen0 = new gqen();
        gqeq.l = gqen0;
        gqeq.m = new gqef(Integer.TYPE, Integer.class, gqen0);
        gqad gqad2 = new gqeo().d();
        gqeq.n = gqad2;
        gqeq.o = new gqed(AtomicInteger.class, gqad2);
        gqad gqad3 = new gqep().d();
        gqeq.p = gqad3;
        gqeq.q = new gqed(AtomicBoolean.class, gqad3);
        gqad gqad4 = new gqdm().d();
        gqeq.r = gqad4;
        gqeq.s = new gqed(AtomicIntegerArray.class, gqad4);
        gqeq.t = new gqdn();
        gqdo gqdo0 = new gqdo();
        gqeq.u = gqdo0;
        gqeq.v = new gqef(Character.TYPE, Character.class, gqdo0);
        gqdp gqdp0 = new gqdp();
        gqeq.w = gqdp0;
        gqeq.x = new gqdq();
        gqeq.y = new gqdr();
        gqeq.z = new gqds();
        gqeq.A = new gqed(String.class, gqdp0);
        gqdt gqdt0 = new gqdt();
        gqeq.B = gqdt0;
        gqeq.C = new gqed(StringBuilder.class, gqdt0);
        gqdv gqdv0 = new gqdv();
        gqeq.D = gqdv0;
        gqeq.E = new gqed(StringBuffer.class, gqdv0);
        gqdw gqdw0 = new gqdw();
        gqeq.F = gqdw0;
        gqeq.G = new gqed(URL.class, gqdw0);
        gqdx gqdx0 = new gqdx();
        gqeq.H = gqdx0;
        gqeq.I = new gqed(URI.class, gqdx0);
        gqdy gqdy0 = new gqdy();
        gqeq.J = gqdy0;
        gqeq.K = new gqei(InetAddress.class, gqdy0);
        gqdz gqdz0 = new gqdz();
        gqeq.L = gqdz0;
        gqeq.M = new gqed(UUID.class, gqdz0);
        gqad gqad5 = new gqea().d();
        gqeq.N = gqad5;
        gqeq.O = new gqed(Currency.class, gqad5);
        gqeb gqeb0 = new gqeb();
        gqeq.P = gqeb0;
        gqeq.Q = new gqeg(Calendar.class, GregorianCalendar.class, gqeb0);
        gqec gqec0 = new gqec();
        gqeq.R = gqec0;
        gqeq.S = new gqed(Locale.class, gqec0);
        gqeq.T = gqcv.a;
        gqeq.U = new gqei(gpzq.class, gqcv.a);
        gqeq.V = gqcs.a;
    }
}

