// PARTIAL FAILURE: ENUM SUGARING
// The enumeration is rendered as-is instead of being sugared into a Java 5 enum.
public final class gqgf extends Enum {
    public static final enum gqgf A;
    public static final enum gqgf B;
    public static final enum gqgf C;
    public static final enum gqgf D;
    public static final enum gqgf E;
    public static final enum gqgf F;
    public static final enum gqgf G;
    public static final enum gqgf H;
    public static final enum gqgf I;
    @Deprecated
    public static final enum gqgf J;
    public static final enum gqgf K;
    public static final enum gqgf L;
    public static final enum gqgf M;
    public static final enum gqgf N;
    public static final enum gqgf O;
    public static final enum gqgf P;
    public static final enum gqgf Q;
    public static final enum gqgf R;
    public static final enum gqgf S;
    public static final enum gqgf T;
    public static final enum gqgf U;
    public static final enum gqgf V;
    public static final enum gqgf W;
    public static final enum gqgf X;
    public static final enum gqgf Y;
    public static final enum gqgf Z;
    public static final enum gqgf a;
    public static final enum gqgf aA;
    public static final enum gqgf aB;
    public static final enum gqgf aC;
    public static final enum gqgf aD;
    public static final enum gqgf aE;
    public static final enum gqgf aF;
    public static final enum gqgf aG;
    public static final enum gqgf aH;
    @Deprecated
    public static final enum gqgf aI;
    public static final enum gqgf aJ;
    public static final enum gqgf aK;
    public static final enum gqgf aL;
    public static final enum gqgf aM;
    public static final enum gqgf aN;
    public static final enum gqgf aO;
    public static final enum gqgf aP;
    public static final enum gqgf aQ;
    public static final enum gqgf aR;
    public static final enum gqgf aS;
    public static final enum gqgf aT;
    public static final enum gqgf aU;
    public static final enum gqgf aV;
    public static final enum gqgf aW;
    public static final enum gqgf aX;
    public static final enum gqgf aY;
    public static final enum gqgf aZ;
    public static final enum gqgf aa;
    public static final enum gqgf ab;
    public static final enum gqgf ac;
    @Deprecated
    public static final enum gqgf ad;
    public static final enum gqgf ae;
    public static final enum gqgf af;
    public static final enum gqgf ag;
    public static final enum gqgf ah;
    public static final enum gqgf ai;
    public static final enum gqgf aj;
    @Deprecated
    public static final enum gqgf ak;
    public static final enum gqgf al;
    public static final enum gqgf am;
    public static final enum gqgf an;
    public static final enum gqgf ao;
    public static final enum gqgf ap;
    public static final enum gqgf aq;
    public static final enum gqgf ar;
    public static final enum gqgf as;
    public static final enum gqgf at;
    public static final enum gqgf au;
    public static final enum gqgf av;
    public static final enum gqgf aw;
    public static final enum gqgf ax;
    public static final enum gqgf ay;
    public static final enum gqgf az;
    public static final enum gqgf b;
    public static final enum gqgf bA;
    public static final enum gqgf bB;
    public static final enum gqgf bC;
    public static final enum gqgf bD;
    public static final enum gqgf bE;
    public static final enum gqgf bF;
    public static final enum gqgf bG;
    public static final enum gqgf bH;
    public static final enum gqgf bI;
    public static final enum gqgf bJ;
    public static final enum gqgf bK;
    public static final enum gqgf bL;
    public static final enum gqgf bM;
    public static final enum gqgf bN;
    public static final enum gqgf bO;
    public static final enum gqgf bP;
    public static final enum gqgf bQ;
    public static final enum gqgf bR;
    public static final enum gqgf bS;
    public static final enum gqgf bT;
    public static final enum gqgf bU;
    public static final enum gqgf bV;
    public static final enum gqgf bW;
    public static final enum gqgf bX;
    public static final enum gqgf bY;
    public static final enum gqgf bZ;
    public static final enum gqgf ba;
    public static final enum gqgf bb;
    public static final enum gqgf bc;
    public static final enum gqgf bd;
    public static final enum gqgf be;
    public static final enum gqgf bf;
    public static final enum gqgf bg;
    public static final enum gqgf bh;
    public static final enum gqgf bi;
    public static final enum gqgf bj;
    public static final enum gqgf bk;
    public static final enum gqgf bl;
    public static final enum gqgf bm;
    public static final enum gqgf bn;
    public static final enum gqgf bo;
    public static final enum gqgf bp;
    public static final enum gqgf bq;
    public static final enum gqgf br;
    public static final enum gqgf bs;
    public static final enum gqgf bt;
    public static final enum gqgf bu;
    public static final enum gqgf bv;
    public static final enum gqgf bw;
    public static final enum gqgf bx;
    public static final enum gqgf by;
    public static final enum gqgf bz;
    public static final enum gqgf c;
    @Deprecated
    public static final enum gqgf cA;
    public static final enum gqgf cB;
    public static final enum gqgf cC;
    public static final enum gqgf cD;
    public static final enum gqgf cE;
    public static final enum gqgf cF;
    public static final enum gqgf cG;
    public static final enum gqgf cH;
    public static final enum gqgf cI;
    public static final enum gqgf cJ;
    public static final enum gqgf cK;
    public static final enum gqgf cL;
    public static final enum gqgf cM;
    public static final enum gqgf cN;
    public static final enum gqgf cO;
    public static final enum gqgf cP;
    public static final enum gqgf cQ;
    public static final enum gqgf cR;
    public static final enum gqgf cS;
    public static final enum gqgf cT;
    @Deprecated
    public static final enum gqgf cU;
    public static final enum gqgf cV;
    public static final enum gqgf cW;
    public static final enum gqgf cX;
    public static final enum gqgf cY;
    public static final enum gqgf cZ;
    public static final enum gqgf ca;
    public static final enum gqgf cb;
    public static final enum gqgf cc;
    public static final enum gqgf cd;
    public static final enum gqgf ce;
    public static final enum gqgf cf;
    public static final enum gqgf cg;
    public static final enum gqgf ch;
    public static final enum gqgf ci;
    public static final enum gqgf cj;
    public static final enum gqgf ck;
    public static final enum gqgf cl;
    public static final enum gqgf cm;
    public static final enum gqgf cn;
    public static final enum gqgf co;
    public static final enum gqgf cp;
    public static final enum gqgf cq;
    public static final enum gqgf cr;
    public static final enum gqgf cs;
    public static final enum gqgf ct;
    public static final enum gqgf cu;
    public static final enum gqgf cv;
    public static final enum gqgf cw;
    public static final enum gqgf cx;
    public static final enum gqgf cy;
    public static final enum gqgf cz;
    public static final enum gqgf d;
    public static final enum gqgf dA;
    public static final enum gqgf dB;
    public static final enum gqgf dC;
    public static final enum gqgf dD;
    public static final enum gqgf dE;
    public static final enum gqgf dF;
    public static final enum gqgf dG;
    public static final enum gqgf dH;
    @Deprecated
    public static final enum gqgf dI;
    public static final enum gqgf dJ;
    public static final enum gqgf dK;
    public static final enum gqgf dL;
    public static final enum gqgf dM;
    public static final enum gqgf dN;
    public static final enum gqgf dO;
    public static final enum gqgf dP;
    public static final enum gqgf dQ;
    public static final enum gqgf dR;
    public static final enum gqgf dS;
    public static final enum gqgf dT;
    public static final enum gqgf dU;
    public static final enum gqgf dV;
    public static final enum gqgf dW;
    public static final enum gqgf dX;
    public static final enum gqgf dY;
    public static final enum gqgf dZ;
    public static final enum gqgf da;
    public static final enum gqgf db;
    public static final enum gqgf dc;
    public static final enum gqgf dd;
    public static final enum gqgf de;
    public static final enum gqgf df;
    public static final enum gqgf dg;
    public static final enum gqgf dh;
    public static final enum gqgf di;
    public static final enum gqgf dj;
    public static final enum gqgf dk;
    public static final enum gqgf dl;
    public static final enum gqgf dm;
    public static final enum gqgf dn;
    public static final enum gqgf do;
    public static final enum gqgf dp;
    public static final enum gqgf dq;
    @Deprecated
    public static final enum gqgf dr;
    public static final enum gqgf ds;
    public static final enum gqgf dt;
    public static final enum gqgf du;
    public static final enum gqgf dv;
    public static final enum gqgf dw;
    public static final enum gqgf dx;
    public static final enum gqgf dy;
    public static final enum gqgf dz;
    public static final enum gqgf e;
    public static final enum gqgf eA;
    public static final enum gqgf eB;
    public static final enum gqgf eC;
    public static final enum gqgf eD;
    public static final enum gqgf eE;
    public static final enum gqgf eF;
    public static final enum gqgf eG;
    public static final enum gqgf eH;
    public static final enum gqgf eI;
    public static final enum gqgf eJ;
    public static final enum gqgf eK;
    public static final enum gqgf eL;
    public static final enum gqgf eM;
    public static final enum gqgf eN;
    public static final enum gqgf eO;
    public static final enum gqgf eP;
    public static final enum gqgf eQ;
    public static final enum gqgf eR;
    public static final enum gqgf eS;
    public static final enum gqgf eT;
    public static final enum gqgf eU;
    public static final enum gqgf eV;
    public final String eW;
    private static final ggeo eX;
    private static final gqgf[] eY;
    public static final enum gqgf ea;
    public static final enum gqgf eb;
    public static final enum gqgf ec;
    public static final enum gqgf ed;
    public static final enum gqgf ee;
    public static final enum gqgf ef;
    public static final enum gqgf eg;
    public static final enum gqgf eh;
    @Deprecated
    public static final enum gqgf ei;
    public static final enum gqgf ej;
    public static final enum gqgf ek;
    @Deprecated
    public static final enum gqgf el;
    public static final enum gqgf em;
    public static final enum gqgf en;
    @Deprecated
    public static final enum gqgf eo;
    public static final enum gqgf ep;
    public static final enum gqgf eq;
    public static final enum gqgf er;
    public static final enum gqgf es;
    public static final enum gqgf et;
    public static final enum gqgf eu;
    public static final enum gqgf ev;
    public static final enum gqgf ew;
    public static final enum gqgf ex;
    public static final enum gqgf ey;
    public static final enum gqgf ez;
    public static final enum gqgf f;
    public static final enum gqgf g;
    public static final enum gqgf h;
    @Deprecated
    public static final enum gqgf i;
    public static final enum gqgf j;
    public static final enum gqgf k;
    public static final enum gqgf l;
    public static final enum gqgf m;
    public static final enum gqgf n;
    public static final enum gqgf o;
    public static final enum gqgf p;
    public static final enum gqgf q;
    public static final enum gqgf r;
    public static final enum gqgf s;
    public static final enum gqgf t;
    public static final enum gqgf u;
    public static final enum gqgf v;
    public static final enum gqgf w;
    public static final enum gqgf x;
    public static final enum gqgf y;
    public static final enum gqgf z;

    static {
        gqgf.a = new gqgf("AC", 0);
        gqgf.b = new gqgf("AD", 1);
        gqgf.c = new gqgf("AE", 2);
        gqgf.d = new gqgf("AF", 3);
        gqgf.e = new gqgf("AG", 4);
        gqgf.f = new gqgf("AI", 5);
        gqgf.g = new gqgf("AL", 6);
        gqgf.h = new gqgf("AM", 7);
        gqgf.i = new gqgf("AN", 8);
        gqgf.j = new gqgf("AO", 9);
        gqgf.k = new gqgf("AQ", 10);
        gqgf.l = new gqgf("AR", 11);
        gqgf.m = new gqgf("AS", 12);
        gqgf.n = new gqgf("AT", 13);
        gqgf.o = new gqgf("AU", 14);
        gqgf.p = new gqgf("AW", 15);
        gqgf.q = new gqgf("AX", 16);
        gqgf.r = new gqgf("AZ", 17);
        gqgf.s = new gqgf("BA", 18);
        gqgf.t = new gqgf("BB", 19);
        gqgf.u = new gqgf("BD", 20);
        gqgf.v = new gqgf("BE", 21);
        gqgf.w = new gqgf("BF", 22);
        gqgf.x = new gqgf("BG", 23);
        gqgf.y = new gqgf("BH", 24);
        gqgf.z = new gqgf("BI", 25);
        gqgf.A = new gqgf("BJ", 26);
        gqgf.B = new gqgf("BL", 27);
        gqgf.C = new gqgf("BM", 28);
        gqgf.D = new gqgf("BN", 29);
        gqgf.E = new gqgf("BO", 30);
        gqgf.F = new gqgf("BQ", 0x1F);
        gqgf.G = new gqgf("BR", 0x20);
        gqgf.H = new gqgf("BS", 33);
        gqgf.I = new gqgf("BT", 34);
        gqgf.J = new gqgf("BU", 35);
        gqgf.K = new gqgf("BV", 36);
        gqgf.L = new gqgf("BW", 37);
        gqgf.M = new gqgf("BY", 38);
        gqgf.N = new gqgf("BZ", 39);
        gqgf.O = new gqgf("CA", 40);
        gqgf.P = new gqgf("CC", 41);
        gqgf.Q = new gqgf("CD", 42);
        gqgf.R = new gqgf("CF", 43);
        gqgf.S = new gqgf("CG", 44);
        gqgf.T = new gqgf("CH", 45);
        gqgf.U = new gqgf("CI", 46);
        gqgf.V = new gqgf("CK", 0x2F);
        gqgf.W = new gqgf("CL", 0x30);
        gqgf.X = new gqgf("CM", 49);
        gqgf.Y = new gqgf("CN", 50);
        gqgf.Z = new gqgf("CO", 51);
        gqgf.aa = new gqgf("CP", 52);
        gqgf.ab = new gqgf("CQ", 53);
        gqgf.ac = new gqgf("CR", 54);
        gqgf.ad = new gqgf("CS", 55);
        gqgf.ae = new gqgf("CU", 56);
        gqgf.af = new gqgf("CV", 57);
        gqgf.ag = new gqgf("CW", 58);
        gqgf.ah = new gqgf("CX", 59);
        gqgf.ai = new gqgf("CY", 60);
        gqgf.aj = new gqgf("CZ", 61);
        gqgf.ak = new gqgf("DD", 62);
        gqgf.al = new gqgf("DE", 0x3F);
        gqgf.am = new gqgf("DG", 0x40);
        gqgf.an = new gqgf("DJ", 65);
        gqgf.ao = new gqgf("DK", 66);
        gqgf.ap = new gqgf("DM", 67);
        gqgf.aq = new gqgf("DO", 68);
        gqgf.ar = new gqgf("DZ", 69);
        gqgf.as = new gqgf("EA", 70);
        gqgf.at = new gqgf("EC", 71);
        gqgf.au = new gqgf("EE", 72);
        gqgf.av = new gqgf("EG", 73);
        gqgf.aw = new gqgf("EH", 74);
        gqgf.ax = new gqgf("ER", 75);
        gqgf.ay = new gqgf("ES", 76);
        gqgf.az = new gqgf("ET", 77);
        gqgf.aA = new gqgf("EU", 78);
        gqgf.aB = new gqgf("EZ", 0x4F);
        gqgf.aC = new gqgf("FI", 80);
        gqgf.aD = new gqgf("FJ", 81);
        gqgf.aE = new gqgf("FK", 82);
        gqgf.aF = new gqgf("FM", 83);
        gqgf.aG = new gqgf("FO", 84);
        gqgf.aH = new gqgf("FR", 85);
        gqgf.aI = new gqgf("FX", 86);
        gqgf.aJ = new gqgf("GA", 87);
        gqgf.aK = new gqgf("GB", 88);
        gqgf.aL = new gqgf("GD", 89);
        gqgf.aM = new gqgf("GE", 90);
        gqgf.aN = new gqgf("GF", 91);
        gqgf.aO = new gqgf("GG", 92);
        gqgf.aP = new gqgf("GH", 93);
        gqgf.aQ = new gqgf("GI", 94);
        gqgf.aR = new gqgf("GL", 0x5F);
        gqgf.aS = new gqgf("GM", 0x60);
        gqgf.aT = new gqgf("GN", 97);
        gqgf.aU = new gqgf("GP", 98);
        gqgf.aV = new gqgf("GQ", 99);
        gqgf.aW = new gqgf("GR", 100);
        gqgf.aX = new gqgf("GS", 101);
        gqgf.aY = new gqgf("GT", 102);
        gqgf.aZ = new gqgf("GU", 103);
        gqgf.ba = new gqgf("GW", 104);
        gqgf.bb = new gqgf("GY", 105);
        gqgf.bc = new gqgf("HK", 106);
        gqgf.bd = new gqgf("HM", 107);
        gqgf.be = new gqgf("HN", 108);
        gqgf.bf = new gqgf("HR", 109);
        gqgf.bg = new gqgf("HT", 110);
        gqgf.bh = new gqgf("HU", 0x6F);
        gqgf.bi = new gqgf("IC", 0x70);
        gqgf.bj = new gqgf("ID", 0x71);
        gqgf.bk = new gqgf("IE", 0x72);
        gqgf.bl = new gqgf("IL", 0x73);
        gqgf.bm = new gqgf("IM", 0x74);
        gqgf.bn = new gqgf("IN", 0x75);
        gqgf.bo = new gqgf("IO", 0x76);
        gqgf.bp = new gqgf("IQ", 0x77);
        gqgf.bq = new gqgf("IR", 120);
        gqgf.br = new gqgf("IS", 0x79);
        gqgf.bs = new gqgf("IT", 0x7A);
        gqgf.bt = new gqgf("JE", 0x7B);
        gqgf.bu = new gqgf("JM", 0x7C);
        gqgf.bv = new gqgf("JO", 0x7D);
        gqgf.bw = new gqgf("JP", 0x7E);
        gqgf.bx = new gqgf("KE", 0x7F);
        gqgf.by = new gqgf("KG", 0x80);
        gqgf.bz = new gqgf("KH", 0x81);
        gqgf.bA = new gqgf("KI", 130);
        gqgf.bB = new gqgf("KM", 0x83);
        gqgf.bC = new gqgf("KN", 0x84);
        gqgf.bD = new gqgf("KP", 0x85);
        gqgf.bE = new gqgf("KR", 0x86);
        gqgf.bF = new gqgf("KW", 0x87);
        gqgf.bG = new gqgf("KY", 0x88);
        gqgf.bH = new gqgf("KZ", 0x89);
        gqgf.bI = new gqgf("LA", 0x8A);
        gqgf.bJ = new gqgf("LB", 0x8B);
        gqgf.bK = new gqgf("LC", 140);
        gqgf.bL = new gqgf("LI", 0x8D);
        gqgf.bM = new gqgf("LK", 0x8E);
        gqgf.bN = new gqgf("LR", 0x8F);
        gqgf.bO = new gqgf("LS", 0x90);
        gqgf.bP = new gqgf("LT", 0x91);
        gqgf.bQ = new gqgf("LU", 0x92);
        gqgf.bR = new gqgf("LV", 0x93);
        gqgf.bS = new gqgf("LY", 0x94);
        gqgf.bT = new gqgf("MA", 0x95);
        gqgf.bU = new gqgf("MC", 150);
        gqgf.bV = new gqgf("MD", 0x97);
        gqgf.bW = new gqgf("ME", 0x98);
        gqgf.bX = new gqgf("MF", 0x99);
        gqgf.bY = new gqgf("MG", 0x9A);
        gqgf.bZ = new gqgf("MH", 0x9B);
        gqgf.ca = new gqgf("MK", 0x9C);
        gqgf.cb = new gqgf("ML", 0x9D);
        gqgf.cc = new gqgf("MM", 0x9E);
        gqgf.cd = new gqgf("MN", 0x9F);
        gqgf.ce = new gqgf("MO", 0xA0);
        gqgf.cf = new gqgf("MP", 0xA1);
        gqgf.cg = new gqgf("MQ", 0xA2);
        gqgf.ch = new gqgf("MR", 0xA3);
        gqgf.ci = new gqgf("MS", 0xA4);
        gqgf.cj = new gqgf("MT", 0xA5);
        gqgf.ck = new gqgf("MU", 0xA6);
        gqgf.cl = new gqgf("MV", 0xA7);
        gqgf.cm = new gqgf("MW", 0xA8);
        gqgf.cn = new gqgf("MX", 0xA9);
        gqgf.co = new gqgf("MY", 170);
        gqgf.cp = new gqgf("MZ", 0xAB);
        gqgf.cq = new gqgf("NA", 0xAC);
        gqgf.cr = new gqgf("NC", 0xAD);
        gqgf.cs = new gqgf("NE", 0xAE);
        gqgf.ct = new gqgf("NF", 0xAF);
        gqgf.cu = new gqgf("NG", 0xB0);
        gqgf.cv = new gqgf("NI", 0xB1);
        gqgf.cw = new gqgf("NL", 0xB2);
        gqgf.cx = new gqgf("NO", 0xB3);
        gqgf.cy = new gqgf("NP", 180);
        gqgf.cz = new gqgf("NR", 0xB5);
        gqgf.cA = new gqgf("NT", 0xB6);
        gqgf.cB = new gqgf("NU", 0xB7);
        gqgf.cC = new gqgf("NZ", 0xB8);
        gqgf.cD = new gqgf("OM", 0xB9);
        gqgf.cE = new gqgf("PA", 0xBA);
        gqgf.cF = new gqgf("PE", 0xBB);
        gqgf.cG = new gqgf("PF", 0xBC);
        gqgf.cH = new gqgf("PG", 0xBD);
        gqgf.cI = new gqgf("PH", 190);
        gqgf.cJ = new gqgf("PK", 0xBF);
        gqgf.cK = new gqgf("PL", 0xC0);
        gqgf.cL = new gqgf("PM", 0xC1);
        gqgf.cM = new gqgf("PN", 0xC2);
        gqgf.cN = new gqgf("PR", 0xC3);
        gqgf.cO = new gqgf("PS", 0xC4);
        gqgf.cP = new gqgf("PT", 0xC5);
        gqgf.cQ = new gqgf("PW", 0xC6);
        gqgf.cR = new gqgf("PY", 0xC7);
        gqgf.cS = new gqgf("QA", 200);
        gqgf.cT = new gqgf("QO", 201);
        gqgf.cU = new gqgf("QU", 202);
        gqgf.cV = new gqgf("RE", 203);
        gqgf.cW = new gqgf("RO", 204);
        gqgf.cX = new gqgf("RS", 205);
        gqgf.cY = new gqgf("RU", 206);
        gqgf.cZ = new gqgf("RW", 0xCF);
        gqgf.da = new gqgf("SA", 0xD0);
        gqgf.db = new gqgf("SB", 209);
        gqgf.dc = new gqgf("SC", 210);
        gqgf.dd = new gqgf("SD", 0xD3);
        gqgf.de = new gqgf("SE", 0xD4);
        gqgf.df = new gqgf("SG", 0xD5);
        gqgf.dg = new gqgf("SH", 0xD6);
        gqgf.dh = new gqgf("SI", 0xD7);
        gqgf.di = new gqgf("SJ", 0xD8);
        gqgf.dj = new gqgf("SK", 0xD9);
        gqgf.dk = new gqgf("SL", 0xDA);
        gqgf.dl = new gqgf("SM", 0xDB);
        gqgf.dm = new gqgf("SN", 220);
        gqgf.dn = new gqgf("SO", 0xDD);
        gqgf.do = new gqgf("SR", 0xDE);
        gqgf.dp = new gqgf("SS", 0xDF);
        gqgf.dq = new gqgf("ST", 0xE0);
        gqgf.dr = new gqgf("SU", 0xE1);
        gqgf.ds = new gqgf("SV", 0xE2);
        gqgf.dt = new gqgf("SX", 0xE3);
        gqgf.du = new gqgf("SY", 0xE4);
        gqgf.dv = new gqgf("SZ", 0xE5);
        gqgf.dw = new gqgf("TA", 230);
        gqgf.dx = new gqgf("TC", 0xE7);
        gqgf.dy = new gqgf("TD", 0xE8);
        gqgf.dz = new gqgf("TF", 0xE9);
        gqgf.dA = new gqgf("TG", 0xEA);
        gqgf.dB = new gqgf("TH", 0xEB);
        gqgf.dC = new gqgf("TJ", 0xEC);
        gqgf.dD = new gqgf("TK", 0xED);
        gqgf.dE = new gqgf("TL", 0xEE);
        gqgf.dF = new gqgf("TM", 0xEF);
        gqgf.dG = new gqgf("TN", 0xF0);
        gqgf.dH = new gqgf("TO", 0xF1);
        gqgf.dI = new gqgf("TP", 0xF2);
        gqgf.dJ = new gqgf("TR", 0xF3);
        gqgf.dK = new gqgf("TT", 0xF4);
        gqgf.dL = new gqgf("TV", 0xF5);
        gqgf.dM = new gqgf("TW", 0xF6);
        gqgf.dN = new gqgf("TZ", 0xF7);
        gqgf.dO = new gqgf("UA", 0xF8);
        gqgf.dP = new gqgf("UG", 0xF9);
        gqgf.dQ = new gqgf("UM", 0xFA);
        gqgf.dR = new gqgf("UN", 0xFB);
        gqgf.dS = new gqgf("US", 0xFC);
        gqgf.dT = new gqgf("UY", 0xFD);
        gqgf.dU = new gqgf("UZ", 0xFE);
        gqgf.dV = new gqgf("VA", 0xFF);
        gqgf.dW = new gqgf("VC", 0x100);
        gqgf.dX = new gqgf("VE", 0x101);
        gqgf.dY = new gqgf("VG", 0x102);
        gqgf.dZ = new gqgf("VI", 0x103);
        gqgf.ea = new gqgf("VN", 260);
        gqgf.eb = new gqgf("VU", 0x105);
        gqgf.ec = new gqgf("WF", 0x106);
        gqgf.ed = new gqgf("WS", 0x107);
        gqgf.ee = new gqgf("XA", 0x108);
        gqgf.ef = new gqgf("XB", 0x109);
        gqgf.eg = new gqgf("XC", 0x10A);
        gqgf.eh = new gqgf("XK", 0x10B);
        gqgf.ei = new gqgf("YD", 0x10C);
        gqgf.ej = new gqgf("YE", 0x10D);
        gqgf.ek = new gqgf("YT", 270);
        gqgf.el = new gqgf("YU", 0x10F);
        gqgf.em = new gqgf("ZA", 0x110);
        gqgf.en = new gqgf("ZM", 273);
        gqgf.eo = new gqgf("ZR", 274);
        gqgf.ep = new gqgf("ZW", 275);
        gqgf.eq = new gqgf("ZZ", 276);
        gqgf.er = new gqgf("UN001", 277, "001");
        gqgf.es = new gqgf("UN002", 278, "002");
        gqgf.et = new gqgf("UN003", 279, "003");
        gqgf.eu = new gqgf("UN005", 280, "005");
        gqgf.ev = new gqgf("UN009", 281, "009");
        gqgf.ew = new gqgf("UN011", 282, "011");
        gqgf.ex = new gqgf("UN013", 283, "013");
        gqgf.ey = new gqgf("UN014", 284, "014");
        gqgf.ez = new gqgf("UN015", 285, "015");
        gqgf.eA = new gqgf("UN017", 286, "017");
        gqgf.eB = new gqgf("UN018", 0x11F, "018");
        gqgf.eC = new gqgf("UN019", 0x120, "019");
        gqgf.eD = new gqgf("UN021", 289, "021");
        gqgf.eE = new gqgf("UN029", 290, "029");
        gqgf.eF = new gqgf("UN030", 291, "030");
        gqgf.eG = new gqgf("UN034", 292, "034");
        gqgf.eH = new gqgf("UN035", 293, "035");
        gqgf.eI = new gqgf("UN039", 294, "039");
        gqgf.eJ = new gqgf("UN053", 295, "053");
        gqgf.eK = new gqgf("UN054", 296, "054");
        gqgf.eL = new gqgf("UN057", 297, "057");
        gqgf.eM = new gqgf("UN061", 298, "061");
        gqgf.eN = new gqgf("UN142", 299, "142");
        gqgf.eO = new gqgf("UN143", 300, "143");
        gqgf.eP = new gqgf("UN145", 301, "145");
        gqgf.eQ = new gqgf("UN150", 302, "150");
        gqgf.eR = new gqgf("UN151", 303, "151");
        gqgf.eS = new gqgf("UN154", 304, "154");
        gqgf.eT = new gqgf("UN155", 305, "155");
        gqgf.eU = new gqgf("UN202", 306, "202");
        gqgf.eV = new gqgf("UN419", 307, "419");
        gqgf.eY = gqgf.d();
        ggfp.O(gqgf.i, gqgf.J, gqgf.ad, gqgf.ak, gqgf.aI, gqgf.cA, new gqgf[]{gqgf.cU, gqgf.dr, gqgf.dI, gqgf.ei, gqgf.el, gqgf.eo});
        gqgf[] arr_gqgf = gqgf.values();
        ggek ggek0 = new ggek();
        for(int v = 0; v < arr_gqgf.length; ++v) {
            gqgf gqgf0 = arr_gqgf[v];
            ggek0.i(gqgf0.toString(), gqgf0);
        }
        ggek0.i("UK", gqgf.aK);
        gqgf.eX = ggek0.b();
    }

    private gqgf(String s, int v) {
        super(s, v);
        this.eW = this.name();
    }

    private gqgf(String s, int v, String s1) {
        super(s, v);
        this.eW = s1;
    }

    public static gqgf a(String s) {
        gqgf gqgf0 = gqgf.c(s);
        if(gqgf0 != null) {
            return gqgf0;
        }
        throw new IllegalArgumentException(a.a(s, "\'", "\' is not a valid CLDR region code."));
    }

    public static gqgf b(String s) {
        gqgf gqgf0 = gqgf.c(s);
        return gqgf0 == null ? gqgf.eq : gqgf0;
    }

    private static gqgf c(String s) {
        String s1 = gfqz.d(s);
        return (gqgf)gqgf.eX.get(s1);
    }

    private static gqgf[] d() {
        return new gqgf[]{gqgf.a, gqgf.b, gqgf.c, gqgf.d, gqgf.e, gqgf.f, gqgf.g, gqgf.h, gqgf.i, gqgf.j, gqgf.k, gqgf.l, gqgf.m, gqgf.n, gqgf.o, gqgf.p, gqgf.q, gqgf.r, gqgf.s, gqgf.t, gqgf.u, gqgf.v, gqgf.w, gqgf.x, gqgf.y, gqgf.z, gqgf.A, gqgf.B, gqgf.C, gqgf.D, gqgf.E, gqgf.F, gqgf.G, gqgf.H, gqgf.I, gqgf.J, gqgf.K, gqgf.L, gqgf.M, gqgf.N, gqgf.O, gqgf.P, gqgf.Q, gqgf.R, gqgf.S, gqgf.T, gqgf.U, gqgf.V, gqgf.W, gqgf.X, gqgf.Y, gqgf.Z, gqgf.aa, gqgf.ab, gqgf.ac, gqgf.ad, gqgf.ae, gqgf.af, gqgf.ag, gqgf.ah, gqgf.ai, gqgf.aj, gqgf.ak, gqgf.al, gqgf.am, gqgf.an, gqgf.ao, gqgf.ap, gqgf.aq, gqgf.ar, gqgf.as, gqgf.at, gqgf.au, gqgf.av, gqgf.aw, gqgf.ax, gqgf.ay, gqgf.az, gqgf.aA, gqgf.aB, gqgf.aC, gqgf.aD, gqgf.aE, gqgf.aF, gqgf.aG, gqgf.aH, gqgf.aI, gqgf.aJ, gqgf.aK, gqgf.aL, gqgf.aM, gqgf.aN, gqgf.aO, gqgf.aP, gqgf.aQ, gqgf.aR, gqgf.aS, gqgf.aT, gqgf.aU, gqgf.aV, gqgf.aW, gqgf.aX, gqgf.aY, gqgf.aZ, gqgf.ba, gqgf.bb, gqgf.bc, gqgf.bd, gqgf.be, gqgf.bf, gqgf.bg, gqgf.bh, gqgf.bi, gqgf.bj, gqgf.bk, gqgf.bl, gqgf.bm, gqgf.bn, gqgf.bo, gqgf.bp, gqgf.bq, gqgf.br, gqgf.bs, gqgf.bt, gqgf.bu, gqgf.bv, gqgf.bw, gqgf.bx, gqgf.by, gqgf.bz, gqgf.bA, gqgf.bB, gqgf.bC, gqgf.bD, gqgf.bE, gqgf.bF, gqgf.bG, gqgf.bH, gqgf.bI, gqgf.bJ, gqgf.bK, gqgf.bL, gqgf.bM, gqgf.bN, gqgf.bO, gqgf.bP, gqgf.bQ, gqgf.bR, gqgf.bS, gqgf.bT, gqgf.bU, gqgf.bV, gqgf.bW, gqgf.bX, gqgf.bY, gqgf.bZ, gqgf.ca, gqgf.cb, gqgf.cc, gqgf.cd, gqgf.ce, gqgf.cf, gqgf.cg, gqgf.ch, gqgf.ci, gqgf.cj, gqgf.ck, gqgf.cl, gqgf.cm, gqgf.cn, gqgf.co, gqgf.cp, gqgf.cq, gqgf.cr, gqgf.cs, gqgf.ct, gqgf.cu, gqgf.cv, gqgf.cw, gqgf.cx, gqgf.cy, gqgf.cz, gqgf.cA, gqgf.cB, gqgf.cC, gqgf.cD, gqgf.cE, gqgf.cF, gqgf.cG, gqgf.cH, gqgf.cI, gqgf.cJ, gqgf.cK, gqgf.cL, gqgf.cM, gqgf.cN, gqgf.cO, gqgf.cP, gqgf.cQ, gqgf.cR, gqgf.cS, gqgf.cT, gqgf.cU, gqgf.cV, gqgf.cW, gqgf.cX, gqgf.cY, gqgf.cZ, gqgf.da, gqgf.db, gqgf.dc, gqgf.dd, gqgf.de, gqgf.df, gqgf.dg, gqgf.dh, gqgf.di, gqgf.dj, gqgf.dk, gqgf.dl, gqgf.dm, gqgf.dn, gqgf.do, gqgf.dp, gqgf.dq, gqgf.dr, gqgf.ds, gqgf.dt, gqgf.du, gqgf.dv, gqgf.dw, gqgf.dx, gqgf.dy, gqgf.dz, gqgf.dA, gqgf.dB, gqgf.dC, gqgf.dD, gqgf.dE, gqgf.dF, gqgf.dG, gqgf.dH, gqgf.dI, gqgf.dJ, gqgf.dK, gqgf.dL, gqgf.dM, gqgf.dN, gqgf.dO, gqgf.dP, gqgf.dQ, gqgf.dR, gqgf.dS, gqgf.dT, gqgf.dU, gqgf.dV, gqgf.dW, gqgf.dX, gqgf.dY, gqgf.dZ, gqgf.ea, gqgf.eb, gqgf.ec, gqgf.ed, gqgf.ee, gqgf.ef, gqgf.eg, gqgf.eh, gqgf.ei, gqgf.ej, gqgf.ek, gqgf.el, gqgf.em, gqgf.en, gqgf.eo, gqgf.ep, gqgf.eq, gqgf.er, gqgf.es, gqgf.et, gqgf.eu, gqgf.ev, gqgf.ew, gqgf.ex, gqgf.ey, gqgf.ez, gqgf.eA, gqgf.eB, gqgf.eC, gqgf.eD, gqgf.eE, gqgf.eF, gqgf.eG, gqgf.eH, gqgf.eI, gqgf.eJ, gqgf.eK, gqgf.eL, gqgf.eM, gqgf.eN, gqgf.eO, gqgf.eP, gqgf.eQ, gqgf.eR, gqgf.eS, gqgf.eT, gqgf.eU, gqgf.eV};
    }

    @Override
    public final String toString() {
        return this.eW;
    }

    public static gqgf[] values() {
        return (gqgf[])gqgf.eY.clone();
    }
}

