public enum gqtg implements hfub {
    PASSWORD_MANAGER_EVENT_ACTION_UNSPECIFIED(0),
    PWM_PASSWORD_SHARING_SENDING_STARTED(1),
    PWM_PASSWORD_SHARING_SENDING_CONCLUDED(2),
    PWM_PASSWORD_SHARING_CREDENTIALS_NEW(3),
    PWM_PASSWORD_SHARING_CREDENTIALS_DUPLICATE(4),
    PWM_PASSWORD_SHARING_CREDENTIALS_CONFLICT_WITH_NONE_SHARED(5),
    PWM_PASSWORD_SHARING_CREDENTIALS_CONFLICT_WITH_SHARED_SAME_SENDER(6),
    PWM_PASSWORD_SHARING_CREDENTIALS_CONFLICT_WITH_SHARED_DIFFERENT_SENDER(7),
    PWM_SWITCH_TO_LOCAL_ACCOUNT(8),
    PWM_SWITCH_TO_SYNCED_ACCOUNT(9),
    PWM_PASSWORD_SHARING_FAMILY_PICKER_OPENED(10),
    PWM_PASSWORD_SHARING_SENDING_STARTED_AFTER_PICKING_RECIPIENTS(11),
    PWM_PASSWORD_SHARING_USER_CANCELLED_IN_PROGRESS_SENDING(12),
    PWM_REAUTH_BEFORE_FILLING_ON(13),
    PWM_REAUTH_BEFORE_FILLING_OFF(14),
    PWM_REAUTH_BEFORE_FILLING_DISABLED(15),
    PWM_REAUTH_BEFORE_FILLING_SET_API_CALL_VALUE_ON(16),
    PWM_REAUTH_BEFORE_FILLING_SET_API_CALL_VALUE_OFF(17),
    PWM_REAUTH_BEFORE_FILLING_TURNED_ON(18),
    PWM_REAUTH_BEFORE_FILLING_TURNED_OFF(19),
    PWM_DELETE_ALL_STARTED(20),
    PWM_DELETE_ALL_CONFIRMED(21),
    PWM_DELETE_ALL_SUCCESS(22),
    PWM_DELETE_ALL_FAILURE(23),
    PWM_AUTOMATIC_PASSKEY_UPGRADES_TURNED_ON(24),
    PWM_AUTOMATIC_PASSKEY_UPGRADES_TURNED_OFF(25),
    PWM_OSMOSIS_IMPORT_STARTED(26),
    PWM_OSMOSIS_IMPORT_ALL_TYPES_SUCCEEDED(27),
    PWM_OSMOSIS_IMPORT_PARTIAL_SUCCESS(28),
    PWM_OSMOSIS_IMPORT_ALL_TYPES_FAILED(29),
    PWM_OSMOSIS_IMPORT_NO_GOOGLE_ACCOUNT(30),
    PWM_OSMOSIS_IMPORT_CXF_PARSING_FAILED(0x1F),
    PWM_OSMOSIS_IMPORT_PASSWORDS_ZERO_PROVIDED(0x20),
    PWM_OSMOSIS_IMPORT_PASSWORDS_ALL_CONFLICTING(33),
    PWM_OSMOSIS_IMPORT_PASSWORDS_SOME_CONFLICTING(34),
    PWM_OSMOSIS_IMPORT_PASSWORDS_NONE_CONFLICTING(35),
    PWM_OSMOSIS_IMPORT_PASSWORDS_USER_INTERACTION_REQUIRED(36),
    PWM_OSMOSIS_IMPORT_PASSWORDS_UNRESOLVABLE_ERROR(37),
    PWM_OSMOSIS_IMPORT_PASSKEYS_ZERO_PROVIDED(38),
    PWM_OSMOSIS_IMPORT_PASSKEYS_ALL_CONFLICTING(39),
    PWM_OSMOSIS_IMPORT_PASSKEYS_SOME_CONFLICTING(40),
    PWM_OSMOSIS_IMPORT_PASSKEYS_NONE_CONFLICTING(41),
    PWM_OSMOSIS_IMPORT_PASSKEYS_USER_INTERACTION_REQUIRED(42),
    PWM_OSMOSIS_IMPORT_PASSKEYS_UNRESOLVABLE_ERROR(43),
    PWM_OSMOSIS_EXPORT_STARTED(44),
    PWM_OSMOSIS_GET_CAPABILITIES_STARTED(45),
    PWM_OSMOSIS_EXPORT_CXF_CREATION_FAILED(46),
    PWM_OSMOSIS_EXPORT_CXP_PARSING_FAILED(0x2F),
    PWM_OSMOSIS_EXPORT_ALL_TYPES_SUCCEEDED(0x30),
    PWM_OSMOSIS_EXPORT_PARTIAL_SUCCESS(49),
    PWM_OSMOSIS_EXPORT_ALL_REQUESTED_TYPES_FAILED(50),
    PWM_OSMOSIS_EXPORT_NO_GOOGLE_ACCOUNT(51),
    PWM_OSMOSIS_EXPORT_PASSWORDS_NOT_REQUESTED(52),
    PWM_OSMOSIS_EXPORT_PASSWORDS_ZERO_EXPORTED(53),
    PWM_OSMOSIS_EXPORT_PASSWORDS_SOME_EXPORTED(54),
    PWM_OSMOSIS_EXPORT_PASSWORDS_USER_INTERACTION_REQUIRED(55),
    PWM_OSMOSIS_EXPORT_PASSWORDS_UNRESOLVABLE_ERROR(56),
    PWM_OSMOSIS_EXPORT_PASSKEYS_NOT_REQUESTED(57),
    PWM_OSMOSIS_EXPORT_PASSKEYS_ZERO_EXPORTED(58),
    PWM_OSMOSIS_EXPORT_PASSKEYS_SOME_EXPORTED(59),
    PWM_OSMOSIS_EXPORT_PASSKEYS_USER_INTERACTION_REQUIRED(60),
    PWM_OSMOSIS_EXPORT_PASSKEYS_UNRESOLVABLE_ERROR(61);

    public final int ak;

    private gqtg(int v1) {
        this.ak = v1;
    }

    @Override  // hfub
    public final int a() {
        return this.ak;
    }

    @Override
    public final String toString() {
        return Integer.toString(this.ak);
    }
}

