public enum gssm implements hfub {
    EXTENSION_UNSPECIFIED(0),
    CREATE_PERSON(1),
    FILTER_BY_NAME(2),
    MODIFY_NAMES(3),
    PHONE_CANONICALIZATION(54),
    INCLUDE_DOMAIN_INFO(5),
    GDATA_COMPATIBILITY(8),
    ABOUT_ME_ADDITIONAL_DATA(10),
    SANITIZE_ABOUT_HTML(13),
    FILTER_URL_IANTS(16),
    TLS_ADD_PLACEHOLDER_PEOPLE(14),
    TLS_FILL_FIELD(15),
    DYNAMITE_ADDITIONAL_DATA(17),
    DYNAMITE_ORGANIZATION_INFO(27),
    DYNAMITE_DEDUPE_FIELDS(53),
    CALLER_ID_LOOKUPS(21),
    POMEROY_TRUSTED_CONTACTS_EXTENSION(22),
    FILTER_UNVERIFIED_PROFILE_FIELDS(23),
    FILTER_OBSOLETE_CONTACT_EMAILS(35),
    REMOVE_NON_DOMAIN_EMAILS(24),
    PHOTOS_COMPARE_DATA(28),
    SIGN_PHOTOS_IANTS(30),
    FILTER_TO_PRIMARY(0x1F),
    DESK_LOCATION_ADDITIONAL_DATA(0x20),
    FILTER_UNUSED_FIELDS(33),
    GMAIL_SECURITY_DATA(34),
    INCLUDE_EMAIL_LOOKUP_KEY(36),
    DYNAMITE_APPEND_ROOM_MEMBERSHIP_DATA(37),
    FILTER_NON_PRIMARY_SIGNUP_EMAIL(38),
    PAISA_ADDITIONAL_DATA(39),
    CUSTOMER_INFO_ADDITIONAL_DATA(40),
    ADD_PEOPLE_FOR_UNMATCHED_KEYS(42),
    PLAY_GAMES_PROFILE(43),
    JAM_MAPS_PROFILE(44),
    JAM_YOUTUBE_PROFILE(45),
    JAM_GPAY_PROFILE(46),
    PEOPLE_STACK_ANNOTATE_HIDDEN(0x2F),
    PEOPLE_STACK_REMOVE_HIDDEN(0x30),
    PEOPLE_STACK_ANNOTATE_FAMILY(49),
    PEOPLE_STACK_ANNOTATE_PEOPLE_WITH_BIRTHDAYS(50),
    INCLUDE_ACCOUNT_LOCALE(52),
    MERGE_DOMAIN_CONTACT_DATA(55),
    FILTER_REGISTERED_SERVICE_FOR_MEET(56),
    PREFER_GUEST_USERS(57),
    @Deprecated
    HANGOUTS_PHONE_DATA(4),
    @Deprecated
    HANGOUTS_ADDITIONAL_DATA(6),
    @Deprecated
    HANGOUTS_SUGGESTED_PEOPLE(7),
    @Deprecated
    HANGOUTS_OFF_NETWORK_GAIA_GET(9),
    @Deprecated
    HANGOUTS_OFF_NETWORK_GAIA_LOOKUP(12),
    @Deprecated
    DEPRECATED_ADD_HANGOUTS_RELEVANT_PEOPLE(11),
    @Deprecated
    DEPRECATED_DYNAMITE_DM_BOTS(18),
    @Deprecated
    DEPRECATED_DYNAMITE_ROOM_BOTS(19),
    @Deprecated
    DEPRECATED_APPS_WALDO_AVAILABILITY_DATA(29),
    @Deprecated
    TEAMS_ADDITIONAL_DATA(25),
    @Deprecated
    DEPRECATED_CORP_DESKBOOKING_FLEXIBLE_DESK_LOCATIONS(41),
    UNRECOGNIZED(-1);

    private final int af;

    private gssm(int v1) {
        this.af = v1;
    }

    @Override  // hfub
    public final int a() {
        if(this != gssm.ad) {
            return this.af;
        }
        throw new IllegalArgumentException("Can\'t get the number of an unknown enum value.");
    }

    @Override
    public final String toString() {
        return Integer.toString(this.af);
    }
}

