// PARTIAL FAILURE: ENUM SUGARING
// The enumeration is rendered as-is instead of being sugared into a Java 5 enum.
public final class gzww extends Enum implements hfub {
    public static final enum gzww A;
    public static final enum gzww B;
    public static final enum gzww C;
    public static final enum gzww D;
    @Deprecated
    public static final enum gzww E;
    public static final enum gzww F;
    public static final enum gzww G;
    public static final enum gzww H;
    @Deprecated
    public static final enum gzww I;
    @Deprecated
    public static final enum gzww J;
    public static final enum gzww K;
    public static final enum gzww L;
    public static final enum gzww M;
    @Deprecated
    public static final enum gzww N;
    @Deprecated
    public static final enum gzww O;
    @Deprecated
    public static final enum gzww P;
    @Deprecated
    public static final enum gzww Q;
    @Deprecated
    public static final enum gzww R;
    @Deprecated
    public static final enum gzww S;
    public static final enum gzww T;
    public static final enum gzww U;
    public static final enum gzww V;
    @Deprecated
    public static final enum gzww W;
    public static final enum gzww X;
    public static final enum gzww Y;
    public static final enum gzww Z;
    public static final enum gzww a;
    public static final enum gzww aA;
    public static final enum gzww aB;
    public static final enum gzww aC;
    public static final enum gzww aD;
    public static final enum gzww aE;
    public static final enum gzww aF;
    public static final enum gzww aG;
    public static final enum gzww aH;
    public static final enum gzww aI;
    public static final enum gzww aJ;
    public static final enum gzww aK;
    public static final enum gzww aL;
    public static final enum gzww aM;
    public static final enum gzww aN;
    public static final enum gzww aO;
    public static final enum gzww aP;
    public static final enum gzww aQ;
    public static final enum gzww aR;
    public static final enum gzww aS;
    public static final enum gzww aT;
    public static final enum gzww aU;
    public static final enum gzww aV;
    public static final enum gzww aW;
    public static final enum gzww aX;
    public static final enum gzww aY;
    public static final enum gzww aZ;
    public static final enum gzww aa;
    public static final enum gzww ab;
    public static final enum gzww ac;
    public static final enum gzww ad;
    public static final enum gzww ae;
    public static final enum gzww af;
    public static final enum gzww ag;
    public static final enum gzww ah;
    public static final enum gzww ai;
    public static final enum gzww aj;
    public static final enum gzww ak;
    public static final enum gzww al;
    public static final enum gzww am;
    public static final enum gzww an;
    public static final enum gzww ao;
    public static final enum gzww ap;
    public static final enum gzww aq;
    public static final enum gzww ar;
    public static final enum gzww as;
    public static final enum gzww at;
    public static final enum gzww au;
    public static final enum gzww av;
    public static final enum gzww aw;
    public static final enum gzww ax;
    public static final enum gzww ay;
    public static final enum gzww az;
    public static final enum gzww b;
    public static final enum gzww bA;
    public static final enum gzww bB;
    public static final enum gzww bC;
    public static final enum gzww bD;
    public static final enum gzww bE;
    public static final enum gzww bF;
    public static final enum gzww bG;
    public static final enum gzww bH;
    public static final enum gzww bI;
    public static final enum gzww bJ;
    public static final enum gzww bK;
    public static final enum gzww bL;
    public static final enum gzww bM;
    public static final enum gzww bN;
    public static final enum gzww bO;
    public static final enum gzww bP;
    public static final enum gzww bQ;
    public static final enum gzww bR;
    public static final enum gzww bS;
    public static final enum gzww bT;
    public static final enum gzww bU;
    public static final enum gzww bV;
    public static final enum gzww bW;
    public static final enum gzww bX;
    public static final enum gzww bY;
    public static final enum gzww bZ;
    public static final enum gzww ba;
    @Deprecated
    public static final enum gzww bb;
    @Deprecated
    public static final enum gzww bc;
    @Deprecated
    public static final enum gzww bd;
    @Deprecated
    public static final enum gzww be;
    public static final enum gzww bf;
    @Deprecated
    public static final enum gzww bg;
    @Deprecated
    public static final enum gzww bh;
    @Deprecated
    public static final enum gzww bi;
    @Deprecated
    public static final enum gzww bj;
    public static final enum gzww bk;
    public static final enum gzww bl;
    public static final enum gzww bm;
    public static final enum gzww bn;
    public static final enum gzww bo;
    public static final enum gzww bp;
    public static final enum gzww bq;
    public static final enum gzww br;
    public static final enum gzww bs;
    public static final enum gzww bt;
    public static final enum gzww bu;
    public static final enum gzww bv;
    public static final enum gzww bw;
    public static final enum gzww bx;
    public static final enum gzww by;
    public static final enum gzww bz;
    public static final enum gzww c;
    public static final enum gzww cA;
    public static final enum gzww cB;
    public static final enum gzww cC;
    public static final enum gzww cD;
    public static final enum gzww cE;
    public static final enum gzww cF;
    public static final enum gzww cG;
    public static final enum gzww cH;
    public static final enum gzww cI;
    public static final enum gzww cJ;
    public static final enum gzww cK;
    public static final enum gzww cL;
    public static final enum gzww cM;
    public static final enum gzww cN;
    public static final enum gzww cO;
    public static final enum gzww cP;
    public static final enum gzww cQ;
    public static final enum gzww cR;
    public static final enum gzww cS;
    public static final enum gzww cT;
    public static final enum gzww cU;
    public static final enum gzww cV;
    public static final enum gzww cW;
    public static final enum gzww cX;
    public static final enum gzww cY;
    public static final enum gzww cZ;
    public static final enum gzww ca;
    public static final enum gzww cb;
    public static final enum gzww cc;
    public static final enum gzww cd;
    public static final enum gzww ce;
    public static final enum gzww cf;
    public static final enum gzww cg;
    public static final enum gzww ch;
    public static final enum gzww ci;
    public static final enum gzww cj;
    public static final enum gzww ck;
    public static final enum gzww cl;
    public static final enum gzww cm;
    public static final enum gzww cn;
    public static final enum gzww co;
    public static final enum gzww cp;
    public static final enum gzww cq;
    public static final enum gzww cr;
    public static final enum gzww cs;
    public static final enum gzww ct;
    public static final enum gzww cu;
    public static final enum gzww cv;
    public static final enum gzww cw;
    public static final enum gzww cx;
    public static final enum gzww cy;
    public static final enum gzww cz;
    public static final enum gzww d;
    public final int dA;
    private static final gzww[] dB;
    public static final enum gzww da;
    public static final enum gzww db;
    public static final enum gzww dc;
    public static final enum gzww dd;
    public static final enum gzww de;
    public static final enum gzww df;
    public static final enum gzww dg;
    public static final enum gzww dh;
    public static final enum gzww di;
    public static final enum gzww dj;
    public static final enum gzww dk;
    public static final enum gzww dl;
    public static final enum gzww dm;
    public static final enum gzww dn;
    public static final enum gzww do;
    public static final enum gzww dp;
    public static final enum gzww dq;
    public static final enum gzww dr;
    public static final enum gzww ds;
    public static final enum gzww dt;
    public static final enum gzww du;
    public static final enum gzww dv;
    public static final enum gzww dw;
    public static final enum gzww dx;
    public static final enum gzww dy;
    public static final enum gzww dz;
    public static final enum gzww e;
    public static final enum gzww f;
    public static final enum gzww g;
    public static final enum gzww h;
    public static final enum gzww i;
    public static final enum gzww j;
    public static final enum gzww k;
    public static final enum gzww l;
    public static final enum gzww m;
    public static final enum gzww n;
    public static final enum gzww o;
    public static final enum gzww p;
    public static final enum gzww q;
    public static final enum gzww r;
    public static final enum gzww s;
    public static final enum gzww t;
    public static final enum gzww u;
    public static final enum gzww v;
    public static final enum gzww w;
    public static final enum gzww x;
    public static final enum gzww y;
    public static final enum gzww z;

    static {
        gzww.a = new gzww("UNKNOWN_EVENT", 0, 0);
        gzww.b = new gzww("LOCATION_UPDATE", 1, 0xB3);
        gzww.c = new gzww("VISIT_UNKNOWN", 2, 180);
        gzww.d = new gzww("VISIT_ARRIVAL", 3, 0xB5);
        gzww.e = new gzww("VISIT_DEPARTURE", 4, 0xB6);
        gzww.f = new gzww("GEOFENCE_UNKNOWN", 5, 0xB7);
        gzww.g = new gzww("GEOFENCE_ENTRANCE", 6, 0xB8);
        gzww.h = new gzww("GEOFENCE_EXIT", 7, 0xB9);
        gzww.i = new gzww("BLE_SCAN_UNKNOWN", 8, 0xBA);
        gzww.j = new gzww("BLE_SCAN_UID", 9, 0xBB);
        gzww.k = new gzww("BLE_SCAN_URL", 10, 0xBC);
        gzww.l = new gzww("BLE_SCAN_TLM", 11, 0xBD);
        gzww.m = new gzww("BLE_SCAN_EIDR", 12, 190);
        gzww.n = new gzww("BLE_SCAN_GBEACONV1", 13, 0xBF);
        gzww.o = new gzww("BLE_SCAN_IBEACON", 14, 0xC0);
        gzww.p = new gzww("BLE_SCAN_BATCH", 15, 0xC1);
        gzww.q = new gzww("WIFI_SCAN", 16, 0x97);
        gzww.r = new gzww("BURST_PULSE", 17, 0xC2);
        gzww.s = new gzww("EXPEDITED_LOCATION", 18, 0xC3);
        gzww.t = new gzww("SLC_TRIGGER", 19, 1);
        gzww.u = new gzww("VISIT_ARRIVAL_TRIGGER", 20, 2);
        gzww.v = new gzww("VISIT_DEPARTURE_TRIGGER", 21, 3);
        gzww.w = new gzww("GEOFENCE_ENTER_TRIGGER", 22, 4);
        gzww.x = new gzww("GEOFENCE_EXIT_TRIGGER", 23, 5);
        gzww.y = new gzww("GEOFENCE_UNKNOWN_TRIGGER", 24, 0x8D);
        gzww.z = new gzww("BLE_SCAN_TRIGGER", 25, 6);
        gzww.A = new gzww("HEARTBEAT_TRIGGER", 26, 7);
        gzww.B = new gzww("BURST_TRIGGER", 27, 8);
        gzww.C = new gzww("EXPEDITED_LOCATION_TRIGGER", 28, 9);
        gzww.D = new gzww("LOCATION_COLLECTION_DID_START", 29, 10);
        gzww.E = new gzww("LOCATION_COLLECTION_DID_GET_LOCATION_FIX", 30, 11);
        gzww.F = new gzww("LOCATION_COLLECTION_DID_FINISH", 0x1F, 12);
        gzww.G = new gzww("LOCATION_COLLECTION_DID_CANCEL", 0x20, 13);
        gzww.H = new gzww("VISIT_COLLECTION_DID_START", 33, 14);
        gzww.I = new gzww("VISIT_COLLECTION_DID_COLLECT_VISIT_ARRIVAL", 34, 15);
        gzww.J = new gzww("VISIT_COLLECTION_DID_COLLECT_VISIT_DEPARTURE", 35, 16);
        gzww.K = new gzww("VISIT_COLLECTION_DID_FINISH", 36, 17);
        gzww.L = new gzww("VISIT_COLLECTION_DID_CANCEL", 37, 18);
        gzww.M = new gzww("BLE_SCAN_COLLECTION_DID_START", 38, 19);
        gzww.N = new gzww("BLE_SCAN_COLLECTION_DID_COLLECT_BLE_SCAN_UNKNOWN", 39, 20);
        gzww.O = new gzww("BLE_SCAN_COLLECTION_DID_COLLECT_BLE_SCAN_UID", 40, 21);
        gzww.P = new gzww("BLE_SCAN_COLLECTION_DID_COLLECT_BLE_SCAN_URL", 41, 22);
        gzww.Q = new gzww("BLE_SCAN_COLLECTION_DID_COLLECT_BLE_SCAN_TLM", 42, 23);
        gzww.R = new gzww("BLE_SCAN_COLLECTION_DID_COLLECT_BLE_SCAN_EIDR", 43, 24);
        gzww.S = new gzww("BLE_SCAN_COLLECTION_DID_FINISH", 44, 25);
        gzww.T = new gzww("BLE_SCAN_COLLECTION_DID_FINISH_UNKNOWN_REASON", 45, 0x95);
        gzww.U = new gzww("BLE_SCAN_COLLECTION_DID_FINISH_FINISH_EARLY_NO_SCANS_SEEN", 46, 0x8F);
        gzww.V = new gzww("BLE_SCAN_COLLECTION_DID_FINISH_COMPLETE", 0x2F, 0x90);
        gzww.W = new gzww("BLE_SCAN_COLLECTION_DID_CANCEL", 0x30, 26);
        gzww.X = new gzww("BLE_SCAN_COLLECTION_DID_CANCEL_UNKNOWN_REASON", 49, 150);
        gzww.Y = new gzww("BLE_SCAN_COLLECTION_DID_CANCEL_STATE_CHANGE", 50, 0x91);
        gzww.Z = new gzww("BLE_SCAN_COLLECTION_DID_CANCEL_SHOULD_NOT_BE_COLLECTING", 51, 0x92);
        gzww.aa = new gzww("BLE_SCAN_COLLECTION_DID_CANCEL_TOO_MANY_BLE_SCANS", 52, 0x93);
        gzww.ab = new gzww("BLE_SCAN_COLLECTION_DID_CANCEL_SENDING_LOCATION_REPORT", 53, 0x94);
        gzww.ac = new gzww("MOTION_COLLECTION_DID_START", 54, 27);
        gzww.ad = new gzww("MOTION_COLLECTION_DID_FINISH", 55, 28);
        gzww.ae = new gzww("MOTION_COLLECTION_DID_CANCEL", 56, 29);
        gzww.af = new gzww("POLICY_COMPUTER_STATE_CHANGED", 57, 0x98);
        gzww.ag = new gzww("ACTIVITY_RECOGNITION_ACTIVITY_RECEIVED", 58, 0x99);
        gzww.ah = new gzww("EATER_DID_EAT_LOCATION", 59, 30);
        gzww.ai = new gzww("EATER_DID_EAT_VISIT_ARRIVAL", 60, 0x1F);
        gzww.aj = new gzww("EATER_DID_EAT_VISIT_DEPARTURE", 61, 0x20);
        gzww.ak = new gzww("EATER_DID_EAT_GEOFENCE_ENTRANCE", 62, 33);
        gzww.al = new gzww("EATER_DID_EAT_GEOFENCE_EXIT", 0x3F, 34);
        gzww.am = new gzww("EATER_DID_EAT_GEOFENCE_UNKNOWN", 0x40, 0x8E);
        gzww.an = new gzww("BURST_REQUEST_CREATED", 65, 35);
        gzww.ao = new gzww("BURST_DID_START", 66, 0x89);
        gzww.ap = new gzww("BURST_DID_PAUSE", 67, 0x8A);
        gzww.aq = new gzww("BURST_DID_RESUME", 68, 0x8B);
        gzww.ar = new gzww("BURST_REQUEST_CANCEL", 69, 36);
        gzww.as = new gzww("BURST_REQUEST_CANCEL_ALL", 70, 140);
        gzww.at = new gzww("BURST_REQUEST_COMPLETED_SUCCESS", 71, 37);
        gzww.au = new gzww("BURST_REQUEST_COMPLETED_FAILURE", 72, 38);
        gzww.av = new gzww("EXPEDITED_LOCATION_REQUEST_CREATE", 73, 39);
        gzww.aw = new gzww("EXPEDITED_LOCATION_REQUEST_COMPLETED_SUCCESS", 74, 40);
        gzww.ax = new gzww("EXPEDITED_LOCATION_REQUEST_COMPLETED_FAILURE", 75, 41);
        gzww.ay = new gzww("APPLICATION_DID_FINISH_LAUNCHING", 76, 42);
        gzww.az = new gzww("APPLICATION_DID_BECOME_ACTIVE", 77, 43);
        gzww.aA = new gzww("APPLICATION_DID_ENTER_BACKGROUND", 78, 44);
        gzww.aB = new gzww("APPLICATION_WILL_TERMINATE", 0x4F, 45);
        gzww.aC = new gzww("STORAGE_DID_ADD_ENTRY", 80, 46);
        gzww.aD = new gzww("STORAGE_DID_REMOVE_ENTRY", 81, 0x2F);
        gzww.aE = new gzww("STORAGE_CLEARED", 82, 0x30);
        gzww.aF = new gzww("ASSUME_RESPONSIBILITY_NO_CURRENT_SINGLE_REPORTER", 83, 49);
        gzww.aG = new gzww("ASSUME_RESPONSIBILITY_REASSERT_CURRENT_RESPONSIBILITY", 84, 50);
        gzww.aH = new gzww("ASSUME_RESPONSIBILITY_CURRENT_REPORTER_UNINSTALLED", 85, 51);
        gzww.aI = new gzww("ASSUME_RESPONSIBILITY_CURRENT_REPORTER_UNINTERESTED", 86, 52);
        gzww.aJ = new gzww("ASSUME_RESPONSIBILITY_NEWER_LIBRARY_VERSION", 87, 53);
        gzww.aK = new gzww("ASSUME_RESPONSIBILITY_BURSTING", 88, 54);
        gzww.aL = new gzww("ASSUME_RESPONSIBILITY_INACTIVE_FOR_24H", 89, 55);
        gzww.aM = new gzww("ASSUME_RESPONSIBILITY_BETTER_SENSORS", 90, 56);
        gzww.aN = new gzww("ASSUME_RESPONSIBILITY_FORCED", 91, 57);
        gzww.aO = new gzww("ASSUME_RESPONSIBILITY_MORE_POWER_HUNGRY", 92, 0xEC);
        gzww.aP = new gzww("ASSUME_RESPONSIBILITY_UNKNOWN", 93, 0xED);
        gzww.aQ = new gzww("DISAVOW_RESPONSIBILITY_NO_KEYCHAIN_ACCESS", 94, 58);
        gzww.aR = new gzww("DISAVOW_RESPONSIBILITY_NO_LOCATION_BACKGROUND_MODE", 0x5F, 59);
        gzww.aS = new gzww("DISAVOW_RESPONSIBILITY_LOCATION_SERVICES_UNAVAILABLE", 0x60, 60);
        gzww.aT = new gzww("DISAVOW_RESPONSIBILITY_TRIGGERS_NOT_SUPPORTED", 97, 61);
        gzww.aU = new gzww("DISAVOW_RESPONSIBILITY_TRIGGERS_FAILED_TO_START", 98, 62);
        gzww.aV = new gzww("DISAVOW_RESPONSIBILITY_NO_REPORTABLE_IDENTITIES", 99, 0x3F);
        gzww.aW = new gzww("DISAVOW_RESPONSIBILITY_WAITING_FOR_REPORTABLE_IDENTITIES", 100, 0x40);
        gzww.aX = new gzww("DISAVOW_RESPONSIBILITY_NOT_RESPONSIBLE_FOR_ANY_IDENTITIES", 101, 65);
        gzww.aY = new gzww("DISAVOW_RESPONSIBILITY_FAILURE_TO_DISAVOW_SPECIFIC_IDENTITY", 102, 66);
        gzww.aZ = new gzww("DISAVOW_RESPONSIBILITY_FAILURE_TO_UPDATE_REPORTING_STATE", 103, 67);
        gzww.ba = new gzww("DISAVOW_RESPONSIBILITY_UNKNOWN", 104, 0xEE);
        gzww.bb = new gzww("UNKEYED_ARCHIVING", 105, 68);
        gzww.bc = new gzww("UNKEYED_UNARCHIVING", 106, 69);
        gzww.bd = new gzww("ULR_INITIALIZATION_START", 107, 70);
        gzww.be = new gzww("ULR_INITIALIZATION_FINISH", 108, 71);
        gzww.bf = new gzww("INITIALIZATION", 109, 0x9A);
        gzww.bg = new gzww("LOCATION_REPORT_UPLOADED_TO_SERVER", 110, 72);
        gzww.bh = new gzww("LOCATION_REPORT_RESPONSE_SUCCESS", 0x6F, 73);
        gzww.bi = new gzww("LOCATION_REPORT_RESPONSE_FAILURE", 0x70, 74);
        gzww.bj = new gzww("LOCATION_REPORT_UPLOAD_RETRY", 0x71, 75);
        gzww.bk = new gzww("RPC_REPORT_LOCATIONS_REQUEST", 0x72, 0x9B);
        gzww.bl = new gzww("RPC_REPORT_LOCATIONS_SUCCESS", 0x73, 0x9C);
        gzww.bm = new gzww("RPC_REPORT_LOCATIONS_FAILURE", 0x74, 0x9D);
        gzww.bn = new gzww("RPC_REPORT_LOCATIONS_RETRY", 0x75, 0x9E);
        gzww.bo = new gzww("RPC_GET_SETTINGS_REQUEST", 0x76, 0x9F);
        gzww.bp = new gzww("RPC_GET_SETTINGS_SUCCESS", 0x77, 0xA0);
        gzww.bq = new gzww("RPC_GET_SETTINGS_FAILURE", 120, 0xA1);
        gzww.br = new gzww("RPC_GET_SETTINGS_RETRY", 0x79, 0xA2);
        gzww.bs = new gzww("RPC_SET_SETTINGS_REQUEST", 0x7A, 0xA3);
        gzww.bt = new gzww("RPC_SET_SETTINGS_SUCCESS", 0x7B, 0xA4);
        gzww.bu = new gzww("RPC_SET_SETTINGS_FAILURE", 0x7C, 0xA5);
        gzww.bv = new gzww("RPC_SET_SETTINGS_RETRY", 0x7D, 0xA6);
        gzww.bw = new gzww("RPC_GET_USER_SETTINGS_REQUEST", 0x7E, 0xA7);
        gzww.bx = new gzww("RPC_GET_USER_SETTINGS_SUCCESS", 0x7F, 0xA8);
        gzww.by = new gzww("RPC_GET_USER_SETTINGS_FAILURE", 0x80, 0xA9);
        gzww.bz = new gzww("RPC_GET_USER_SETTINGS_RETRY", 0x81, 170);
        gzww.bA = new gzww("RPC_SET_REMOTE_DEVICE_SETTINGS_REQUEST", 130, 0xAB);
        gzww.bB = new gzww("RPC_SET_REMOTE_DEVICE_SETTINGS_SUCCESS", 0x83, 0xAC);
        gzww.bC = new gzww("RPC_SET_REMOTE_DEVICE_SETTINGS_FAILURE", 0x84, 0xAD);
        gzww.bD = new gzww("RPC_SET_REMOTE_DEVICE_SETTINGS_RETRY", 0x85, 0xAE);
        gzww.bE = new gzww("RPC_DELETE_LOCATIONS_REQUEST", 0x86, 0xAF);
        gzww.bF = new gzww("RPC_DELETE_LOCATIONS_SUCCESS", 0x87, 0xB0);
        gzww.bG = new gzww("RPC_DELETE_LOCATIONS_FAILURE", 0x88, 0xB1);
        gzww.bH = new gzww("RPC_DELETE_LOCATIONS_RETRY", 0x89, 0xB2);
        gzww.bI = new gzww("SPACE_LOCATIONS_AT_MINIMUM_TIME_INTERVAL", 0x8A, 76);
        gzww.bJ = new gzww("MERGE_IDENTICAL_LOCATIONS", 0x8B, 77);
        gzww.bK = new gzww("MERGE_INTERMEDIATE_STATIONARY_LOCATIONS", 140, 78);
        gzww.bL = new gzww("REFINE_LOCATIONS_BY_TIME", 0x8D, 0x4F);
        gzww.bM = new gzww("LOCATION_AUTHORIZATION_STATUS_DID_UPDATE", 0x8E, 80);
        gzww.bN = new gzww("KEYCHAIN_DEVICE_QUERY", 0x8F, 81);
        gzww.bO = new gzww("KEYCHAIN_DEVICE_ADD_SUCCESS", 0x90, 82);
        gzww.bP = new gzww("KEYCHAIN_DEVICE_ADD_FAILURE", 0x91, 83);
        gzww.bQ = new gzww("KEYCHAIN_DEVICE_UPDATE_SUCCESS", 0x92, 84);
        gzww.bR = new gzww("KEYCHAIN_DEVICE_UPDATE_FAILURE", 0x93, 85);
        gzww.bS = new gzww("KEYCHAIN_DEVICE_DELETE_SUCCESS", 0x94, 86);
        gzww.bT = new gzww("KEYCHAIN_DEVICE_DELETE_FAILURE", 0x95, 87);
        gzww.bU = new gzww("KEYCHAIN_IDENTITY_QUERY", 150, 88);
        gzww.bV = new gzww("KEYCHAIN_IDENTITY_ADD_SUCCESS", 0x97, 89);
        gzww.bW = new gzww("KEYCHAIN_IDENTITY_ADD_FAILURE", 0x98, 90);
        gzww.bX = new gzww("KEYCHAIN_IDENTITY_UPDATE_SUCCESS", 0x99, 91);
        gzww.bY = new gzww("KEYCHAIN_IDENTITY_UPDATE_FAILURE", 0x9A, 92);
        gzww.bZ = new gzww("KEYCHAIN_IDENTITY_DELETE_SUCCESS", 0x9B, 93);
        gzww.ca = new gzww("KEYCHAIN_IDENTITY_DELETE_FAILURE", 0x9C, 94);
        gzww.cb = new gzww("KEYCHAIN_INTEREST_QUERY", 0x9D, 0x5F);
        gzww.cc = new gzww("KEYCHAIN_INTEREST_ADD_SUCCESS", 0x9E, 0x60);
        gzww.cd = new gzww("KEYCHAIN_INTEREST_ADD_FAILURE", 0x9F, 97);
        gzww.ce = new gzww("KEYCHAIN_INTEREST_UPDATE_SUCCESS", 0xA0, 98);
        gzww.cf = new gzww("KEYCHAIN_INTEREST_UPDATE_FAILURE", 0xA1, 99);
        gzww.cg = new gzww("KEYCHAIN_INTEREST_DELETE_SUCCESS", 0xA2, 100);
        gzww.ch = new gzww("KEYCHAIN_INTEREST_DELETE_FAILURE", 0xA3, 101);
        gzww.ci = new gzww("KEYCHAIN_KILL_REQUEST_QUERY", 0xA4, 102);
        gzww.cj = new gzww("KEYCHAIN_KILL_REQUEST_ADD_SUCCESS", 0xA5, 103);
        gzww.ck = new gzww("KEYCHAIN_KILL_REQUEST_ADD_FAILURE", 0xA6, 104);
        gzww.cl = new gzww("KEYCHAIN_KILL_REQUEST_UPDATE_SUCCESS", 0xA7, 105);
        gzww.cm = new gzww("KEYCHAIN_KILL_REQUEST_UPDATE_FAILURE", 0xA8, 106);
        gzww.cn = new gzww("KEYCHAIN_KILL_REQUEST_DELETE_SUCCESS", 0xA9, 107);
        gzww.co = new gzww("KEYCHAIN_KILL_REQUEST_DELETE_FAILURE", 170, 108);
        gzww.cp = new gzww("KEYCHAIN_RESPONSIBILITY_QUERY", 0xAB, 109);
        gzww.cq = new gzww("KEYCHAIN_RESPONSIBILITY_ADD_SUCCESS", 0xAC, 110);
        gzww.cr = new gzww("KEYCHAIN_RESPONSIBILITY_ADD_FAILURE", 0xAD, 0x6F);
        gzww.cs = new gzww("KEYCHAIN_RESPONSIBILITY_UPDATE_SUCCESS", 0xAE, 0x70);
        gzww.ct = new gzww("KEYCHAIN_RESPONSIBILITY_UPDATE_FAILURE", 0xAF, 0x71);
        gzww.cu = new gzww("KEYCHAIN_RESPONSIBILITY_DELETE_SUCCESS", 0xB0, 0x72);
        gzww.cv = new gzww("KEYCHAIN_RESPONSIBILITY_DELETE_FAILURE", 0xB1, 0x73);
        gzww.cw = new gzww("KEYCHAIN_RESTRICTION_QUERY", 0xB2, 0x74);
        gzww.cx = new gzww("KEYCHAIN_RESTRICTION_ADD_SUCCESS", 0xB3, 0x75);
        gzww.cy = new gzww("KEYCHAIN_RESTRICTION_ADD_FAILURE", 180, 0x76);
        gzww.cz = new gzww("KEYCHAIN_RESTRICTION_UPDATE_SUCCESS", 0xB5, 0x77);
        gzww.cA = new gzww("KEYCHAIN_RESTRICTION_UPDATE_FAILURE", 0xB6, 120);
        gzww.cB = new gzww("KEYCHAIN_RESTRICTION_DELETE_SUCCESS", 0xB7, 0x79);
        gzww.cC = new gzww("KEYCHAIN_RESTRICTION_DELETE_FAILURE", 0xB8, 0x7A);
        gzww.cD = new gzww("ENABLE_LH_SUCCESS", 0xB9, 130);
        gzww.cE = new gzww("ENABLE_LH_FAILURE", 0xBA, 0x83);
        gzww.cF = new gzww("ENABLE_LR_SUCCESS", 0xBB, 0x84);
        gzww.cG = new gzww("ENABLE_LR_FAILURE", 0xBC, 0x86);
        gzww.cH = new gzww("DISABLE_LH_SUCCESS", 0xBD, 0xC4);
        gzww.cI = new gzww("DISABLE_LH_FAILURE", 190, 0xC5);
        gzww.cJ = new gzww("DISABLE_LR_SUCCESS", 0xBF, 0xC6);
        gzww.cK = new gzww("DISABLE_LR_FAILURE", 0xC0, 0xC7);
        gzww.cL = new gzww("ONBOARDING_FLOW_ENABLE_LH_LR_SUCCESS", 0xC1, 0x87);
        gzww.cM = new gzww("ONBOARDING_FLOW_ENABLE_LH_LR_FAILURE", 0xC2, 0x88);
        gzww.cN = new gzww("TIMING_UNKNOWN_PROCESS", 0xC3, 200);
        gzww.cO = new gzww("TIMING_START_TRIGGERS", 0xC4, 201);
        gzww.cP = new gzww("TIMING_START_LOCATION_COLLECTION", 0xC5, 202);
        gzww.cQ = new gzww("DEEP_STILL_CHANGED", 0xC6, 203);
        gzww.cR = new gzww("BAROMETER_READING", 0xC7, 204);
        gzww.cS = new gzww("API_CALL_UNKNOWN", 200, 205);
        gzww.cT = new gzww("API_CALL_GET_REPORTING_STATE_SAFE", 201, 206);
        gzww.cU = new gzww("API_CALL_TRY_OPT_IN", 202, 0xCF);
        gzww.cV = new gzww("API_CALL_TRY_OPT_IN_REQUEST", 203, 0xD0);
        gzww.cW = new gzww("API_CALL_REQUEST_UPLOAD", 204, 209);
        gzww.cX = new gzww("API_CALL_CANCEL_UPLOAD", 205, 210);
        gzww.cY = new gzww("API_CALL_REPORT_PLACE", 206, 0xD3);
        gzww.cZ = new gzww("API_CALL_SEND_DATA", 0xCF, 0xD4);
        gzww.da = new gzww("API_CALL_TOGGLE_PRIVATE_MODE_ON", 0xD0, 0xEF);
        gzww.db = new gzww("API_CALL_TOGGLE_PRIVATE_MODE_OFF", 209, 0xF0);
        gzww.dc = new gzww("GEO_SUPPORTED", 210, 0xD6);
        gzww.dd = new gzww("GEO_UNSUPPORTED", 0xD3, 0xD7);
        gzww.de = new gzww("LOCATION_ENABLED_FOR_GOOGLE_APPS", 0xD4, 0xD8);
        gzww.df = new gzww("LOCATION_DISABLED_FOR_GOOGLE_APPS", 0xD5, 0xD9);
        gzww.dg = new gzww("WIFI_ALWAYS_SCAN_MODE_ENABLED", 0xD6, 0xDA);
        gzww.dh = new gzww("WIFI_ALWAYS_SCAN_MODE_DISABLED", 0xD7, 0xDB);
        gzww.di = new gzww("BLE_ALWAYS_SCAN_MODE_ENABLED", 0xD8, 220);
        gzww.dj = new gzww("BLE_ALWAYS_SCAN_MODE_DISABLED", 0xD9, 0xDD);
        gzww.dk = new gzww("BATTERY_SAVER_MODE_ENABLED", 0xDA, 0xDE);
        gzww.dl = new gzww("BATTERY_SAVER_MODE_DISABLED", 0xDB, 0xDF);
        gzww.dm = new gzww("BATTERY_SAVER_MODE_THRESHOLD_CHANGED", 220, 0xE0);
        gzww.dn = new gzww("WIFI_ENABLED", 0xDD, 0xE1);
        gzww.do = new gzww("WIFI_DISABLED", 0xDE, 0xE2);
        gzww.dp = new gzww("LOCATION_MODE_UNKNOWN", 0xDF, 0xE3);
        gzww.dq = new gzww("LOCATION_MODE_OFF", 0xE0, 0xE4);
        gzww.dr = new gzww("LOCATION_MODE_BATTERY_SAVING", 0xE1, 0xE5);
        gzww.ds = new gzww("LOCATION_MODE_SENSORS_ONLY", 0xE2, 230);
        gzww.dt = new gzww("LOCATION_MODE_HIGH_ACCURACY", 0xE3, 0xE7);
        gzww.du = new gzww("AIRPLANE_MODE_ON", 0xE4, 0xE8);
        gzww.dv = new gzww("AIRPLANE_MODE_OFF", 0xE5, 0xE9);
        gzww.dw = new gzww("DOZE_MODE_ON", 230, 0xEA);
        gzww.dx = new gzww("DOZE_MODE_OFF", 0xE7, 0xEB);
        gzww.dy = new gzww("DAILY_REPORT", 0xE8, 0xF1);
        gzww.dz = new gzww("CSL_UPLOAD", 0xE9, 0xF2);
        gzww.dB = gzww.b();
    }

    private gzww(String s, int v, int v1) {
        super(s, v);
        this.dA = v1;
    }

    @Override  // hfub
    public final int a() {
        return this.dA;
    }

    private static gzww[] b() {
        return new gzww[]{gzww.a, gzww.b, gzww.c, gzww.d, gzww.e, gzww.f, gzww.g, gzww.h, gzww.i, gzww.j, gzww.k, gzww.l, gzww.m, gzww.n, gzww.o, gzww.p, gzww.q, gzww.r, gzww.s, gzww.t, gzww.u, gzww.v, gzww.w, gzww.x, gzww.y, gzww.z, gzww.A, gzww.B, gzww.C, gzww.D, gzww.E, gzww.F, gzww.G, gzww.H, gzww.I, gzww.J, gzww.K, gzww.L, gzww.M, gzww.N, gzww.O, gzww.P, gzww.Q, gzww.R, gzww.S, gzww.T, gzww.U, gzww.V, gzww.W, gzww.X, gzww.Y, gzww.Z, gzww.aa, gzww.ab, gzww.ac, gzww.ad, gzww.ae, gzww.af, gzww.ag, gzww.ah, gzww.ai, gzww.aj, gzww.ak, gzww.al, gzww.am, gzww.an, gzww.ao, gzww.ap, gzww.aq, gzww.ar, gzww.as, gzww.at, gzww.au, gzww.av, gzww.aw, gzww.ax, gzww.ay, gzww.az, gzww.aA, gzww.aB, gzww.aC, gzww.aD, gzww.aE, gzww.aF, gzww.aG, gzww.aH, gzww.aI, gzww.aJ, gzww.aK, gzww.aL, gzww.aM, gzww.aN, gzww.aO, gzww.aP, gzww.aQ, gzww.aR, gzww.aS, gzww.aT, gzww.aU, gzww.aV, gzww.aW, gzww.aX, gzww.aY, gzww.aZ, gzww.ba, gzww.bb, gzww.bc, gzww.bd, gzww.be, gzww.bf, gzww.bg, gzww.bh, gzww.bi, gzww.bj, gzww.bk, gzww.bl, gzww.bm, gzww.bn, gzww.bo, gzww.bp, gzww.bq, gzww.br, gzww.bs, gzww.bt, gzww.bu, gzww.bv, gzww.bw, gzww.bx, gzww.by, gzww.bz, gzww.bA, gzww.bB, gzww.bC, gzww.bD, gzww.bE, gzww.bF, gzww.bG, gzww.bH, gzww.bI, gzww.bJ, gzww.bK, gzww.bL, gzww.bM, gzww.bN, gzww.bO, gzww.bP, gzww.bQ, gzww.bR, gzww.bS, gzww.bT, gzww.bU, gzww.bV, gzww.bW, gzww.bX, gzww.bY, gzww.bZ, gzww.ca, gzww.cb, gzww.cc, gzww.cd, gzww.ce, gzww.cf, gzww.cg, gzww.ch, gzww.ci, gzww.cj, gzww.ck, gzww.cl, gzww.cm, gzww.cn, gzww.co, gzww.cp, gzww.cq, gzww.cr, gzww.cs, gzww.ct, gzww.cu, gzww.cv, gzww.cw, gzww.cx, gzww.cy, gzww.cz, gzww.cA, gzww.cB, gzww.cC, gzww.cD, gzww.cE, gzww.cF, gzww.cG, gzww.cH, gzww.cI, gzww.cJ, gzww.cK, gzww.cL, gzww.cM, gzww.cN, gzww.cO, gzww.cP, gzww.cQ, gzww.cR, gzww.cS, gzww.cT, gzww.cU, gzww.cV, gzww.cW, gzww.cX, gzww.cY, gzww.cZ, gzww.da, gzww.db, gzww.dc, gzww.dd, gzww.de, gzww.df, gzww.dg, gzww.dh, gzww.di, gzww.dj, gzww.dk, gzww.dl, gzww.dm, gzww.dn, gzww.do, gzww.dp, gzww.dq, gzww.dr, gzww.ds, gzww.dt, gzww.du, gzww.dv, gzww.dw, gzww.dx, gzww.dy, gzww.dz};
    }

    @Override
    public final String toString() {
        return Integer.toString(this.dA);
    }

    public static gzww[] values() {
        return (gzww[])gzww.dB.clone();
    }
}

