public enum gzxv implements hfub {
    UNKNOWN_ENROLLMENT_RESULT(0),
    ENROLLMENT_REQUESTED(1),
    ENROLLMENT_RESULT_SUCCESS(2),
    ENROLLMENT_FAILURE_UNKNOWN(3),
    ENROLLMENT_FAILURE_CONNECTION_UNKNOWN(4),
    ENROLLMENT_FAILURE_KEYGUARD(5),
    ENROLLMENT_FAILURE_AUTHENTICATION(6),
    ENROLLMENT_FAILURE_VERIFICATION(7),
    ENROLLMENT_FAILURE_CONNECTION_TIMEOUT(8),
    ENROLLMENT_FAILURE_CONNECTION_REFUSED(9),
    ENROLLMENT_FAILURE_CONNECTION_DISCONNECTED(10),
    ENROLLMENT_FAILURE_RPC_TIMEOUT(11),
    ENROLLMENT_FAILURE_CONNECTION_UNAVAILABLE(12),
    ENROLLMENT_FAILURE_RPC_UNAVAILABLE(13),
    ENROLLMENT_FAILURE_TIME_NOT_SYNCED(14),
    ENROLLMENT_FAILURE_ATTESTATION_MISSING_PROPERTIES(15),
    ENROLLMENT_FAILURE_CHALLENGE_MISMATCH(16),
    ENROLLMENT_FAILURE_UNABLE_PARSE_ATTESTATION(17),
    ENROLLMENT_FAILURE_NOT_VERIFIED_BOOT(18),
    ENROLLMENT_FAILURE_INVALID_PATCH_LEVEL(19),
    ENROLLMENT_FAILURE_INVALID_PATCH_DATE_FORMAT(20),
    ENROLLMENT_FAILURE_CERTIFICATE_PATH_NOT_VALID(21),
    ENROLLMENT_FAILURE_MISSING_REENROLLMENT_DATA(22),
    ENROLLMENT_FAILURE_UNHANDLED(23),
    ENROLLMENT_FAILURE_INVALID_REQUEST(24),
    ENROLLMENT_FAILURE_PHONE_RELOCK_ON_TRUST_LOST(25),
    ENROLLMENT_FAILURE_RANGING_METHOD_UWB_UNAVAILABLE(26),
    ENROLLMENT_FAILURE_VERIFICATION_LIBRARY_CHALLENGE_MISMATCH(27),
    ENROLLMENT_FAILURE_VERIFICATION_LIBRARY_PATH_VALIDATION(28),
    ENROLLMENT_FAILURE_VERIFICATION_LIBRARY_CHAIN_PARSING(29),
    ENROLLMENT_FAILURE_VERIFICATION_LIBRARY_EXTENSION_PARSING(30),
    ENROLLMENT_FAILURE_VERIFICATION_LIBRARY_OTHER(0x1F),
    ENROLLMENT_FAILURE_REENROLLMENT_TIMEDOUT(0x20),
    UNRECOGNIZED(-1);

    private final int J;

    private gzxv(int v1) {
        this.J = v1;
    }

    @Override  // hfub
    public final int a() {
        if(this != gzxv.H) {
            return this.J;
        }
        throw new IllegalArgumentException("Can\'t get the number of an unknown enum value.");
    }

    @Override
    public final String toString() {
        return Integer.toString(this.J);
    }
}

