public final class hldg {
    public static final String A;
    public static final String B;
    public static final String C;
    public static final String D;
    public static final String E;
    public static final String F;
    public static final String G;
    public static final String H;
    public static final String I;
    public static final String J;
    public static final String K;
    public static final String L;
    public static final String M;
    public static final String N;
    public static final String O;
    public static final String P;
    public static final String Q;
    public static final String R;
    public static final String S;
    public static final String T;
    public static final String U;
    public static final String V;
    public static final String W;
    public static final String X;
    public static final String Y;
    public static final String Z;
    public static final String a;
    public static final String aa;
    public static final String ab;
    public static final String ac;
    public static final String ad;
    public static final String ae;
    public static final String af;
    public static final String ag;
    public static final String ah;
    public static final String ai;
    public static final String aj;
    public static final String ak;
    public static final String al;
    public static final String am;
    public static final String an;
    public static final String ao;
    public static final String ap;
    public static final String aq;
    public static final String ar;
    public static final String b;
    public static final String c;
    public static final String d;
    public static final String e;
    public static final String f;
    public static final String g;
    public static final String h;
    public static final String i;
    public static final String j;
    public static final String k;
    public static final String l;
    public static final String m;
    public static final String n;
    public static final String o;
    public static final String p;
    public static final String q;
    public static final String r;
    public static final String s;
    public static final String t;
    public static final String u;
    public static final String v;
    public static final String w;
    public static final String x;
    public static final String y;
    public static final String z;

    static {
        String s = hldf.a(hldd.h, "merge_activity_segments");
        hldg.a = s;
        String s1 = hldf.a(hldd.d, "merge_active_minutes");
        hldg.b = s1;
        String s2 = hldf.a(hldd.E, "merge_heart_minutes");
        hldg.c = s2;
        String s3 = hldf.a(hldd.aS, "merge_step_deltas");
        hldg.d = s3;
        String s4 = hldf.a(hldd.aQ, "merged");
        hldg.e = s4;
        String s5 = hldf.a(hldd.aB, "merge_location_samples");
        hldg.f = s5;
        String s6 = hldf.a(hldd.G, "merge_heart_rate_bpm");
        hldg.g = s6;
        String s7 = hldf.a(hldd.aL, "merge_respiratory_rate");
        hldg.h = s7;
        String s8 = hldf.a(hldd.aW, "merge_weight");
        hldg.i = s8;
        String s9 = hldf.a(hldd.I, "merge_height");
        hldg.j = s9;
        String s10 = hldf.a(hldd.t, "merge_calories_expended");
        hldg.k = s10;
        String s11 = hldf.a(hldd.r, "merged");
        hldg.l = s11;
        String s12 = hldf.a(hldd.C, "merge_distance_delta");
        hldg.m = s12;
        String s13 = hldf.a(hldd.aJ, "merge_power_sample");
        hldg.n = s13;
        String s14 = hldf.a(hldd.aO, "merge_speed");
        hldg.o = s14;
        String s15 = hldf.a(hldd.f, "merged");
        hldg.p = s15;
        String s16 = hldf.a(hldd.j, "merged");
        hldg.q = s16;
        String s17 = hldf.a(hldd.l, "merged");
        hldg.r = s17;
        String s18 = hldf.a(hldd.aH, "merged");
        hldg.s = s18;
        String s19 = hldf.a(hldd.p, "merged");
        hldg.t = s19;
        String s20 = hldf.a(hldd.v, "merged");
        hldg.u = s20;
        String s21 = hldf.a(hldd.w, "merged");
        hldg.v = s21;
        String s22 = hldf.a(hldd.aD, "merged");
        hldg.w = s22;
        String s23 = hldf.a(hldd.aG, "merged");
        hldg.x = s23;
        String s24 = hldf.a(hldd.aV, "merged");
        hldg.y = s24;
        String s25 = hldf.a(hldd.ap, "merged");
        hldg.z = s25;
        String s26 = hldf.a(hldd.as, "merged");
        hldg.A = s26;
        String s27 = hldf.a(hldd.aN, "merged");
        hldg.B = s27;
        String s28 = hldf.a(hldd.aE, "merged");
        hldg.C = s28;
        String s29 = hldf.a(hldd.K, "merged");
        hldg.D = s29;
        String s30 = hldf.a(hldd.n, "merged");
        hldg.E = s30;
        String s31 = hldf.a(hldd.x, "merged");
        hldg.F = s31;
        String s32 = hldf.a(hldd.A, "merged");
        hldg.G = s32;
        String s33 = hldf.a(hldd.aU, "merged");
        hldg.H = s33;
        String s34 = hldf.a(hldd.ag, "merged");
        hldg.I = s34;
        String s35 = hldf.a(hldd.ao, "merged");
        hldg.J = s35;
        String s36 = hldf.a(hldd.ad, "merged");
        hldg.K = s36;
        String s37 = hldf.a(hldd.Q, "merged");
        hldg.L = s37;
        String s38 = hldf.a(hldd.M, "merged");
        hldg.M = s38;
        String s39 = hldf.a(hldd.an, "merged");
        hldg.N = s39;
        String s40 = hldf.a(hldd.R, "merged");
        hldg.O = s40;
        String s41 = hldf.a(hldd.ah, "merged");
        hldg.P = s41;
        String s42 = hldf.a(hldd.af, "merged");
        hldg.Q = s42;
        String s43 = hldf.a(hldd.ai, "merged");
        hldg.R = s43;
        String s44 = hldf.a(hldd.X, "merged");
        hldg.S = s44;
        String s45 = hldf.a(hldd.ak, "merged");
        hldg.T = s45;
        String s46 = hldf.a(hldd.ab, "merged");
        hldg.U = s46;
        String s47 = hldf.a(hldd.P, "merged");
        hldg.V = s47;
        String s48 = hldf.a(hldd.O, "merged");
        hldg.W = s48;
        String s49 = hldf.a(hldd.ax, "merged");
        hldg.X = s49;
        String s50 = hldf.a(hldd.Z, "merged");
        hldg.Y = s50;
        String s51 = hldf.a(hldd.az, "merged");
        hldg.Z = s51;
        String s52 = hldf.a(hldd.ac, "merged");
        hldg.aa = s52;
        String s53 = hldf.a(hldd.N, "merged");
        hldg.ab = s53;
        String s54 = hldf.a(hldd.aq, "merged");
        hldg.ac = s54;
        String s55 = hldf.a(hldd.am, "merged");
        hldg.ad = s55;
        String s56 = hldf.a(hldd.V, "merged");
        hldg.ae = s56;
        String s57 = hldf.a(hldd.at, "merged");
        hldg.af = s57;
        String s58 = hldf.a(hldd.au, "merged");
        hldg.ag = s58;
        String s59 = hldf.a(hldd.ar, "merged");
        hldg.ah = s59;
        String s60 = hldf.a(hldd.aw, "merged");
        hldg.ai = s60;
        String s61 = hldf.a(hldd.ay, "merged");
        hldg.aj = s61;
        String s62 = hldf.a(hldd.aa, "merged");
        hldg.ak = s62;
        String s63 = hldf.a(hldd.av, "merged");
        hldg.al = s63;
        String s64 = hldf.a(hldd.W, "merged");
        hldg.am = s64;
        String s65 = hldf.a(hldd.T, "merged");
        hldg.an = s65;
        String s66 = hldf.a(hldd.S, "merged");
        hldg.ao = s66;
        String s67 = hldf.a(hldd.al, "merged");
        hldg.ap = s67;
        String s68 = hldf.a(hldd.U, "merged");
        hldg.aq = s68;
        String s69 = hldf.a(hldd.ae, "merged");
        hldg.ar = s69;
        ggfp.O(s38, s53, s15, s, s48, s11, new String[]{s16, s17, s30, s19, s10, s20, s21, s47, s37, s40, s31, s32, s66, s65, s68, s56, s64, s12, s44, s50, s62, s2, s6, s46, s52, s9, s29, s36, s69, s5, s42, s22, s34, s41, s43, s1, s28, s23, s18, s13, s45, s7, s67, s55, s39, s35, s25, s54, s59, s26, s27, s57, s58, s14, s4, s3, s63, s60, s49, s33, s24, s61, s51, s8});
    }
}

