public final class hnzn implements gphn {
    public static final fokg a;
    public static final gphl b;
    public static final gphl c;
    public static final gphl d;
    public static final gphl e;
    public static final gphl f;
    public static final gphl g;
    public static final gphl h;
    public static final gphl i;
    public static final gphl j;
    public static final gphl k;
    public static final gphl l;
    public static final gphl m;
    public static final hnzn n;
    public final ggfp o;
    private static final fokg p;
    private static final fokg q;
    private final ggeo r;

    static {
        hnzn.a = new fokg("google.internal.communications.instantmessaging.v1.Messaging.");
        hnzn.p = new fokg("google.internal.communications.instantmessaging.v1.Messaging/");
        hnzn.b = new hnze();
        hnzn.c = new hnzf();
        hnzn.d = new hnzg();
        hnzn.e = new hnzh();
        hnzn.f = new hnzi();
        hnzn.g = new hnzj();
        hnzn.h = new hnzk();
        hnzn.i = new hnzl();
        hnzn.j = new hnzm();
        hnzn.k = new hnzb();
        hnzn.l = new hnzc();
        hnzn.m = new hnzd();
        hnzn.n = new hnzn();
        hnzn.q = new fokg("instantmessaging-pa.googleapis.com");
    }

    private hnzn() {
        ggdy ggdy0 = new ggdy();
        ggdy0.i("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-pa.mtls.googleapis.com");
        ggdy0.i("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-west-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-west-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-west-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-west-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-west-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-west-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("zero-instantmessaging-pa.googleapis.com");
        ggdy0.i("zero-instantmessaging-pa.mtls.googleapis.com");
        ggdy0.i("instantmessaging-pa.googleapis.com");
        ggdy0.h();
        this.o = new ggfn().h();
        ggfp.O(hnzn.b, hnzn.c, hnzn.d, hnzn.e, hnzn.f, hnzn.g, new gphl[]{hnzn.h, hnzn.i, hnzn.j, hnzn.k, hnzn.l, hnzn.m});
        ggek ggek0 = new ggek();
        ggek0.i("SendMessage", hnzn.b);
        ggek0.i("SendMessageExpress", hnzn.c);
        ggek0.i("Bind", hnzn.d);
        ggek0.i("ReceiveMessages", hnzn.e);
        ggek0.i("ReceiveMessagesExpress", hnzn.f);
        ggek0.i("PullMessages", hnzn.g);
        ggek0.i("AckMessages", hnzn.h);
        ggek0.i("BatchAckMessages", hnzn.i);
        ggek0.i("RevokeMessagesById", hnzn.j);
        ggek0.i("RevokeMessagesBySender", hnzn.k);
        ggek0.i("PrewarmReceiver", hnzn.l);
        ggek0.i("Echo", hnzn.m);
        this.r = ggek0.b();
        new ggek().b();
    }

    @Override  // gphn
    public final fokg a() {
        return hnzn.q;
    }

    @Override  // gphn
    public final gphl b(String s) {
        String s1 = hnzn.p.a;
        if(s.startsWith(s1)) {
            String s2 = s.substring(s1.length());
            return this.r.containsKey(s2) ? ((gphl)this.r.get(s2)) : null;
        }
        return null;
    }
}

