public final class hoat implements gphn {
    public static final gphl A;
    public static final gphl B;
    public static final gphl C;
    public static final gphl D;
    public static final gphl E;
    public static final gphl F;
    public static final hoat G;
    public final ggfp H;
    private static final fokg I;
    private static final fokg J;
    private final ggeo K;
    public static final fokg a;
    public static final gphl b;
    public static final gphl c;
    public static final gphl d;
    public static final gphl e;
    public static final gphl f;
    public static final gphl g;
    public static final gphl h;
    public static final gphl i;
    public static final gphl j;
    public static final gphl k;
    public static final gphl l;
    public static final gphl m;
    public static final gphl n;
    public static final gphl o;
    public static final gphl p;
    public static final gphl q;
    public static final gphl r;
    public static final gphl s;
    public static final gphl t;
    public static final gphl u;
    public static final gphl v;
    public static final gphl w;
    public static final gphl x;
    public static final gphl y;
    public static final gphl z;

    static {
        hoat.a = new fokg("google.internal.communications.instantmessaging.v1.Registration.");
        hoat.I = new fokg("google.internal.communications.instantmessaging.v1.Registration/");
        hoat.b = new hnzy();
        hoat.c = new hoaj();
        hoat.d = new hoam();
        hoat.e = new hoan();
        hoat.f = new hoao();
        hoat.g = new hoap();
        hoat.h = new hoaq();
        hoat.i = new hoar();
        hoat.j = new hoas();
        hoat.k = new hnzo();
        hoat.l = new hnzp();
        hoat.m = new hnzq();
        hoat.n = new hnzr();
        hoat.o = new hnzs();
        hoat.p = new hnzt();
        hoat.q = new hnzu();
        hoat.r = new hnzv();
        hoat.s = new hnzw();
        hoat.t = new hnzx();
        hoat.u = new hnzz();
        hoat.v = new hoaa();
        hoat.w = new hoab();
        hoat.x = new hoac();
        hoat.y = new hoad();
        hoat.z = new hoae();
        hoat.A = new hoaf();
        hoat.B = new hoag();
        hoat.C = new hoah();
        hoat.D = new hoai();
        hoat.E = new hoak();
        hoat.F = new hoal();
        hoat.G = new hoat();
        hoat.J = new fokg("instantmessaging-pa.googleapis.com");
    }

    private hoat() {
        ggdy ggdy0 = new ggdy();
        ggdy0.i("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-pa.mtls.googleapis.com");
        ggdy0.i("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-west-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-west-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-west-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-west-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-west-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-west-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("zero-instantmessaging-pa.googleapis.com");
        ggdy0.i("zero-instantmessaging-pa.mtls.googleapis.com");
        ggdy0.i("instantmessaging-pa.googleapis.com");
        ggdy0.h();
        this.H = new ggfn().h();
        ggfp.O(hoat.b, hoat.c, hoat.d, hoat.e, hoat.f, hoat.g, new gphl[]{hoat.h, hoat.i, hoat.j, hoat.k, hoat.l, hoat.m, hoat.n, hoat.o, hoat.p, hoat.q, hoat.r, hoat.s, hoat.t, hoat.u, hoat.v, hoat.w, hoat.x, hoat.y, hoat.z, hoat.A, hoat.B, hoat.C, hoat.D, hoat.E, hoat.F});
        ggek ggek0 = new ggek();
        ggek0.i("Register", hoat.b);
        ggek0.i("RegisterSilent", hoat.c);
        ggek0.i("PeriodicRegisterSilent", hoat.d);
        ggek0.i("RegisterAnonymous", hoat.e);
        ggek0.i("RegisterByAgent", hoat.f);
        ggek0.i("RegisterRefresh", hoat.g);
        ggek0.i("Verify", hoat.h);
        ggek0.i("Unregister", hoat.i);
        ggek0.i("DeleteAccount", hoat.j);
        ggek0.i("LookupRegistered", hoat.k);
        ggek0.i("LookupRegisteredSheddable", hoat.l);
        ggek0.i("SetCapabilities", hoat.m);
        ggek0.i("GetPreKey", hoat.n);
        ggek0.i("GetPreKeyBatch", hoat.o);
        ggek0.i("SetPreKeys", hoat.p);
        ggek0.i("UpgradeAccount", hoat.q);
        ggek0.i("DowngradeAccount", hoat.r);
        ggek0.i("SignInGaia", hoat.s);
        ggek0.i("SignInGaiaSilent", hoat.t);
        ggek0.i("VerifyGaia", hoat.u);
        ggek0.i("GetAccountInfo", hoat.v);
        ggek0.i("AddPhoneReachability", hoat.w);
        ggek0.i("VerifyPhoneReachability", hoat.x);
        ggek0.i("RegisterGaiaSilent", hoat.y);
        ggek0.i("ReplacePhoneReachability", hoat.z);
        ggek0.i("UnregisterGoogleRCS", hoat.A);
        ggek0.i("GetGaiaDeviceInfo", hoat.B);
        ggek0.i("LinkIdentity", hoat.C);
        ggek0.i("ListIdentities", hoat.D);
        ggek0.i("SignInSecondary", hoat.E);
        ggek0.i("UnlinkIdentity", hoat.F);
        this.K = ggek0.b();
        new ggek().b();
    }

    @Override  // gphn
    public final fokg a() {
        return hoat.J;
    }

    @Override  // gphn
    public final gphl b(String s) {
        String s1 = hoat.I.a;
        if(s.startsWith(s1)) {
            String s2 = s.substring(s1.length());
            return this.K.containsKey(s2) ? ((gphl)this.K.get(s2)) : null;
        }
        return null;
    }
}

