public final class hobf implements gphn {
    public static final fokg a;
    public static final gphl b;
    public static final gphl c;
    public static final gphl d;
    public static final gphl e;
    public static final gphl f;
    public static final gphl g;
    public static final gphl h;
    public static final gphl i;
    public static final gphl j;
    public static final gphl k;
    public static final gphl l;
    public static final hobf m;
    public final ggfp n;
    private static final fokg o;
    private static final fokg p;
    private final ggeo q;

    static {
        hobf.a = new fokg("google.internal.communications.instantmessaging.v1.SmartMessaging.");
        hobf.o = new fokg("google.internal.communications.instantmessaging.v1.SmartMessaging/");
        hobf.b = new hoaw();
        hobf.c = new hoax();
        hobf.d = new hoay();
        hobf.e = new hoaz();
        hobf.f = new hoba();
        hobf.g = new hobb();
        hobf.h = new hobc();
        hobf.i = new hobd();
        hobf.j = new hobe();
        hobf.k = new hoau();
        hobf.l = new hoav();
        hobf.m = new hobf();
        hobf.p = new fokg("instantmessaging-pa.googleapis.com");
    }

    private hobf() {
        ggdy ggdy0 = new ggdy();
        ggdy0.i("autopush-asan-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-asan-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("autopush-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("autopush-rcs-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("autopush-rcs-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-asan-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-asan-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-rcs-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-autopush-rcs-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-pa.mtls.googleapis.com");
        ggdy0.i("instantmessaging-preprod-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-preprod-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-hawk-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-hawk-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-heron-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-heron-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-west-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-rcs-us-west-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-sparrow-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-prod-sparrow-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-ap-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-ap-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-eu-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-eu-pa.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-us-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("instantmessaging-staging-users-rcs-us-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("preprod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-hawk-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-hawk-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-heron-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-heron-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-west-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-rcs-us-west-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("prod-sparrow-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("prod-sparrow-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-ap-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-ap-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-eu-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-eu-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-us-instantmessaging-pa.mtls.sandbox.googleapis.com");
        ggdy0.i("staging-users-rcs-us-instantmessaging-pa.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-asan-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-asan-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-rcs-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-autopush-rcs-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-preprod-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-hawk-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-hawk-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-heron-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-heron-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-west-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-rcs-us-west-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-sparrow-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-prod-sparrow-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-ap-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-ap-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-eu-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-eu-grpc.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-us-grpc.mtls.sandbox.googleapis.com");
        ggdy0.i("tachyon-playground-staging-users-rcs-us-grpc.sandbox.googleapis.com");
        ggdy0.i("zero-instantmessaging-pa.googleapis.com");
        ggdy0.i("zero-instantmessaging-pa.mtls.googleapis.com");
        ggdy0.i("instantmessaging-pa.googleapis.com");
        ggdy0.h();
        this.n = new ggfn().h();
        ggfp.O(hobf.b, hobf.c, hobf.d, hobf.e, hobf.f, hobf.g, new gphl[]{hobf.h, hobf.i, hobf.j, hobf.k, hobf.l});
        ggek ggek0 = new ggek();
        ggek0.i("GetContentWizardGifSuggestions", hobf.b);
        ggek0.i("GetContentDecoration", hobf.c);
        ggek0.i("GetSuggestions", hobf.d);
        ggek0.i("GetLocation", hobf.e);
        ggek0.i("CreateConversation", hobf.f);
        ggek0.i("GetConversationDetails", hobf.g);
        ggek0.i("SetConsent", hobf.h);
        ggek0.i("SignOutUser", hobf.i);
        ggek0.i("NotifyProvisioned", hobf.j);
        ggek0.i("GetProactiveStatus", hobf.k);
        ggek0.i("SetProactiveStatus", hobf.l);
        this.q = ggek0.b();
        new ggek().b();
    }

    @Override  // gphn
    public final fokg a() {
        return hobf.p;
    }

    @Override  // gphn
    public final gphl b(String s) {
        String s1 = hobf.o.a;
        if(s.startsWith(s1)) {
            String s2 = s.substring(s1.length());
            return this.q.containsKey(s2) ? ((gphl)this.q.get(s2)) : null;
        }
        return null;
    }
}

