import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public final class ifpl {
    private static final Map a;

    static {
        HashMap hashMap0 = new HashMap();
        ifpl.a = hashMap0;
        ifpa ifpa0 = new ifpa();
        hashMap0.put(ifhr.i, ifpa0);
        ifpa ifpa1 = new ifpa();
        hashMap0.put(ifhr.j, ifpa1);
        ifpf ifpf0 = new ifpf();
        hashMap0.put(ifhr.d, ifpf0);
        ifow ifow0 = new ifow();
        hashMap0.put(ifhr.e, ifow0);
        ifpj ifpj0 = new ifpj();
        hashMap0.put(ifhr.f, ifpj0);
        ifpk ifpk0 = new ifpk();
        hashMap0.put(ifhr.g, ifpk0);
        ifpj ifpj1 = new ifpj();
        hashMap0.put(ieth.a, ifpj1);
        ifpk ifpk1 = new ifpk();
        hashMap0.put(ieth.b, ifpk1);
        ifor ifor0 = new ifor();
        hashMap0.put(idvi.am, ifor0);
        ifov ifov0 = new ifov();
        hashMap0.put(ifhr.c, ifov0);
        ifpg ifpg0 = new ifpg();
        hashMap0.put(idtg.P, ifpg0);
        ifpg ifpg1 = new ifpg();
        hashMap0.put(idtg.Q, ifpg1);
        ifpg ifpg2 = new ifpg();
        hashMap0.put(idtg.R, ifpg2);
        ifpg ifpg3 = new ifpg();
        hashMap0.put(idtg.S, ifpg3);
        ifpg ifpg4 = new ifpg();
        hashMap0.put(idtg.T, ifpg4);
        ifpg ifpg5 = new ifpg();
        hashMap0.put(idtg.U, ifpg5);
        ifpg ifpg6 = new ifpg();
        hashMap0.put(idtg.V, ifpg6);
        ifpg ifpg7 = new ifpg();
        hashMap0.put(idtg.W, ifpg7);
        ifpg ifpg8 = new ifpg();
        hashMap0.put(idtg.X, ifpg8);
        ifpg ifpg9 = new ifpg();
        hashMap0.put(idtg.Y, ifpg9);
        ifpg ifpg10 = new ifpg();
        hashMap0.put(idtg.Z, ifpg10);
        ifpg ifpg11 = new ifpg();
        hashMap0.put(idtg.aa, ifpg11);
        ifpg ifpg12 = new ifpg();
        hashMap0.put(idtg.ab, ifpg12);
        ifpg ifpg13 = new ifpg();
        hashMap0.put(idtg.ac, ifpg13);
        ifpg ifpg14 = new ifpg();
        hashMap0.put(idtg.ad, ifpg14);
        ifpg ifpg15 = new ifpg();
        hashMap0.put(idtg.ae, ifpg15);
        ifpg ifpg16 = new ifpg();
        hashMap0.put(idtg.af, ifpg16);
        ifpg ifpg17 = new ifpg();
        hashMap0.put(idtg.ag, ifpg17);
        ifpg ifpg18 = new ifpg();
        hashMap0.put(idtg.ah, ifpg18);
        ifpg ifpg19 = new ifpg();
        hashMap0.put(idtg.am, ifpg19);
        ifpg ifpg20 = new ifpg();
        hashMap0.put(idtg.an, ifpg20);
        ifpg ifpg21 = new ifpg();
        hashMap0.put(idtg.as, ifpg21);
        ifpg ifpg22 = new ifpg();
        hashMap0.put(idtg.at, ifpg22);
        ifpg ifpg23 = new ifpg();
        hashMap0.put(idtg.ay, ifpg23);
        ifpg ifpg24 = new ifpg();
        hashMap0.put(idtg.az, ifpg24);
        ifpg ifpg25 = new ifpg();
        hashMap0.put(idtg.aC, ifpg25);
        ifpg ifpg26 = new ifpg();
        hashMap0.put(idtg.aB, ifpg26);
        ifpg ifpg27 = new ifpg();
        hashMap0.put(idtg.aI, ifpg27);
        ifpg ifpg28 = new ifpg();
        hashMap0.put(idtg.aH, ifpg28);
        ifpg ifpg29 = new ifpg();
        hashMap0.put(idtg.aE, ifpg29);
        ifpg ifpg30 = new ifpg();
        hashMap0.put(idtg.aD, ifpg30);
        ifpg ifpg31 = new ifpg();
        hashMap0.put(idtg.aK, ifpg31);
        ifpg ifpg32 = new ifpg();
        hashMap0.put(idtg.aJ, ifpg32);
        ifpg ifpg33 = new ifpg();
        hashMap0.put(idtg.aG, ifpg33);
        ifpg ifpg34 = new ifpg();
        hashMap0.put(idtg.aF, ifpg34);
        ifpg ifpg35 = new ifpg();
        hashMap0.put(idtg.aM, ifpg35);
        ifpg ifpg36 = new ifpg();
        hashMap0.put(idtg.aL, ifpg36);
        hashMap0.put(new idqg("1.3.9999.6.4.10"), new ifpg());
        ifom ifom0 = new ifom();
        hashMap0.put(idtg.bC, ifom0);
        ifom ifom1 = new ifom();
        hashMap0.put(idtg.bD, ifom1);
        ifom ifom2 = new ifom();
        hashMap0.put(idtg.bE, ifom2);
        ifom ifom3 = new ifom();
        hashMap0.put(idtg.bF, ifom3);
        ifom ifom4 = new ifom();
        hashMap0.put(idtg.bG, ifom4);
        ifom ifom5 = new ifom();
        hashMap0.put(idtg.bH, ifom5);
        ifom ifom6 = new ifom();
        hashMap0.put(idtg.bI, ifom6);
        ifom ifom7 = new ifom();
        hashMap0.put(idtg.bJ, ifom7);
        ifom ifom8 = new ifom();
        hashMap0.put(idtg.bK, ifom8);
        ifom ifom9 = new ifom();
        hashMap0.put(idtg.bL, ifom9);
        ifop ifop0 = new ifop();
        hashMap0.put(idtg.bN, ifop0);
        ifop ifop1 = new ifop();
        hashMap0.put(idtg.bO, ifop1);
        ifop ifop2 = new ifop();
        hashMap0.put(idtg.bP, ifop2);
        ifop ifop3 = new ifop();
        hashMap0.put(idtg.bQ, ifop3);
        ifop ifop4 = new ifop();
        hashMap0.put(idtg.bR, ifop4);
        ifop ifop5 = new ifop();
        hashMap0.put(idtg.bS, ifop5);
        ifpc ifpc0 = new ifpc();
        hashMap0.put(idtg.bU, ifpc0);
        ifpc ifpc1 = new ifpc();
        hashMap0.put(idtg.bV, ifpc1);
        ifpc ifpc2 = new ifpc();
        hashMap0.put(idtg.bW, ifpc2);
        ifpc ifpc3 = new ifpc();
        hashMap0.put(idtg.bX, ifpc3);
        ifpc ifpc4 = new ifpc();
        hashMap0.put(idtg.bY, ifpc4);
        ifpc ifpc5 = new ifpc();
        hashMap0.put(idtg.bZ, ifpc5);
        ifpc ifpc6 = new ifpc();
        hashMap0.put(idtg.ca, ifpc6);
        ifpc ifpc7 = new ifpc();
        hashMap0.put(idtg.cb, ifpc7);
        ifpc ifpc8 = new ifpc();
        hashMap0.put(idtg.cc, ifpc8);
        ifpc ifpc9 = new ifpc();
        hashMap0.put(idtg.cd, ifpc9);
        ifpc ifpc10 = new ifpc();
        hashMap0.put(idtg.ce, ifpc10);
        ifpc ifpc11 = new ifpc();
        hashMap0.put(idtg.cf, ifpc11);
        ifpc ifpc12 = new ifpc();
        hashMap0.put(idtg.cg, ifpc12);
        ifpc ifpc13 = new ifpc();
        hashMap0.put(idtg.ch, ifpc13);
        ifpc ifpc14 = new ifpc();
        hashMap0.put(idtg.ci, ifpc14);
        ifpc ifpc15 = new ifpc();
        hashMap0.put(idtg.cj, ifpc15);
        ifpc ifpc16 = new ifpc();
        hashMap0.put(idtg.ck, ifpc16);
        ifpc ifpc17 = new ifpc();
        hashMap0.put(idtg.cl, ifpc17);
        ifoz ifoz0 = new ifoz();
        hashMap0.put(idtg.aP, ifoz0);
        ifoz ifoz1 = new ifoz();
        hashMap0.put(idtg.aQ, ifoz1);
        ifoz ifoz2 = new ifoz();
        hashMap0.put(idtg.aR, ifoz2);
        ifoz ifoz3 = new ifoz();
        hashMap0.put(idtg.aS, ifoz3);
        ifoz ifoz4 = new ifoz();
        hashMap0.put(idtg.aT, ifoz4);
        ifoz ifoz5 = new ifoz();
        hashMap0.put(idtg.aU, ifoz5);
        ifoz ifoz6 = new ifoz();
        hashMap0.put(idtg.aV, ifoz6);
        ifoz ifoz7 = new ifoz();
        hashMap0.put(idtg.aW, ifoz7);
        ifoz ifoz8 = new ifoz();
        hashMap0.put(idtg.aX, ifoz8);
        ifoz ifoz9 = new ifoz();
        hashMap0.put(idtg.aY, ifoz9);
        ifoz ifoz10 = new ifoz();
        hashMap0.put(idtg.aZ, ifoz10);
        ifoz ifoz11 = new ifoz();
        hashMap0.put(idtg.ba, ifoz11);
        ifoy ifoy0 = new ifoy();
        hashMap0.put(idtg.co, ifoy0);
        ifoy ifoy1 = new ifoy();
        hashMap0.put(idtg.cp, ifoy1);
        ifoy ifoy2 = new ifoy();
        hashMap0.put(idtg.cq, ifoy2);
        ifoy ifoy3 = new ifoy();
        hashMap0.put(idtg.cs, ifoy3);
        ifoy ifoy4 = new ifoy();
        hashMap0.put(idtg.cr, ifoy4);
        ifoy ifoy5 = new ifoy();
        hashMap0.put(idtg.ct, ifoy5);
        ifoo ifoo0 = new ifoo();
        hashMap0.put(idtg.bg, ifoo0);
        ifoo ifoo1 = new ifoo();
        hashMap0.put(idtg.bh, ifoo1);
        ifot ifot0 = new ifot();
        hashMap0.put(idur.aT, ifot0);
        ifot ifot1 = new ifot();
        hashMap0.put(idur.aU, ifot1);
        ifot ifot2 = new ifot();
        hashMap0.put(idur.aV, ifot2);
        ifot ifot3 = new ifot();
        hashMap0.put(idtg.cv, ifot3);
        ifot ifot4 = new ifot();
        hashMap0.put(idtg.cw, ifot4);
        ifot ifot5 = new ifot();
        hashMap0.put(idtg.cx, ifot5);
        ifox ifox0 = new ifox();
        hashMap0.put(idtg.cA, ifox0);
        ifox ifox1 = new ifox();
        hashMap0.put(idtg.cB, ifox1);
        ifox ifox2 = new ifox();
        hashMap0.put(idtg.cC, ifox2);
        ifox ifox3 = new ifox();
        hashMap0.put(idtg.cD, ifox3);
        ifox ifox4 = new ifox();
        hashMap0.put(idtg.cE, ifox4);
        ifox ifox5 = new ifox();
        hashMap0.put(idtg.cF, ifox5);
        ifpe ifpe0 = new ifpe();
        hashMap0.put(idtg.cH, ifpe0);
        ifpe ifpe1 = new ifpe();
        hashMap0.put(idtg.cI, ifpe1);
        ifpe ifpe2 = new ifpe();
        hashMap0.put(idtg.cJ, ifpe2);
        ifpe ifpe3 = new ifpe();
        hashMap0.put(idtg.cK, ifpe3);
        ifpe ifpe4 = new ifpe();
        hashMap0.put(idtg.cL, ifpe4);
        ifpe ifpe5 = new ifpe();
        hashMap0.put(idtg.cM, ifpe5);
        ifos ifos0 = new ifos();
        hashMap0.put(idur.ao, ifos0);
        ifos ifos1 = new ifos();
        hashMap0.put(idur.ap, ifos1);
        ifos ifos2 = new ifos();
        hashMap0.put(idur.aq, ifos2);
        ifos ifos3 = new ifos();
        hashMap0.put(idur.ar, ifos3);
        ifos ifos4 = new ifos();
        hashMap0.put(idur.as, ifos4);
        ifos ifos5 = new ifos();
        hashMap0.put(idur.at, ifos5);
        ifon ifon0 = new ifon();
        hashMap0.put(idtg.bj, ifon0);
        ifon ifon1 = new ifon();
        hashMap0.put(idtg.bk, ifon1);
        ifon ifon2 = new ifon();
        hashMap0.put(idtg.bl, ifon2);
        ifon ifon3 = new ifon();
        hashMap0.put(idtg.bm, ifon3);
        ifon ifon4 = new ifon();
        hashMap0.put(idtg.bn, ifon4);
        ifon ifon5 = new ifon();
        hashMap0.put(idtg.bo, ifon5);
        ifol ifol0 = new ifol();
        hashMap0.put(idtg.cO, ifol0);
        ifol ifol1 = new ifol();
        hashMap0.put(idtg.cP, ifol1);
        ifol ifol2 = new ifol();
        hashMap0.put(idtg.cQ, ifol2);
        ifoq ifoq0 = new ifoq();
        hashMap0.put(idtg.cS, ifoq0);
        ifoq ifoq1 = new ifoq();
        hashMap0.put(idtg.cT, ifoq1);
        ifoq ifoq2 = new ifoq();
        hashMap0.put(idtg.cU, ifoq2);
        ifpb ifpb0 = new ifpb();
        hashMap0.put(idtg.bq, ifpb0);
        ifpb ifpb1 = new ifpb();
        hashMap0.put(idtg.br, ifpb1);
        ifpb ifpb2 = new ifpb();
        hashMap0.put(idtg.bs, ifpb2);
        ifpb ifpb3 = new ifpb();
        hashMap0.put(idtg.bt, ifpb3);
        ifpb ifpb4 = new ifpb();
        hashMap0.put(idtg.bu, ifpb4);
        ifpb ifpb5 = new ifpb();
        hashMap0.put(idtg.bv, ifpb5);
        ifpd ifpd0 = new ifpd();
        hashMap0.put(idur.au, ifpd0);
        ifpd ifpd1 = new ifpd();
        hashMap0.put(idur.av, ifpd1);
        ifpd ifpd2 = new ifpd();
        hashMap0.put(idur.aw, ifpd2);
        ifpd ifpd3 = new ifpd();
        hashMap0.put(idur.ax, ifpd3);
        ifpd ifpd4 = new ifpd();
        hashMap0.put(idur.ay, ifpd4);
        ifpd ifpd5 = new ifpd();
        hashMap0.put(idur.az, ifpd5);
        ifpd ifpd6 = new ifpd();
        hashMap0.put(idur.aA, ifpd6);
        ifpd ifpd7 = new ifpd();
        hashMap0.put(idur.aB, ifpd7);
        ifpd ifpd8 = new ifpd();
        hashMap0.put(idur.aC, ifpd8);
        ifpd ifpd9 = new ifpd();
        hashMap0.put(idur.aD, ifpd9);
        ifpd ifpd10 = new ifpd();
        hashMap0.put(idur.aE, ifpd10);
        ifpd ifpd11 = new ifpd();
        hashMap0.put(idur.aF, ifpd11);
        ifpd ifpd12 = new ifpd();
        hashMap0.put(idur.aG, ifpd12);
        ifpd ifpd13 = new ifpd();
        hashMap0.put(idur.aH, ifpd13);
        ifpd ifpd14 = new ifpd();
        hashMap0.put(idur.aI, ifpd14);
        ifpd ifpd15 = new ifpd();
        hashMap0.put(idur.aJ, ifpd15);
        ifpd ifpd16 = new ifpd();
        hashMap0.put(idur.aK, ifpd16);
        ifpd ifpd17 = new ifpd();
        hashMap0.put(idur.aL, ifpd17);
        ifpd ifpd18 = new ifpd();
        hashMap0.put(idur.aM, ifpd18);
        ifpd ifpd19 = new ifpd();
        hashMap0.put(idur.aN, ifpd19);
        ifpd ifpd20 = new ifpd();
        hashMap0.put(idur.aO, ifpd20);
        ifpd ifpd21 = new ifpd();
        hashMap0.put(idur.aP, ifpd21);
        ifpd ifpd22 = new ifpd();
        hashMap0.put(idur.aQ, ifpd22);
        ifpd ifpd23 = new ifpd();
        hashMap0.put(idur.aR, ifpd23);
        ifou ifou0 = new ifou();
        hashMap0.put(idtg.cW, ifou0);
        ifou ifou1 = new ifou();
        hashMap0.put(idtg.cX, ifou1);
        ifou ifou2 = new ifou();
        hashMap0.put(idtg.cY, ifou2);
        ifou ifou3 = new ifou();
        hashMap0.put(idtg.cZ, ifou3);
        ifph ifph0 = new ifph();
        hashMap0.put(idtg.dc, ifph0);
        ifph ifph1 = new ifph();
        hashMap0.put(idtg.db, ifph1);
        ifph ifph2 = new ifph();
        hashMap0.put(idtg.de, ifph2);
        ifph ifph3 = new ifph();
        hashMap0.put(idtg.dd, ifph3);
        ifph ifph4 = new ifph();
        hashMap0.put(idtg.dg, ifph4);
        ifph ifph5 = new ifph();
        hashMap0.put(idtg.df, ifph5);
        ifph ifph6 = new ifph();
        hashMap0.put(idtg.di, ifph6);
        ifph ifph7 = new ifph();
        hashMap0.put(idtg.dh, ifph7);
        ifph ifph8 = new ifph();
        hashMap0.put(idtg.dk, ifph8);
        ifph ifph9 = new ifph();
        hashMap0.put(idtg.dj, ifph9);
        ifph ifph10 = new ifph();
        hashMap0.put(idtg.dm, ifph10);
        ifph ifph11 = new ifph();
        hashMap0.put(idtg.dl, ifph11);
        ifph ifph12 = new ifph();
        hashMap0.put(idtg.do, ifph12);
        ifph ifph13 = new ifph();
        hashMap0.put(idtg.dn, ifph13);
        ifph ifph14 = new ifph();
        hashMap0.put(idtg.dq, ifph14);
        ifph ifph15 = new ifph();
        hashMap0.put(idtg.dp, ifph15);
        ifph ifph16 = new ifph();
        hashMap0.put(idtg.ds, ifph16);
        ifph ifph17 = new ifph();
        hashMap0.put(idtg.dr, ifph17);
        ifph ifph18 = new ifph();
        hashMap0.put(idtg.du, ifph18);
        ifph ifph19 = new ifph();
        hashMap0.put(idtg.dt, ifph19);
        ifph ifph20 = new ifph();
        hashMap0.put(idtg.dw, ifph20);
        ifph ifph21 = new ifph();
        hashMap0.put(idtg.dv, ifph21);
        ifph ifph22 = new ifph();
        hashMap0.put(idtg.dy, ifph22);
        ifph ifph23 = new ifph();
        hashMap0.put(idtg.dx, ifph23);
        ifph ifph24 = new ifph();
        hashMap0.put(idtg.dA, ifph24);
        ifph ifph25 = new ifph();
        hashMap0.put(idtg.dz, ifph25);
        ifph ifph26 = new ifph();
        hashMap0.put(idtg.dC, ifph26);
        ifph ifph27 = new ifph();
        hashMap0.put(idtg.dB, ifph27);
        ifph ifph28 = new ifph();
        hashMap0.put(idtg.dE, ifph28);
        ifph ifph29 = new ifph();
        hashMap0.put(idtg.dD, ifph29);
        ifph ifph30 = new ifph();
        hashMap0.put(idtg.dG, ifph30);
        ifph ifph31 = new ifph();
        hashMap0.put(idtg.dF, ifph31);
        ifph ifph32 = new ifph();
        hashMap0.put(idtg.dI, ifph32);
        ifph ifph33 = new ifph();
        hashMap0.put(idtg.dH, ifph33);
        ifph ifph34 = new ifph();
        hashMap0.put(idtg.dK, ifph34);
        ifph ifph35 = new ifph();
        hashMap0.put(idtg.dJ, ifph35);
        ifph ifph36 = new ifph();
        hashMap0.put(idtg.dM, ifph36);
        ifph ifph37 = new ifph();
        hashMap0.put(idtg.dL, ifph37);
        ifph ifph38 = new ifph();
        hashMap0.put(idtg.dO, ifph38);
        ifph ifph39 = new ifph();
        hashMap0.put(idtg.dN, ifph39);
        ifph ifph40 = new ifph();
        hashMap0.put(idtg.dQ, ifph40);
        ifph ifph41 = new ifph();
        hashMap0.put(idtg.dP, ifph41);
        ifph ifph42 = new ifph();
        hashMap0.put(idtg.dS, ifph42);
        ifph ifph43 = new ifph();
        hashMap0.put(idtg.dR, ifph43);
    }

    public static ienr a(idzh idzh0) {
        if(idzh0 == null) {
            throw new IllegalArgumentException("keyInfo argument null");
        }
        idyk idyk0 = idzh0.a;
        ifpi ifpi0 = (ifpi)ifpl.a.get(idyk0.a);
        if(ifpi0 != null) {
            return ifpi0.a(idzh0);
        }
        throw new IOException("algorithm identifier in public key not recognised: " + idyk0.a);
    }
}

