public interface igou {
    public static final ignf A;
    public static final ignf B;
    public static final ignf C;
    public static final ignf D;
    public static final ignf E;
    public static final ignf F;
    public static final ignf G;
    public static final ignf H;
    public static final ignf I;
    public static final ignf a;
    public static final ignf b;
    public static final ignf c;
    public static final ignf d;
    public static final ignf e;
    public static final ignf f;
    public static final ignf g;
    public static final ignf h;
    public static final ignf i;
    public static final ignf j;
    public static final ignf k;
    public static final ignf l;
    public static final ignf m;
    public static final ignf n;
    public static final ignf o;
    public static final ignf p;
    public static final ignf q;
    public static final ignf r;
    public static final ignf s;
    public static final ignf t;
    public static final ignf u;
    public static final ignf v;
    public static final ignf w;
    public static final ignf x;
    public static final ignf y;
    public static final ignf z;

    static {
        ignf ignf0 = new ignf("1.3.132.0");
        igou.a = ignf0;
        igou.b = new ignf(ignf0, "1");
        igou.c = new ignf(ignf0, "2");
        igou.d = new ignf(ignf0, "3");
        igou.e = new ignf(ignf0, "4");
        igou.f = new ignf(ignf0, "5");
        igou.g = new ignf(ignf0, "6");
        igou.h = new ignf(ignf0, "7");
        igou.i = new ignf(ignf0, "8");
        igou.j = new ignf(ignf0, "9");
        igou.k = new ignf(ignf0, "10");
        igou.l = new ignf(ignf0, "15");
        igou.m = new ignf(ignf0, "16");
        igou.n = new ignf(ignf0, "17");
        igou.o = new ignf(ignf0, "22");
        igou.p = new ignf(ignf0, "23");
        igou.q = new ignf(ignf0, "24");
        igou.r = new ignf(ignf0, "25");
        igou.s = new ignf(ignf0, "26");
        igou.t = new ignf(ignf0, "27");
        igou.u = new ignf(ignf0, "28");
        igou.v = new ignf(ignf0, "29");
        igou.w = new ignf(ignf0, "30");
        igou.x = new ignf(ignf0, "31");
        igou.y = new ignf(ignf0, "32");
        igou.z = new ignf(ignf0, "33");
        igou.A = new ignf(ignf0, "34");
        igou.B = new ignf(ignf0, "35");
        igou.C = new ignf(ignf0, "36");
        igou.D = new ignf(ignf0, "37");
        igou.E = new ignf(ignf0, "38");
        igou.F = new ignf(ignf0, "39");
        igou.G = igpb.r;
        igou.H = igpb.s;
        ignf ignf1 = new ignf("1.3.132.1");
        igou.I = ignf1;
        new ignf(ignf1, "11.0");
        new ignf(ignf1, "11.1");
        new ignf(ignf1, "11.2");
        new ignf(ignf1, "11.3");
        new ignf(ignf1, "14.0");
        new ignf(ignf1, "14.1");
        new ignf(ignf1, "14.2");
        new ignf(ignf1, "14.3");
        new ignf(ignf1, "15.0");
        new ignf(ignf1, "15.1");
        new ignf(ignf1, "15.2");
        new ignf(ignf1, "15.3");
        new ignf(ignf1, "16.0");
        new ignf(ignf1, "16.1");
        new ignf(ignf1, "16.2");
        new ignf(ignf1, "16.3");
    }
}

