public interface igpb {
    public static final ignf f;
    public static final ignf g;
    public static final ignf h;
    public static final ignf i;
    public static final ignf j;
    public static final ignf k;
    public static final ignf l;
    public static final ignf m;
    public static final ignf n;
    public static final ignf o;
    public static final ignf p;
    public static final ignf q;
    public static final ignf r;
    public static final ignf s;
    public static final ignf t;
    public static final ignf u;
    public static final ignf v;
    public static final ignf w;
    public static final ignf x;

    static {
        ignf ignf0 = new ignf("1.2.840.10045");
        igpb.f = ignf0;
        ignf ignf1 = new ignf(ignf0, "1");
        igpb.g = ignf1;
        igpb.h = new ignf(ignf1, "1");
        ignf ignf2 = new ignf(ignf1, "2");
        igpb.i = ignf2;
        new ignf(ignf2, "3.1");
        igpb.j = new ignf(ignf2, "3.2");
        igpb.k = new ignf(ignf2, "3.3");
        ignf ignf3 = new ignf(ignf0, "4");
        igpb.l = ignf3;
        new ignf(ignf3, "1");
        ignf ignf4 = new ignf(ignf0, "2");
        igpb.m = ignf4;
        new ignf(ignf4, "1");
        ignf ignf5 = new ignf(ignf3, "3");
        igpb.n = ignf5;
        new ignf(ignf5, "1");
        new ignf(ignf5, "2");
        new ignf(ignf5, "3");
        new ignf(ignf5, "4");
        ignf ignf6 = new ignf(ignf0, "3");
        igpb.o = ignf6;
        ignf ignf7 = new ignf(ignf6, "0");
        igpb.p = ignf7;
        new ignf(ignf7, "1");
        new ignf(ignf7, "2");
        new ignf(ignf7, "3");
        new ignf(ignf7, "4");
        new ignf(ignf7, "5");
        new ignf(ignf7, "6");
        new ignf(ignf7, "7");
        new ignf(ignf7, "8");
        new ignf(ignf7, "9");
        new ignf(ignf7, "10");
        new ignf(ignf7, "11");
        new ignf(ignf7, "12");
        new ignf(ignf7, "13");
        new ignf(ignf7, "14");
        new ignf(ignf7, "15");
        new ignf(ignf7, "16");
        new ignf(ignf7, "17");
        new ignf(ignf7, "18");
        new ignf(ignf7, "19");
        new ignf(ignf7, "20");
        ignf ignf8 = new ignf(ignf6, "1");
        igpb.q = ignf8;
        igpb.r = new ignf(ignf8, "1");
        new ignf(ignf8, "2");
        new ignf(ignf8, "3");
        new ignf(ignf8, "4");
        new ignf(ignf8, "5");
        new ignf(ignf8, "6");
        igpb.s = new ignf(ignf8, "7");
        new ignf("1.2.840.10040.4.1");
        new ignf("1.2.840.10040.4.3");
        ignf ignf9 = new ignf("1.3.133.16.840.63.0");
        igpb.t = ignf9;
        new ignf(ignf9, "2");
        new ignf(ignf9, "3");
        new ignf(ignf9, "16");
        ignf ignf10 = new ignf("1.2.840.10046");
        igpb.u = ignf10;
        new ignf(ignf10, "2.1");
        ignf ignf11 = new ignf(ignf10, "3");
        igpb.v = ignf11;
        new ignf(ignf11, "1");
        new ignf(ignf11, "2");
        new ignf(ignf11, "3");
        new ignf(ignf11, "4");
        new ignf(ignf11, "5");
        new ignf(ignf11, "6");
        new ignf(ignf11, "7");
        new ignf(ignf11, "8");
        ignf ignf12 = new ignf("1.3.133.16.840.9.44");
        igpb.w = ignf12;
        ignf ignf13 = new ignf(ignf12, "1");
        igpb.x = ignf13;
        new ignf(ignf13, "1");
        new ignf(ignf13, "2");
    }
}

