public final class iuz {
    public static final ivi A;
    public static final ivi B;
    public static final ivi C;
    public static final ivi D;
    public static final ivi E;
    public static final ivi F;
    public static final ivi G;
    public static final ivi H;
    public static final ivi I;
    public static final ivi J;
    public static final ivi K;
    public static final ivi L;
    public static final ivi M;
    public static final ivi N;
    public static final ivi O;
    public static final ivi a;
    public static final ivi b;
    public static final ivi c;
    public static final ivi d;
    public static final ivi e;
    public static final ivi f;
    public static final ivi g;
    public static final ivi h;
    public static final ivi i;
    public static final ivi j;
    public static final ivi k;
    public static final ivi l;
    public static final ivi m;
    public static final ivi n;
    public static final ivi o;
    public static final ivi p;
    public static final ivi q;
    public static final ivi r;
    public static final ivi s;
    public static final ivi t;
    public static final ivi u;
    public static final ivi v;
    public static final ivi w;
    public static final ivi x;
    public static final ivi y;
    public static final ivi z;

    static {
        iuz.a = new ivi("ContentDescription", true, ium.a);
        iuz.b = new ivi("StateDescription", null);
        iuz.c = new ivi("ProgressBarRangeInfo", null);
        iuz.d = new ivi("PaneTitle", true, iut.a);
        iuz.e = new ivi("SelectableGroup", null);
        iuz.f = new ivi("CollectionInfo", null);
        iuz.g = new ivi("CollectionItemInfo", null);
        iuz.h = new ivi("Heading", null);
        iuz.i = new ivi("Disabled", null);
        iuz.j = new ivi("LiveRegion", null);
        iuz.k = new ivi("Focused", null);
        iuz.l = new ivi("IsContainer", null);
        iuz.m = new ivi("IsTraversalGroup");
        iuz.n = new ivi("IsSensitiveData");
        iuz.o = new ivi("InvisibleToUser", iup.a);
        iuz.p = new ivi("HideFromAccessibility", iuo.a);
        iuz.q = new ivi("ContentType", iun.a);
        iuz.r = new ivi("ContentDataType", iul.a);
        iuz.s = new ivi("TraversalIndex", iuy.a);
        iuz.t = new ivi("HorizontalScrollAxisRange", null);
        iuz.u = new ivi("VerticalScrollAxisRange", null);
        iuz.v = new ivi("IsPopup", true, iur.a);
        iuz.w = new ivi("IsDialog", true, iuq.a);
        iuz.x = new ivi("Role", true, iuu.a);
        iuz.y = new ivi("TestTag", false, iuw.a);
        iuz.z = new ivi("LinkTestMarker", false, ius.a);
        iuz.A = new ivi("Text", true, iux.a);
        iuz.B = new ivi("TextSubstitution");
        iuz.C = new ivi("IsShowingTextSubstitution");
        iuz.D = new ivi("InputText", null);
        iuz.E = new ivi("EditableText", null);
        iuz.F = new ivi("TextSelectionRange", null);
        iuz.G = new ivi("ImeAction", null);
        iuz.H = new ivi("Selected", null);
        iuz.I = new ivi("ToggleableState", null);
        iuz.J = new ivi("Password", null);
        iuz.K = new ivi("Error", null);
        iuz.L = new ivi("IndexForKey");
        iuz.M = new ivi("IsEditable");
        iuz.N = new ivi("MaxTextLength");
        iuz.O = new ivi("Shape", false, iuv.a);
    }
}

