public enum tgj {
    PPMC4("PPMC4"),
    VCBP10("VCBP10"),
    VCBP12_CVN50("VCBP12_CVN50"),
    VCPA21("VCPA21"),
    DISCOVER_ZIP("DISCOVER_ZIP"),
    EXPRESSPAY("EXPRESSPAY"),
    EXPRESSPAY_CVN49("EXPRESSPAY_CVN49"),
    PAYPAL("GENERIC"),
    EFTPOS("EFTPOS"),
    DCBP_PAS("DCBP_PAS"),
    GENERIC("GENERIC"),
    PLASTIC_DISCOVER("PLASTIC_DISCOVER"),
    GENERIC_VISA("GENERIC_VISA"),
    GENERIC_MDA("GENERIC_MDA"),
    GENERIC_MASTERCARD("GENERIC_MASTERCARD"),
    GENERIC_INTERAC("GENERIC_INTERAC"),
    INTERAC_FLASH("INTERAC_CMDA");

    public final String r;

    private tgj(String s1) {
        this.r = s1;
    }
}

