package com.google.android.gms.ads.internal.request;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable.Creator;
import baub;
import com.google.android.gms.ads.internal.client.AdRequestParcel;
import com.google.android.gms.ads.internal.client.AdSizeParcel;
import com.google.android.gms.ads.internal.client.IconAdOptionsParcel;
import com.google.android.gms.ads.internal.formats.NativeAdOptionsParcel;
import com.google.android.gms.ads.internal.instream.InstreamAdConfigurationParcel;
import com.google.android.gms.ads.internal.util.client.VersionInfoParcel;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import j..util.DesugarCollections;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public final class AdRequestInfoParcel extends AbstractSafeParcelable {
    public final long A;
    public final String B;
    public final float C;
    public static final Parcelable.Creator CREATOR;
    public final int D;
    public final int E;
    public final boolean F;
    public final String G;
    public final boolean H;
    public final String I;
    public final boolean J;
    public final int K;
    public final Bundle L;
    public final String M;
    public final IconAdOptionsParcel N;
    public final boolean O;
    public final Bundle P;
    public final String Q;
    public final String R;
    public final String S;
    public final boolean T;
    public final List U;
    public final String V;
    public final List W;
    public final int X;
    public final boolean Y;
    public final boolean Z;
    public final int a;
    public final boolean aa;
    public final ArrayList ab;
    public final String ac;
    public final InstreamAdConfigurationParcel ad;
    public final String ae;
    public final Bundle af;
    public final Bundle b;
    public final AdRequestParcel c;
    public final AdSizeParcel d;
    public final String e;
    public final ApplicationInfo f;
    public final PackageInfo g;
    public final String h;
    public final String i;
    public final String j;
    public final VersionInfoParcel k;
    public final Bundle l;
    public final int m;
    public final List n;
    public final Bundle o;
    public final boolean p;
    public final int q;
    public final int r;
    public final float s;
    public final String t;
    public final long u;
    public final String v;
    public final List w;
    public final String x;
    public final NativeAdOptionsParcel y;
    public final List z;

    static {
        AdRequestInfoParcel.CREATOR = new a();
    }

    public AdRequestInfoParcel(int v, Bundle bundle0, AdRequestParcel adRequestParcel0, AdSizeParcel adSizeParcel0, String s, ApplicationInfo applicationInfo0, PackageInfo packageInfo0, String s1, String s2, String s3, VersionInfoParcel versionInfoParcel0, Bundle bundle1, int v1, List list0, Bundle bundle2, boolean z, int v2, int v3, float f, String s4, long v4, String s5, List list1, String s6, NativeAdOptionsParcel nativeAdOptionsParcel0, List list2, long v5, String s7, float f1, boolean z1, int v6, int v7, boolean z2, String s8, String s9, boolean z3, int v8, Bundle bundle3, String s10, IconAdOptionsParcel iconAdOptionsParcel0, boolean z4, Bundle bundle4, String s11, String s12, String s13, boolean z5, List list3, String s14, List list4, int v9, boolean z6, boolean z7, boolean z8, ArrayList arrayList0, String s15, InstreamAdConfigurationParcel instreamAdConfigurationParcel0, String s16, Bundle bundle5) {
        this.a = v;
        this.b = bundle0;
        this.c = adRequestParcel0;
        this.d = adSizeParcel0;
        this.e = s;
        this.f = applicationInfo0;
        this.g = packageInfo0;
        this.h = s1;
        this.i = s2;
        this.j = s3;
        this.k = versionInfoParcel0;
        this.l = bundle1;
        this.m = v1;
        this.n = list0;
        this.z = list2 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(list2);
        this.o = bundle2;
        this.p = z;
        this.q = v2;
        this.r = v3;
        this.s = f;
        this.t = s4;
        this.u = v4;
        this.v = s5;
        this.w = list1 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(list1);
        this.x = s6;
        this.y = nativeAdOptionsParcel0;
        this.A = v5;
        this.B = s7;
        this.C = f1;
        this.H = z1;
        this.D = v6;
        this.E = v7;
        this.F = z2;
        this.G = s8;
        this.I = s9;
        this.J = z3;
        this.K = v8;
        this.L = bundle3;
        this.M = s10;
        this.N = iconAdOptionsParcel0;
        this.O = z4;
        this.P = bundle4;
        this.Q = s11;
        this.R = s12;
        this.S = s13;
        this.T = z5;
        this.U = list3;
        this.V = s14;
        this.W = list4;
        this.X = v9;
        this.Y = z6;
        this.Z = z7;
        this.aa = z8;
        this.ab = arrayList0;
        this.ac = s15;
        this.ad = instreamAdConfigurationParcel0;
        this.ae = s16;
        this.af = bundle5;
    }

    @Override  // android.os.Parcelable
    public final void writeToParcel(Parcel parcel0, int v) {
        int v1 = baub.a(parcel0);
        baub.o(parcel0, 1, this.a);
        baub.g(parcel0, 2, this.b, false);
        baub.t(parcel0, 3, this.c, v, false);
        baub.t(parcel0, 4, this.d, v, false);
        baub.v(parcel0, 5, this.e, false);
        baub.t(parcel0, 6, this.f, v, false);
        baub.t(parcel0, 7, this.g, v, false);
        baub.v(parcel0, 8, this.h, false);
        baub.v(parcel0, 9, this.i, false);
        baub.v(parcel0, 10, this.j, false);
        baub.t(parcel0, 11, this.k, v, false);
        baub.g(parcel0, 12, this.l, false);
        baub.o(parcel0, 13, this.m);
        baub.x(parcel0, 14, this.n, false);
        baub.g(parcel0, 15, this.o, false);
        baub.e(parcel0, 16, this.p);
        baub.o(parcel0, 18, this.q);
        baub.o(parcel0, 19, this.r);
        baub.l(parcel0, 20, this.s);
        baub.v(parcel0, 21, this.t, false);
        baub.q(parcel0, 25, this.u);
        baub.v(parcel0, 26, this.v, false);
        baub.x(parcel0, 27, this.w, false);
        baub.v(parcel0, 28, this.x, false);
        baub.t(parcel0, 29, this.y, v, false);
        baub.x(parcel0, 30, this.z, false);
        baub.q(parcel0, 0x1F, this.A);
        baub.v(parcel0, 33, this.B, false);
        baub.l(parcel0, 34, this.C);
        baub.o(parcel0, 35, this.D);
        baub.o(parcel0, 36, this.E);
        baub.e(parcel0, 37, this.F);
        baub.v(parcel0, 39, this.G, false);
        baub.e(parcel0, 40, this.H);
        baub.v(parcel0, 41, this.I, false);
        baub.e(parcel0, 42, this.J);
        baub.o(parcel0, 43, this.K);
        baub.g(parcel0, 44, this.L, false);
        baub.v(parcel0, 45, this.M, false);
        baub.t(parcel0, 46, this.N, v, false);
        baub.e(parcel0, 0x2F, this.O);
        baub.g(parcel0, 0x30, this.P, false);
        baub.v(parcel0, 49, this.Q, false);
        baub.v(parcel0, 50, this.R, false);
        baub.v(parcel0, 51, this.S, false);
        baub.e(parcel0, 52, this.T);
        baub.E(parcel0, 53, this.U);
        baub.v(parcel0, 54, this.V, false);
        baub.x(parcel0, 55, this.W, false);
        baub.o(parcel0, 56, this.X);
        baub.e(parcel0, 57, this.Y);
        baub.e(parcel0, 58, this.Z);
        baub.e(parcel0, 59, this.aa);
        baub.x(parcel0, 60, this.ab, false);
        baub.v(parcel0, 61, this.ac, false);
        baub.t(parcel0, 0x3F, this.ad, v, false);
        baub.v(parcel0, 0x40, this.ae, false);
        baub.g(parcel0, 65, this.af, false);
        baub.c(parcel0, v1);
    }
}

